--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create sprite1
local sprite1 = cc.Sprite:create("game/texaspoker_std/resource/image/Nroom_headbg.png")
sprite1:setName("sprite1")
sprite1:setTag(154)
sprite1:setCascadeColorEnabled(true)
sprite1:setCascadeOpacityEnabled(true)
sprite1:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprite1)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(182.0000, 275.0000))
layout:setLeftMargin(-91.0000)
layout:setRightMargin(-91.0000)
layout:setTopMargin(-137.5.0000)
layout:setBottomMargin(-137.5.0000)
Node:addChild(sprite1)

--Create sprHead
local sprHead = cc.Sprite:create("game/texaspoker_std/resource/image/Nroom_headbg.png")
sprHead:setName("sprHead")
sprHead:setTag(168)
sprHead:setCascadeColorEnabled(true)
sprHead:setCascadeOpacityEnabled(true)
sprHead:setPosition(115.0000, 127.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprHead)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setSize(cc.size(230.0000, 254.0000))
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
sprite1:addChild(sprHead)

--Create labName
local labName = ccui.Text:create()
labName:ignoreContentAdaptWithSize(true)
labName:setTextAreaSize(cc.size(0, 0))
labName:setFontName("simhei.ttf")
labName:setFontSize(36)
labName:setString([[yang123456]])
labName:enableOutline(cc.c4b(255, 255, 255, 255), 1)
labName:setLayoutComponentEnabled(true)
labName:setName("labName")
labName:setTag(156)
labName:setCascadeColorEnabled(true)
labName:setCascadeOpacityEnabled(true)
labName:setAnchorPoint(0.0000, 0.5000)
labName:setPosition(-89.9689, 133.8571)
layout = ccui.LayoutComponent:bindLayoutComponent(labName)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(181.0000, 43.0000))
layout:setLeftMargin(-89.9689)
layout:setRightMargin(-91.0311)
layout:setTopMargin(-155.3571)
layout:setBottomMargin(112.3571)
Node:addChild(labName)

--Create labOwnChips
local labOwnChips = ccui.Text:create()
labOwnChips:ignoreContentAdaptWithSize(true)
labOwnChips:setTextAreaSize(cc.size(0, 0))
labOwnChips:setFontName("simhei.ttf")
labOwnChips:setFontSize(36)
labOwnChips:setString([[123456789]])
labOwnChips:enableOutline(cc.c4b(255, 255, 255, 255), 1)
labOwnChips:setLayoutComponentEnabled(true)
labOwnChips:setName("labOwnChips")
labOwnChips:setTag(157)
labOwnChips:setCascadeColorEnabled(true)
labOwnChips:setCascadeOpacityEnabled(true)
labOwnChips:setAnchorPoint(0.0000, 0.5000)
labOwnChips:setPosition(-79.5717, -131.4543)
layout = ccui.LayoutComponent:bindLayoutComponent(labOwnChips)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(162.0000, 43.0000))
layout:setLeftMargin(-79.5717)
layout:setRightMargin(-82.4283)
layout:setTopMargin(109.9543)
layout:setBottomMargin(-152.9543)
Node:addChild(labOwnChips)

--Create imgReady
local imgReady = cc.Sprite:create("game/texaspoker_std/resource/word/reday.png")
imgReady:setName("imgReady")
imgReady:setTag(159)
imgReady:setCascadeColorEnabled(true)
imgReady:setCascadeOpacityEnabled(true)
imgReady:setPosition(0.0000, 164.4075)
layout = ccui.LayoutComponent:bindLayoutComponent(imgReady)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(345.0000, 93.0000))
layout:setLeftMargin(-172.5000)
layout:setRightMargin(-172.5000)
layout:setTopMargin(-210.9075)
layout:setBottomMargin(117.9075)
Node:addChild(imgReady)

--Create sprBetType
local sprBetType = cc.Sprite:create("game/texaspoker_std/resource/word/dmz.png")
sprBetType:setName("sprBetType")
sprBetType:setTag(167)
sprBetType:setCascadeColorEnabled(true)
sprBetType:setCascadeOpacityEnabled(true)
sprBetType:setPosition(135.9896, 106.8884)
layout = ccui.LayoutComponent:bindLayoutComponent(sprBetType)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(78.0000, 26.0000))
layout:setLeftMargin(96.9896)
layout:setRightMargin(-174.9896)
layout:setTopMargin(-119.8884)
layout:setBottomMargin(93.8884)
Node:addChild(sprBetType)

--Create sprCard1
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/texaspoker_std/resource/effect/card_big.plist")
local sprCard1 = cc.Sprite:createWithSpriteFrameName("card_big1_55.png")
sprCard1:setName("sprCard1")
sprCard1:setTag(169)
sprCard1:setCascadeColorEnabled(true)
sprCard1:setCascadeOpacityEnabled(true)
sprCard1:setPosition(90.2659, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprCard1)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(145.0000, 187.0000))
layout:setLeftMargin(17.7659)
layout:setRightMargin(-162.7659)
layout:setTopMargin(-93.5000)
layout:setBottomMargin(-93.5000)
Node:addChild(sprCard1)

--Create imgFrame1
local imgFrame1 = cc.Sprite:create("game/texaspoker_std/resource/image/paikuang.png")
imgFrame1:setName("imgFrame1")
imgFrame1:setTag(10)
imgFrame1:setCascadeColorEnabled(true)
imgFrame1:setCascadeOpacityEnabled(true)
imgFrame1:setPosition(73.1923, 92.4228)
layout = ccui.LayoutComponent:bindLayoutComponent(imgFrame1)
layout:setPositionPercentX(0.5048)
layout:setPositionPercentY(0.4942)
layout:setSize(cc.size(145.0000, 187.0000))
layout:setLeftMargin(0.6923)
layout:setRightMargin(-0.6923)
layout:setTopMargin(1.0772)
layout:setBottomMargin(-1.0772)
sprCard1:addChild(imgFrame1)

--Create sprCard2
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/texaspoker_std/resource/effect/card_big.plist")
local sprCard2 = cc.Sprite:createWithSpriteFrameName("card_big1_55.png")
sprCard2:setName("sprCard2")
sprCard2:setTag(170)
sprCard2:setCascadeColorEnabled(true)
sprCard2:setCascadeOpacityEnabled(true)
sprCard2:setPosition(217.5327, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprCard2)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(145.0000, 187.0000))
layout:setLeftMargin(145.0327)
layout:setRightMargin(-290.0327)
layout:setTopMargin(-93.5000)
layout:setBottomMargin(-93.5000)
Node:addChild(sprCard2)

--Create imgFrame2
local imgFrame2 = cc.Sprite:create("game/texaspoker_std/resource/image/paikuang.png")
imgFrame2:setName("imgFrame2")
imgFrame2:setTag(11)
imgFrame2:setCascadeColorEnabled(true)
imgFrame2:setCascadeOpacityEnabled(true)
imgFrame2:setPosition(74.1900, 92.4200)
layout = ccui.LayoutComponent:bindLayoutComponent(imgFrame2)
layout:setPositionPercentX(0.5117)
layout:setPositionPercentY(0.4942)
layout:setSize(cc.size(145.0000, 187.0000))
layout:setLeftMargin(1.6900)
layout:setRightMargin(-1.6900)
layout:setTopMargin(1.0800)
layout:setBottomMargin(-1.0800)
sprCard2:addChild(imgFrame2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

