--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ImgBj
local ImgBj = ccui.ImageView:create()
ImgBj:ignoreContentAdaptWithSize(false)
ImgBj:loadTexture("game/baccarat_std/resource/image/shezd.png",0)
ImgBj:setLayoutComponentEnabled(true)
ImgBj:setName("ImgBj")
ImgBj:setTag(80)
ImgBj:setCascadeColorEnabled(true)
ImgBj:setCascadeOpacityEnabled(true)
ImgBj:setAnchorPoint(0.0000, 0.5000)
ImgBj:setPosition(2.2873, 0.3237)
layout = ccui.LayoutComponent:bindLayoutComponent(ImgBj)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(327.0000, 381.0000))
layout:setLeftMargin(2.2873)
layout:setRightMargin(-329.2873)
layout:setTopMargin(-190.8237)
layout:setBottomMargin(-190.1763)
Node:addChild(ImgBj)

--Create sbtn_Set
local sbtn_Set = ccui.CheckBox:create()
sbtn_Set:ignoreContentAdaptWithSize(false)
sbtn_Set:loadTextureBackGround("game/baccarat_std/resource/button/anchu.png",0)
sbtn_Set:loadTextureFrontCross("game/baccarat_std/resource/button/sh.png",0)
sbtn_Set:setLayoutComponentEnabled(true)
sbtn_Set:setName("sbtn_Set")
sbtn_Set:setTag(79)
sbtn_Set:setCascadeColorEnabled(true)
sbtn_Set:setCascadeOpacityEnabled(true)
sbtn_Set:setPosition(-50.3543, 2.5738)
layout = ccui.LayoutComponent:bindLayoutComponent(sbtn_Set)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(121.0000, 211.0000))
layout:setLeftMargin(-110.8543)
layout:setRightMargin(-10.1457)
layout:setTopMargin(-108.0738)
layout:setBottomMargin(-102.9262)
Node:addChild(sbtn_Set)

--Create btn_set
local btn_set = ccui.Button:create()
btn_set:ignoreContentAdaptWithSize(false)
btn_set:loadTextureNormal("game/baccarat_std/resource/button/sz.png",0)
btn_set:setTitleFontSize(14)
btn_set:setTitleColor(cc.c3b(65, 65, 70))
btn_set:setScale9Enabled(true)
btn_set:setCapInsets(cc.rect(15,11,212,76))
btn_set:setLayoutComponentEnabled(true)
btn_set:setName("btn_set")
btn_set:setTag(81)
btn_set:setCascadeColorEnabled(true)
btn_set:setCascadeOpacityEnabled(true)
btn_set:setPosition(180.0001, 79.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_set)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(242.0000, 98.0000))
layout:setLeftMargin(59.0001)
layout:setRightMargin(-301.0001)
layout:setTopMargin(-128.9999)
layout:setBottomMargin(30.9999)
Node:addChild(btn_set)

--Create btn_out
local btn_out = ccui.Button:create()
btn_out:ignoreContentAdaptWithSize(false)
btn_out:loadTextureNormal("game/baccarat_std/resource/button/tuic.png",0)
btn_out:setTitleFontSize(14)
btn_out:setTitleColor(cc.c3b(65, 65, 70))
btn_out:setScale9Enabled(true)
btn_out:setCapInsets(cc.rect(15,11,208,72))
btn_out:setLayoutComponentEnabled(true)
btn_out:setName("btn_out")
btn_out:setTag(82)
btn_out:setCascadeColorEnabled(true)
btn_out:setCascadeOpacityEnabled(true)
btn_out:setPosition(182.0001, -60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_out)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(238.0000, 94.0000))
layout:setLeftMargin(63.0001)
layout:setRightMargin(-301.0001)
layout:setTopMargin(13.0000)
layout:setBottomMargin(-107.0000)
Node:addChild(btn_out)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

