--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgPlayer
local imgPlayer = ccui.ImageView:create()
imgPlayer:ignoreContentAdaptWithSize(false)
imgPlayer:loadTexture("game/baccarat_std/resource/image/grxx1.png",0)
imgPlayer:setLayoutComponentEnabled(true)
imgPlayer:setName("imgPlayer")
imgPlayer:setTag(154)
imgPlayer:setCascadeColorEnabled(true)
imgPlayer:setCascadeOpacityEnabled(true)
imgPlayer:setPosition(-107.3981, 549.4332)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayer)
layout:setSize({width = 350.0000, height = 302.0000})
layout:setLeftMargin(-282.3981)
layout:setRightMargin(-67.6019)
layout:setTopMargin(-700.4332)
layout:setBottomMargin(398.4332)
Node:addChild(imgPlayer)

--Create sprPlayerHead
local sprPlayerHead = cc.Sprite:create("common/head_pic/115/0.png")
sprPlayerHead:setName("sprPlayerHead")
sprPlayerHead:setTag(149)
sprPlayerHead:setCascadeColorEnabled(true)
sprPlayerHead:setCascadeOpacityEnabled(true)
sprPlayerHead:setPosition(-135.4771, 621.3920)
layout = ccui.LayoutComponent:bindLayoutComponent(sprPlayerHead)
layout:setSize({width = 110.0000, height = 110.0000})
layout:setLeftMargin(-190.4771)
layout:setRightMargin(80.4771)
layout:setTopMargin(-676.3920)
layout:setBottomMargin(566.3920)
sprPlayerHead:setBlendFunc({src = 1, dst = 771})
Node:addChild(sprPlayerHead)

--Create fntChips
local fntChips = ccui.TextBMFont:create()
fntChips:setFntFile("game/baccarat_std/resource/number/playerNum.fnt")
fntChips:setString([[]])
fntChips:setLayoutComponentEnabled(true)
fntChips:setName("fntChips")
fntChips:setTag(150)
fntChips:setCascadeColorEnabled(true)
fntChips:setCascadeOpacityEnabled(true)
fntChips:setPosition(-125.0000, 440.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fntChips)
layout:setLeftMargin(-125.0000)
layout:setRightMargin(125.0000)
layout:setTopMargin(-440.0000)
layout:setBottomMargin(440.0000)
Node:addChild(fntChips)

--Create fntGold
local fntGold = ccui.TextBMFont:create()
fntGold:setFntFile("game/baccarat_std/resource/number/playerNum.fnt")
fntGold:setString([[]])
fntGold:setLayoutComponentEnabled(true)
fntGold:setName("fntGold")
fntGold:setTag(151)
fntGold:setCascadeColorEnabled(true)
fntGold:setCascadeOpacityEnabled(true)
fntGold:setPosition(-133.2580, 487.7303)
layout = ccui.LayoutComponent:bindLayoutComponent(fntGold)
layout:setLeftMargin(-133.2580)
layout:setRightMargin(133.2580)
layout:setTopMargin(-487.7303)
layout:setBottomMargin(487.7303)
Node:addChild(fntGold)

--Create textName
local textName = ccui.Text:create()
textName:ignoreContentAdaptWithSize(true)
textName:setTextAreaSize({width = 0, height = 0})
textName:setFontSize(20)
textName:setString([[]])
textName:setTextHorizontalAlignment(1)
textName:setTextVerticalAlignment(1)
textName:setLayoutComponentEnabled(true)
textName:setName("textName")
textName:setTag(152)
textName:setCascadeColorEnabled(true)
textName:setCascadeOpacityEnabled(true)
textName:setPosition(-133.2129, 536.6969)
layout = ccui.LayoutComponent:bindLayoutComponent(textName)
layout:setLeftMargin(-133.2129)
layout:setRightMargin(133.2129)
layout:setTopMargin(-536.6969)
layout:setBottomMargin(536.6969)
Node:addChild(textName)

--Create btnPlayer
local btnPlayer = ccui.Button:create()
btnPlayer:ignoreContentAdaptWithSize(false)
btnPlayer:loadTextureNormal("game/baccarat_std/resource/image/grxx.png",0)
btnPlayer:loadTexturePressed("game/baccarat_std/resource/image/grxx.png",0)
btnPlayer:loadTextureDisabled("Default/Button_Disable.png",0)
btnPlayer:setTitleFontSize(14)
btnPlayer:setTitleColor({r = 65, g = 65, b = 70})
btnPlayer:setScale9Enabled(true)
btnPlayer:setCapInsets({x = 15, y = 11, width = 36, height = 190})
btnPlayer:setLayoutComponentEnabled(true)
btnPlayer:setName("btnPlayer")
btnPlayer:setTag(153)
btnPlayer:setCascadeColorEnabled(true)
btnPlayer:setCascadeOpacityEnabled(true)
btnPlayer:setPosition(32.4488, 550.1942)
layout = ccui.LayoutComponent:bindLayoutComponent(btnPlayer)
layout:setSize({width = 66.0000, height = 212.0000})
layout:setLeftMargin(-0.5512)
layout:setRightMargin(-65.4488)
layout:setTopMargin(-656.1942)
layout:setBottomMargin(444.1942)
Node:addChild(btnPlayer)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

