--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgBack
local imgBack = cc.Sprite:create("game/shark_std/resource/image/dtbg.jpg")
imgBack:setName("imgBack")
imgBack:setTag(130)
imgBack:setCascadeColorEnabled(true)
imgBack:setCascadeOpacityEnabled(true)
imgBack:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBack)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(825.0000, 590.0000))
layout:setLeftMargin(-412.5000)
layout:setRightMargin(-412.5000)
layout:setTopMargin(-295.0000)
layout:setBottomMargin(-295.0000)
Node:addChild(imgBack)

--Create btnEnter
local btnEnter = ccui.Button:create()
btnEnter:ignoreContentAdaptWithSize(false)
btnEnter:loadTextureNormal("game/shark_std/resource/button/ks1.png",0)
btnEnter:loadTexturePressed("game/shark_std/resource/button/ks3.png",0)
btnEnter:setTitleFontSize(14)
btnEnter:setTitleColor(cc.c3b(65, 65, 70))
btnEnter:setScale9Enabled(true)
btnEnter:setCapInsets(cc.rect(15,11,282,66))
btnEnter:setLayoutComponentEnabled(true)
btnEnter:setName("btnEnter")
btnEnter:setTag(131)
btnEnter:setCascadeColorEnabled(true)
btnEnter:setCascadeOpacityEnabled(true)
btnEnter:setPosition(-17.0000, -80.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnEnter)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(312.0000, 88.0000))
layout:setLeftMargin(-156.0000)
layout:setRightMargin(-156.0000)
layout:setTopMargin(96.0000)
layout:setBottomMargin(-184.0000)
Node:addChild(btnEnter)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

