--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create btn_game_item
local btn_game_item = ccui.Button:create()
btn_game_item:ignoreContentAdaptWithSize(false)
btn_game_item:loadTextureNormal("lobby/resource/icon/icon/jcby.png",0)
btn_game_item:setTitleFontSize(14)
btn_game_item:setTitleColor(cc.c3b(65, 65, 70))
btn_game_item:setScale9Enabled(true)
btn_game_item:setCapInsets(cc.rect(15,11,257,494))
btn_game_item:setLayoutComponentEnabled(true)
btn_game_item:setName("btn_game_item")
btn_game_item:setTag(36)
btn_game_item:setCascadeColorEnabled(true)
btn_game_item:setCascadeOpacityEnabled(true)
btn_game_item:setPosition(0.0000, 0.0000)
btn_game_item:setScaleX(2.0000)
btn_game_item:setScaleY(2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btn_game_item)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(287.0000, 516.0000))
layout:setLeftMargin(-143.5000)
layout:setRightMargin(-143.5000)
layout:setTopMargin(-258.0000)
layout:setBottomMargin(-258.0000)
Node:addChild(btn_game_item)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

