--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgBj
local imgBj = ccui.ImageView:create()
imgBj:ignoreContentAdaptWithSize(false)
imgBj:loadTexture("lobby/resource/horm/bg.png",0)
imgBj:setLayoutComponentEnabled(true)
imgBj:setName("imgBj")
imgBj:setTag(118)
imgBj:setCascadeColorEnabled(true)
imgBj:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBj)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setSize({width = 1093.0000, height = 527.0000})
layout:setLeftMargin(-546.5000)
layout:setRightMargin(-546.5000)
layout:setTopMargin(-263.5000)
layout:setBottomMargin(-263.5000)
Node:addChild(imgBj)

--Create imgSurplusWord
local imgSurplusWord = ccui.ImageView:create()
imgSurplusWord:ignoreContentAdaptWithSize(false)
imgSurplusWord:loadTexture("lobby/resource/horm/sylb.png",0)
imgSurplusWord:setLayoutComponentEnabled(true)
imgSurplusWord:setName("imgSurplusWord")
imgSurplusWord:setTag(119)
imgSurplusWord:setCascadeColorEnabled(true)
imgSurplusWord:setCascadeOpacityEnabled(true)
imgSurplusWord:setPosition(274.4945, 129.7339)
layout = ccui.LayoutComponent:bindLayoutComponent(imgSurplusWord)
layout:setSize({width = 169.0000, height = 39.0000})
layout:setLeftMargin(189.9945)
layout:setRightMargin(-358.9945)
layout:setTopMargin(-149.2339)
layout:setBottomMargin(110.2339)
Node:addChild(imgSurplusWord)

--Create btnClose
local btnClose = ccui.Button:create()
btnClose:ignoreContentAdaptWithSize(false)
btnClose:loadTextureNormal("lobby/resource/button/close.png",0)
btnClose:setTitleFontSize(14)
btnClose:setTitleColor({r = 65, g = 65, b = 70})
btnClose:setLayoutComponentEnabled(true)
btnClose:setName("btnClose")
btnClose:setTag(144)
btnClose:setCascadeColorEnabled(true)
btnClose:setCascadeOpacityEnabled(true)
btnClose:setPosition(520.0000, 190.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnClose)
layout:setSize({width = 80.0000, height = 80.0000})
layout:setLeftMargin(470.0000)
layout:setRightMargin(-570.0000)
layout:setTopMargin(-240.0000)
layout:setBottomMargin(140.0000)
Node:addChild(btnClose)

--Create textSurplusNum
local textSurplusNum = ccui.Text:create()
textSurplusNum:ignoreContentAdaptWithSize(true)
textSurplusNum:setTextAreaSize({width = 0, height = 0})
textSurplusNum:setFontName("simhei.ttf")
textSurplusNum:setFontSize(48)
textSurplusNum:setString([[123]])
textSurplusNum:setTextHorizontalAlignment(1)
textSurplusNum:setTextVerticalAlignment(1)
textSurplusNum:setLayoutComponentEnabled(true)
textSurplusNum:setName("textSurplusNum")
textSurplusNum:setTag(145)
textSurplusNum:setCascadeColorEnabled(true)
textSurplusNum:setCascadeOpacityEnabled(true)
textSurplusNum:setAnchorPoint(0.0000, 0.5000)
textSurplusNum:setPosition(369.9886, 129.6249)
layout = ccui.LayoutComponent:bindLayoutComponent(textSurplusNum)
layout:setSize({width = 73.0000, height = 55.0000})
layout:setLeftMargin(369.9886)
layout:setRightMargin(-442.9886)
layout:setTopMargin(-157.1249)
layout:setBottomMargin(102.1249)
Node:addChild(textSurplusNum)

--Create inputHorm
local inputHorm = ccui.TextField:create()
inputHorm:ignoreContentAdaptWithSize(false)
tolua.cast(inputHorm:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
--inputHorm:setFontName("simhei.ttf")
inputHorm:setFontSize(36)
inputHorm:setPlaceHolder("")
inputHorm:setString([[]])
inputHorm:setMaxLength(10)
inputHorm:setLayoutComponentEnabled(true)
inputHorm:setName("inputHorm")
inputHorm:setTag(146)
inputHorm:setCascadeColorEnabled(true)
inputHorm:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(inputHorm)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 950.0000, height = 149.0000})
layout:setLeftMargin(-475.0000)
layout:setRightMargin(-475.0000)
layout:setTopMargin(-74.5000)
layout:setBottomMargin(-74.5000)
Node:addChild(inputHorm)

--Create btnSure
local btnSure = ccui.Button:create()
btnSure:ignoreContentAdaptWithSize(false)
btnSure:loadTextureNormal("lobby/resource/horm/fs.png",0)
btnSure:setTitleFontSize(14)
btnSure:setTitleColor({r = 65, g = 65, b = 70})
btnSure:setLayoutComponentEnabled(true)
btnSure:setName("btnSure")
btnSure:setTag(147)
btnSure:setCascadeColorEnabled(true)
btnSure:setCascadeOpacityEnabled(true)
btnSure:setPosition(0.0000, -180.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSure)
layout:setPositionPercentXEnabled(true)
layout:setSize({width = 254.0000, height = 84.0000})
layout:setLeftMargin(-127.0000)
layout:setRightMargin(-127.0000)
layout:setTopMargin(138.0000)
layout:setBottomMargin(-222.0000)
Node:addChild(btnSure)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

