--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create imgBg
local imgBg = ccui.ImageView:create()
imgBg:ignoreContentAdaptWithSize(false)
imgBg:loadTexture("lobby/resource/login_res/bg.png",0)
imgBg:setLayoutComponentEnabled(true)
imgBg:setName("imgBg")
imgBg:setTag(44)
imgBg:setCascadeColorEnabled(true)
imgBg:setCascadeOpacityEnabled(true)
imgBg:setPosition(957.6960, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.4988)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1920.0000, height = 1080.0000})
layout:setLeftMargin(-2.3040)
layout:setRightMargin(2.3040)
Scene:addChild(imgBg)

--Create nodeAct
local nodeAct=cc.Node:create()
nodeAct:setName("nodeCard")
Scene:addChild(nodeAct)

-- --Create imgBg
-- local light1 = cc.Sprite:create("lobby/resource/login_res/bg_1.png")
-- light1:setCascadeColorEnabled(true)
-- light1:setCascadeOpacityEnabled(true)
-- light1:setPosition(960.0000, 192.0000)
-- layout = ccui.LayoutComponent:bindLayoutComponent(light1)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(1920.0000, 394.0000))
-- layout:setLeftMargin(844.3009)
-- layout:setRightMargin(-1074.3010)
-- layout:setTopMargin(-1078.0400)
-- layout:setBottomMargin(824.0400)
-- Scene:addChild(light1)

--灯光2
local light2 = cc.Sprite:create("lobby/resource/login_res/Logo.png")
light2:setCascadeColorEnabled(true)
light2:setCascadeOpacityEnabled(true)
light2:setPosition(1460.0000, 930.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(light2)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(921.0000, 649.0000))
layout:setLeftMargin(844.3009)
layout:setRightMargin(-1074.3010)
layout:setTopMargin(-1078.0400)
layout:setBottomMargin(824.0400)
Scene:addChild(light2)

-- --文字灯光
-- local spriteText = cc.Sprite:create("lobby/resource/cj/cj_1.png")
-- spriteText:setName("spriteText")
-- spriteText:setCascadeColorEnabled(true)
-- spriteText:setCascadeOpacityEnabled(true)
-- spriteText:setPosition(1780.0000, 963.0000)
-- layout = ccui.LayoutComponent:bindLayoutComponent(spriteText)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(240.0000, 207.0000))
-- layout:setLeftMargin(844.3009)
-- layout:setRightMargin(-1074.3010)
-- layout:setTopMargin(-1078.0400)
-- layout:setBottomMargin(824.0400)
-- Scene:addChild(spriteText)

-- --美女
-- local spritewomen = cc.Sprite:create("lobby/resource/cj/women.png")
-- spritewomen:setName("spritewomen")
-- spritewomen:setCascadeColorEnabled(true)
-- spritewomen:setCascadeOpacityEnabled(true)
-- spritewomen:setPosition(960.0000, 480.0000)
-- layout = ccui.LayoutComponent:bindLayoutComponent(spritewomen)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(706.0000, 963.0000))
-- layout:setLeftMargin(844.3009)
-- layout:setRightMargin(-1074.3010)
-- layout:setTopMargin(-1078.0400)
-- layout:setBottomMargin(824.0400)
-- Scene:addChild(spritewomen)

-- --闪光1
-- local flashSprite1 = cc.Sprite:create("lobby/resource/cj/flash.png")
-- flashSprite1:setName("flashSprite1")
-- flashSprite1:setCascadeColorEnabled(true)
-- flashSprite1:setCascadeOpacityEnabled(true)
-- flashSprite1:setPosition(892.0000,642.0000)
-- layout = ccui.LayoutComponent:bindLayoutComponent(flashSprite1)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(71.0000, 71.0000))
-- layout:setLeftMargin(844.3009)
-- layout:setRightMargin(-1074.3010)
-- layout:setTopMargin(-1078.0400)
-- layout:setBottomMargin(824.0400)
-- Scene:addChild(flashSprite1)

-- --闪光2
-- local flashSprite2 = cc.Sprite:create("lobby/resource/cj/flash.png")
-- flashSprite2:setName("flashSprite2")
-- flashSprite2:setCascadeColorEnabled(true)
-- flashSprite2:setCascadeOpacityEnabled(true)
-- flashSprite2:setPosition(1030.0000,623.0000)
-- flashSprite2:setScale(0.5)
-- layout = ccui.LayoutComponent:bindLayoutComponent(flashSprite2)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(71.0000, 71.0000))
-- layout:setLeftMargin(844.3009)
-- layout:setRightMargin(-1074.3010)
-- layout:setTopMargin(-1078.0400)
-- layout:setBottomMargin(824.0400)
-- Scene:addChild(flashSprite2)

local temp = 160

--Create btnTouristLogin
local btnTouristLogin = ccui.Button:create()
btnTouristLogin:ignoreContentAdaptWithSize(false)
btnTouristLogin:loadTextureNormal("lobby/resource/login_res/ykdl.png",0)
btnTouristLogin:setTitleFontSize(14)
btnTouristLogin:setTitleColor({r = 65, g = 65, b = 70})
btnTouristLogin:setLayoutComponentEnabled(true)
btnTouristLogin:setName("btnTouristLogin")
btnTouristLogin:setTag(46)
btnTouristLogin:setCascadeColorEnabled(true)
btnTouristLogin:setCascadeOpacityEnabled(true)
btnTouristLogin:setPosition(1350.0000, 490.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnTouristLogin)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1400)
layout:setPercentWidth(0.1885)
layout:setPercentHeight(0.1093)
layout:setSize({width = 373.0000, height = 128.0000})
layout:setLeftMargin(779.0000)
layout:setRightMargin(779.0000)
layout:setTopMargin(869.8000)
layout:setBottomMargin(92.2000)
Scene:addChild(btnTouristLogin)

--Create btnAccLogin
local btnAccLogin = ccui.Button:create()
btnAccLogin:ignoreContentAdaptWithSize(false)
btnAccLogin:loadTextureNormal("lobby/resource/login_res/zhdl.png",0)
btnAccLogin:setTitleFontSize(14)
btnAccLogin:setTitleColor({r = 65, g = 65, b = 70})
btnAccLogin:setScale9Enabled(true)
btnAccLogin:setCapInsets({x = 15, y = 11, width = 332, height = 96})
btnAccLogin:setLayoutComponentEnabled(true)
btnAccLogin:setName("btnAccLogin")
btnAccLogin:setTag(45)
btnAccLogin:setCascadeColorEnabled(true)
btnAccLogin:setCascadeOpacityEnabled(true)
btnAccLogin:setPosition(1350.0000, 490.0000-temp)
layout = ccui.LayoutComponent:bindLayoutComponent(btnAccLogin)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2800)
layout:setPositionPercentY(0.1400)
layout:setPercentWidth(0.1885)
layout:setPercentHeight(0.1093)
layout:setSize({width = 362.0000, height = 118.0000})
layout:setLeftMargin(356.6000)
layout:setRightMargin(1201.4000)
layout:setTopMargin(869.8000)
layout:setBottomMargin(92.2000)
Scene:addChild(btnAccLogin)

--Create btnWechatLogin
local btnWechatLogin = ccui.Button:create()
btnWechatLogin:ignoreContentAdaptWithSize(false)
btnWechatLogin:loadTextureNormal("lobby/resource/login_res/wxdl.png",0)
btnWechatLogin:setTitleFontSize(14)
btnWechatLogin:setTitleColor({r = 65, g = 65, b = 70})
btnWechatLogin:setLayoutComponentEnabled(true)
btnWechatLogin:setName("btnWechatLogin")
btnWechatLogin:setTag(47)
btnWechatLogin:setCascadeColorEnabled(true)
btnWechatLogin:setCascadeOpacityEnabled(true)
btnWechatLogin:setPosition(1350.0000, 490.0000-temp*2)
layout = ccui.LayoutComponent:bindLayoutComponent(btnWechatLogin)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.7200)
layout:setPositionPercentY(0.1400)
layout:setPercentWidth(0.1885)
layout:setPercentHeight(0.1093)
layout:setSize({width = 362.0000, height = 118.0000})
layout:setLeftMargin(1201.4000)
layout:setRightMargin(356.6000)
layout:setTopMargin(869.8000)
layout:setBottomMargin(92.2000)
Scene:addChild(btnWechatLogin)


--Create btnClose
local btnExit = ccui.Button:create()
btnExit:ignoreContentAdaptWithSize(false)
btnExit:loadTextureNormal("lobby/resource/button/btnClose1.png",0)
btnExit:loadTexturePressed("lobby/resource/button/btnClose3.png",0)
btnExit:setTitleFontSize(14)
btnExit:setTitleColor({r = 65, g = 65, b = 70})
btnExit:setLayoutComponentEnabled(true)
btnExit:setName("btnExit")
btnExit:setTag(163)
btnExit:setCascadeColorEnabled(true)
btnExit:setCascadeOpacityEnabled(true)
btnExit:setPosition(1899.0000, 1064.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnExit)
layout:setPositionPercentX(0.0339)
layout:setPositionPercentY(0.9444)
layout:setPercentWidth(0.0458)
layout:setPercentHeight(0.0852)
layout:setSize({width = 42.0000, height = 32.0000})
layout:setLeftMargin(21.0002)
layout:setRightMargin(1811.0000)
layout:setTopMargin(13.9990)
layout:setBottomMargin(974.0009)
Scene:addChild(btnExit)

--Create btnClose
local btnSmall = ccui.Button:create()
btnSmall:ignoreContentAdaptWithSize(false)
btnSmall:loadTextureNormal("lobby/resource/button/btnSmall1.png",0)
btnSmall:loadTexturePressed("lobby/resource/button/btnSmall3.png",0)
btnSmall:setTitleFontSize(14)
btnSmall:setTitleColor({r = 65, g = 65, b = 70})
btnSmall:setLayoutComponentEnabled(true)
btnSmall:setName("btnSmall")
btnSmall:setTag(163)
btnSmall:setCascadeColorEnabled(true)
btnSmall:setCascadeOpacityEnabled(true)
btnSmall:setPosition(1857.0000, 1064.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSmall)
layout:setPositionPercentX(0.0339)
layout:setPositionPercentY(0.9444)
layout:setPercentWidth(0.0458)
layout:setPercentHeight(0.0852)
layout:setSize({width = 42.0000, height = 32.0000})
layout:setLeftMargin(21.0002)
layout:setRightMargin(1811.0000)
layout:setTopMargin(13.9990)
layout:setBottomMargin(974.0009)
Scene:addChild(btnSmall)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List



result['root'] = Scene
return result;
end

return Result

