--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create btnRoom
local btnRoom = ccui.Button:create()
btnRoom:ignoreContentAdaptWithSize(false)
btnRoom:loadTextureNormal("lobby/resource/icon/icon/bsddz.png",0)
btnRoom:loadTexturePressed("lobby/resource/icon/icon/bsddz.png",0)
btnRoom:setTitleFontSize(14)
btnRoom:setTitleColor(cc.c3b(65, 65, 70))
btnRoom:setScale9Enabled(true)
btnRoom:setCapInsets(cc.rect(15,11,257,494))
btnRoom:setLayoutComponentEnabled(true)
btnRoom:setName("btnRoom")
btnRoom:setTag(114)
btnRoom:setCascadeColorEnabled(true)
btnRoom:setCascadeOpacityEnabled(true)
btnRoom:setAnchorPoint(0.0000, 0.5000)
btnRoom:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnRoom)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(287.0000, 516.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(-287.0000)
layout:setTopMargin(-258.0000)
layout:setBottomMargin(-258.0000)
Node:addChild(btnRoom)

--Create imgRoom
local imgRoom = ccui.ImageView:create()
imgRoom:ignoreContentAdaptWithSize(false)
imgRoom:loadTexture("lobby/resource/RoomList/xsc.png",0)
imgRoom:setLayoutComponentEnabled(true)
imgRoom:setName("imgRoom")
imgRoom:setTag(117)
imgRoom:setCascadeColorEnabled(true)
imgRoom:setCascadeOpacityEnabled(true)
imgRoom:setPosition(240.9975, -82.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgRoom)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(104.0000, 140.0000))
layout:setLeftMargin(188.9975)
layout:setRightMargin(-292.9975)
layout:setTopMargin(12.0000)
layout:setBottomMargin(-152.0000)
Node:addChild(imgRoom)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

