--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create hte_1
local hte_1 = cc.Sprite:create("lobby/resource/hall_res/hte.png")
hte_1:setName("hte_1")
hte_1:setTag(30)
hte_1:setCascadeColorEnabled(true)
hte_1:setCascadeOpacityEnabled(true)
hte_1:setPosition(0.0000, 0.0000)
hte_1:setOpacity(100)
layout = ccui.LayoutComponent:bindLayoutComponent(hte_1)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(1097.0000, 99.0000))
layout:setLeftMargin(-526.0000)
layout:setRightMargin(-526.0000)
layout:setTopMargin(-59.0000)
layout:setBottomMargin(-59.0000)
Node:addChild(hte_1)

--Create text
local text = ccui.Text:create()
text:ignoreContentAdaptWithSize(true)
text:setTextAreaSize(cc.size(0, 0))
--text:setFontName("simhei.ttf")
text:setFontSize(48)
text:setString([[网络连接成功]])
text:setLayoutComponentEnabled(true)
text:setName("text")
text:setTag(29)
text:setCascadeColorEnabled(true)
text:setCascadeOpacityEnabled(true)
text:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(text)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(288.0000, 55.0000))
layout:setLeftMargin(-216.0000)
layout:setRightMargin(-216.0000)
layout:setTopMargin(-41.0000)
layout:setBottomMargin(-41.0000)
Node:addChild(text)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

