--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Img_CMBg
local Img_CMBg = ccui.ImageView:create()
Img_CMBg:ignoreContentAdaptWithSize(false)
Img_CMBg:loadTexture("game/weishuwu_std/resource/image/heid.png",0)
Img_CMBg:setLayoutComponentEnabled(true)
Img_CMBg:setName("Img_CMBg")
Img_CMBg:setTag(201)
Img_CMBg:setCascadeColorEnabled(true)
Img_CMBg:setCascadeOpacityEnabled(true)
Img_CMBg:setPosition(957.0000, 96.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_CMBg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(1300.0000, 175.0000))
layout:setLeftMargin(307.0000)
layout:setRightMargin(-1607.0000)
layout:setTopMargin(-183.5000)
layout:setBottomMargin(8.5000)
Node:addChild(Img_CMBg)

--Create ListView_CM
local ListView_CM = ccui.ListView:create()
ListView_CM:setItemsMargin(10)
ListView_CM:setDirection(2)
ListView_CM:setGravity(5)
ListView_CM:ignoreContentAdaptWithSize(false)
ListView_CM:setClippingEnabled(true)
ListView_CM:setBackGroundColorOpacity(102)
ListView_CM:setLayoutComponentEnabled(true)
ListView_CM:setName("ListView_CM")
ListView_CM:setTag(202)
ListView_CM:setCascadeColorEnabled(true)
ListView_CM:setCascadeOpacityEnabled(true)
ListView_CM:setAnchorPoint(0.5000, 0.5000)
ListView_CM:setPosition(660.0000, 98.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_CM)
layout:setPositionPercentX(0.5077)
layout:setPositionPercentY(0.5629)
layout:setPercentWidth(0.8846)
layout:setPercentHeight(0.9714)
layout:setSize(cc.size(1150.0000, 170.0000))
layout:setLeftMargin(85.0000)
layout:setRightMargin(65.0000)
layout:setTopMargin(-8.5000)
layout:setBottomMargin(13.5000)
Img_CMBg:addChild(ListView_CM)

--Create Btn_CM1
local Btn_CM1 = ccui.CheckBox:create()
Btn_CM1:ignoreContentAdaptWithSize(false)
Btn_CM1:loadTextureBackGround("game/weishuwu_std/resource/button/1.png",0)
Btn_CM1:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM1:setLayoutComponentEnabled(true)
Btn_CM1:setName("Btn_CM1")
Btn_CM1:setTag(203)
Btn_CM1:setCascadeColorEnabled(true)
Btn_CM1:setCascadeOpacityEnabled(true)
Btn_CM1:setPosition(81.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM1)
layout:setPositionPercentX(0.1424)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(22.9737)
layout:setRightMargin(545.0264)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM1)

--Create Btn_CM2
local Btn_CM2 = ccui.CheckBox:create()
Btn_CM2:ignoreContentAdaptWithSize(false)
Btn_CM2:loadTextureBackGround("game/weishuwu_std/resource/button/10.png",0)
Btn_CM2:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM2:setLayoutComponentEnabled(true)
Btn_CM2:setName("Btn_CM2")
Btn_CM2:setLocalZOrder(1)
Btn_CM2:setTag(204)
Btn_CM2:setCascadeColorEnabled(true)
Btn_CM2:setCascadeOpacityEnabled(true)
Btn_CM2:setPosition(253.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM2)
layout:setPositionPercentX(0.3835)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(198.9742)
layout:setRightMargin(369.0258)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM2)

--Create Btn_CM3
local Btn_CM3 = ccui.CheckBox:create()
Btn_CM3:ignoreContentAdaptWithSize(false)
Btn_CM3:loadTextureBackGround("game/weishuwu_std/resource/button/100.png",0)
Btn_CM3:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM3:setLayoutComponentEnabled(true)
Btn_CM3:setName("Btn_CM3")
Btn_CM3:setLocalZOrder(2)
Btn_CM3:setTag(205)
Btn_CM3:setCascadeColorEnabled(true)
Btn_CM3:setCascadeOpacityEnabled(true)
Btn_CM3:setPosition(425.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM3)
layout:setPositionPercentX(0.6260)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(375.9723)
layout:setRightMargin(192.0277)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM3)

--Create Btn_CM4
local Btn_CM4 = ccui.CheckBox:create()
Btn_CM4:ignoreContentAdaptWithSize(false)
Btn_CM4:loadTextureBackGround("game/weishuwu_std/resource/button/1000.png",0)
Btn_CM4:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM4:setLayoutComponentEnabled(true)
Btn_CM4:setName("Btn_CM4")
Btn_CM4:setLocalZOrder(3)
Btn_CM4:setTag(206)
Btn_CM4:setCascadeColorEnabled(true)
Btn_CM4:setCascadeOpacityEnabled(true)
Btn_CM4:setPosition(597.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM4)
layout:setPositionPercentX(0.8685)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(552.9724)
layout:setRightMargin(15.0276)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM4)

--Create Btn_CM5
local Btn_CM5 = ccui.CheckBox:create()
Btn_CM5:ignoreContentAdaptWithSize(false)
Btn_CM5:loadTextureBackGround("game/weishuwu_std/resource/button/10000.png",0)
Btn_CM5:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM5:setLayoutComponentEnabled(true)
Btn_CM5:setName("Btn_CM5")
Btn_CM5:setLocalZOrder(4)
Btn_CM5:setTag(207)
Btn_CM5:setCascadeColorEnabled(true)
Btn_CM5:setCascadeOpacityEnabled(true)
Btn_CM5:setPosition(769.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM5)
layout:setPositionPercentX(1.1109)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(729.9703)
layout:setRightMargin(-161.9703)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM5)

--Create Btn_CM6
local Btn_CM6 = ccui.CheckBox:create()
Btn_CM6:ignoreContentAdaptWithSize(false)
Btn_CM6:loadTextureBackGround("game/weishuwu_std/resource/button/100000.png",0)
Btn_CM6:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM6:setLayoutComponentEnabled(true)
Btn_CM6:setName("Btn_CM6")
Btn_CM6:setLocalZOrder(5)
Btn_CM6:setTag(208)
Btn_CM6:setCascadeColorEnabled(true)
Btn_CM6:setCascadeOpacityEnabled(true)
Btn_CM6:setPosition(941.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM6)
layout:setPositionPercentX(1.3534)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(906.9760)
layout:setRightMargin(-338.9760)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM6)

--Create Btn_CM7
local Btn_CM7 = ccui.CheckBox:create()
Btn_CM7:ignoreContentAdaptWithSize(false)
Btn_CM7:loadTextureBackGround("game/weishuwu_std/resource/button/1000000.png",0)
Btn_CM7:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM7:setLayoutComponentEnabled(true)
Btn_CM7:setName("Btn_CM7")
Btn_CM7:setLocalZOrder(6)
Btn_CM7:setTag(209)
Btn_CM7:setCascadeColorEnabled(true)
Btn_CM7:setCascadeOpacityEnabled(true)
Btn_CM7:setPosition(1113.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM7)
layout:setPositionPercentX(1.5959)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(1083.9770)
layout:setRightMargin(-515.9772)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM7)

--Create Btn_CM8
local Btn_CM8 = ccui.CheckBox:create()
Btn_CM8:ignoreContentAdaptWithSize(false)
Btn_CM8:loadTextureBackGround("game/weishuwu_std/resource/button/10000000.png",0)
Btn_CM8:loadTextureFrontCross("game/weishuwu_std/resource/image/GQuan.png",0)
Btn_CM8:setLayoutComponentEnabled(true)
Btn_CM8:setName("Btn_CM8")
Btn_CM8:setLocalZOrder(7)
Btn_CM8:setTag(210)
Btn_CM8:setCascadeColorEnabled(true)
Btn_CM8:setCascadeOpacityEnabled(true)
Btn_CM8:setPosition(1285.0000, 85.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Btn_CM8)
layout:setPositionPercentX(1.8383)
layout:setPositionPercentY(0.5450)
layout:setSize(cc.size(162.0000, 161.0000))
layout:setLeftMargin(1260.9730)
layout:setRightMargin(-692.9731)
layout:setTopMargin(10.4996)
layout:setBottomMargin(28.5004)
ListView_CM:pushBackCustomItem(Btn_CM8)

--Create huakuai1_10
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/weishuwu_std/resource/effect/huakuai.plist")
local huakuai1_10 = cc.Sprite:createWithSpriteFrameName("huakuai1.png")
huakuai1_10:setName("huakuai1_10")
huakuai1_10:setTag(211)
huakuai1_10:setCascadeColorEnabled(true)
huakuai1_10:setCascadeOpacityEnabled(true)
huakuai1_10:setPosition(1254.0760, 98.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(huakuai1_10)
layout:setPositionPercentX(0.9647)
layout:setPositionPercentY(0.5629)
layout:setSize(cc.size(138.0000, 197.0000))
layout:setLeftMargin(1185.0760)
layout:setRightMargin(-23.0762)
layout:setTopMargin(-22.0000)
layout:setBottomMargin(0.0000)
huakuai1_10:setFlippedX(true)
Img_CMBg:addChild(huakuai1_10)

--Create huakuai1_9
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/weishuwu_std/resource/effect/huakuai.plist")
local huakuai1_9 = cc.Sprite:createWithSpriteFrameName("huakuai1.png")
huakuai1_9:setName("huakuai1_9")
huakuai1_9:setTag(212)
huakuai1_9:setCascadeColorEnabled(true)
huakuai1_9:setCascadeOpacityEnabled(true)
huakuai1_9:setPosition(64.0970, 98.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(huakuai1_9)
layout:setPositionPercentX(0.0493)
layout:setPositionPercentY(0.5629)
layout:setSize(cc.size(138.0000, 197.0000))
layout:setLeftMargin(-4.9030)
layout:setRightMargin(1166.9030)
layout:setTopMargin(-22.0000)
layout:setBottomMargin(0.0000)
Img_CMBg:addChild(huakuai1_9)

--Create NodeYidEffect2
local NodeYidEffect2=cc.Node:create()
NodeYidEffect2:setName("NodeYidEffect2")
NodeYidEffect2:setTag(213)
NodeYidEffect2:setCascadeColorEnabled(true)
NodeYidEffect2:setCascadeOpacityEnabled(true)
NodeYidEffect2:setPosition(1254.0970, 98.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(NodeYidEffect2)
layout:setPositionPercentX(0.9647)
layout:setPositionPercentY(0.5629)
layout:setLeftMargin(1254.0970)
layout:setRightMargin(45.9028)
layout:setTopMargin(76.5000)
layout:setBottomMargin(98.5000)
Img_CMBg:addChild(NodeYidEffect2)

--Create NodeYidEffect1
local NodeYidEffect1=cc.Node:create()
NodeYidEffect1:setName("NodeYidEffect1")
NodeYidEffect1:setTag(214)
NodeYidEffect1:setCascadeColorEnabled(true)
NodeYidEffect1:setCascadeOpacityEnabled(true)
NodeYidEffect1:setPosition(64.0913, 98.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(NodeYidEffect1)
layout:setPositionPercentX(0.0493)
layout:setPositionPercentY(0.5629)
layout:setLeftMargin(64.0913)
layout:setRightMargin(1235.9090)
layout:setTopMargin(76.5000)
layout:setBottomMargin(98.5000)
Img_CMBg:addChild(NodeYidEffect1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

