--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Img_DBg
local Img_DBg = ccui.ImageView:create()
Img_DBg:ignoreContentAdaptWithSize(false)
Img_DBg:loadTexture("game/weishuwu_std/resource/image/DHK.png",0)
Img_DBg:setLayoutComponentEnabled(true)
Img_DBg:setName("Img_DBg")
Img_DBg:setTag(319)
Img_DBg:setCascadeColorEnabled(true)
Img_DBg:setCascadeOpacityEnabled(true)
Img_DBg:setPosition(0.0000, 0.0000)
Img_DBg:setScaleX(0.7000)
Img_DBg:setScaleY(0.7000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_DBg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(739.0000, 917.0000))
layout:setLeftMargin(-369.5000)
layout:setRightMargin(-369.5000)
layout:setTopMargin(-458.5000)
layout:setBottomMargin(-458.5000)
Node:addChild(Img_DBg)

--Create btnAddChips
local btnAddChips = ccui.Button:create()
btnAddChips:ignoreContentAdaptWithSize(false)
btnAddChips:loadTextureNormal("game/weishuwu_std/resource/button/SF.png",0)
btnAddChips:setTitleFontSize(14)
btnAddChips:setTitleColor(cc.c3b(65, 65, 70))
btnAddChips:setScale9Enabled(true)
btnAddChips:setCapInsets(cc.rect(15,11,407,211))
btnAddChips:setLayoutComponentEnabled(true)
btnAddChips:setName("btnAddChips")
btnAddChips:setTag(320)
btnAddChips:setCascadeColorEnabled(true)
btnAddChips:setCascadeOpacityEnabled(true)
btnAddChips:setPosition(369.2845, 680.5112)
btnAddChips:setScaleY(0.9500)
layout = ccui.LayoutComponent:bindLayoutComponent(btnAddChips)
layout:setPositionPercentX(0.4997)
layout:setPositionPercentY(0.7421)
layout:setPercentWidth(0.5913)
layout:setPercentHeight(0.2541)
layout:setSize(cc.size(437.0000, 233.0000))
layout:setLeftMargin(150.7845)
layout:setRightMargin(151.2155)
layout:setTopMargin(119.9888)
layout:setBottomMargin(564.0112)
Img_DBg:addChild(btnAddChips)

--Create btnReduceChips
local btnReduceChips = ccui.Button:create()
btnReduceChips:ignoreContentAdaptWithSize(false)
btnReduceChips:loadTextureNormal("game/weishuwu_std/resource/button/XF.png",0)
btnReduceChips:setTitleFontSize(14)
btnReduceChips:setTitleColor(cc.c3b(65, 65, 70))
btnReduceChips:setScale9Enabled(true)
btnReduceChips:setCapInsets(cc.rect(15,11,407,211))
btnReduceChips:setLayoutComponentEnabled(true)
btnReduceChips:setName("btnReduceChips")
btnReduceChips:setTag(321)
btnReduceChips:setCascadeColorEnabled(true)
btnReduceChips:setCascadeOpacityEnabled(true)
btnReduceChips:setPosition(369.2845, 414.9722)
btnReduceChips:setScaleY(0.9500)
layout = ccui.LayoutComponent:bindLayoutComponent(btnReduceChips)
layout:setPositionPercentX(0.4997)
layout:setPositionPercentY(0.4525)
layout:setPercentWidth(0.5913)
layout:setPercentHeight(0.2541)
layout:setSize(cc.size(437.0000, 233.0000))
layout:setLeftMargin(150.7845)
layout:setRightMargin(151.2155)
layout:setTopMargin(385.5278)
layout:setBottomMargin(298.4722)
Img_DBg:addChild(btnReduceChips)

--Create btnExchangeAll
local btnExchangeAll = ccui.Button:create()
btnExchangeAll:ignoreContentAdaptWithSize(false)
btnExchangeAll:loadTextureNormal("game/weishuwu_std/resource/button/AllS.png",0)
btnExchangeAll:setTitleFontSize(14)
btnExchangeAll:setTitleColor(cc.c3b(65, 65, 70))
btnExchangeAll:setScale9Enabled(true)
btnExchangeAll:setCapInsets(cc.rect(15,11,407,211))
btnExchangeAll:setLayoutComponentEnabled(true)
btnExchangeAll:setName("btnExchangeAll")
btnExchangeAll:setTag(322)
btnExchangeAll:setCascadeColorEnabled(true)
btnExchangeAll:setCascadeOpacityEnabled(true)
btnExchangeAll:setPosition(369.2845, 153.5709)
btnExchangeAll:setScaleY(0.9500)
layout = ccui.LayoutComponent:bindLayoutComponent(btnExchangeAll)
layout:setPositionPercentX(0.4997)
layout:setPositionPercentY(0.1675)
layout:setPercentWidth(0.5913)
layout:setPercentHeight(0.2541)
layout:setSize(cc.size(437.0000, 233.0000))
layout:setLeftMargin(150.7845)
layout:setRightMargin(151.2155)
layout:setTopMargin(646.9291)
layout:setBottomMargin(37.0709)
Img_DBg:addChild(btnExchangeAll)

--Create btnClose
local btnClose = ccui.Button:create()
btnClose:ignoreContentAdaptWithSize(false)
btnClose:loadTextureNormal("game/weishuwu_std/resource/button/guanb.png",0)
btnClose:setTitleFontSize(14)
btnClose:setTitleColor(cc.c3b(65, 65, 70))
btnClose:setScale9Enabled(true)
btnClose:setCapInsets(cc.rect(15,11,50,58))
btnClose:setLayoutComponentEnabled(true)
btnClose:setName("btnClose")
btnClose:setTag(478)
btnClose:setCascadeColorEnabled(true)
btnClose:setCascadeOpacityEnabled(true)
btnClose:setPosition(648.0767, 818.3323)
btnClose:setScaleX(1.4000)
btnClose:setScaleY(1.4000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnClose)
layout:setPositionPercentX(0.8770)
layout:setPositionPercentY(0.8924)
layout:setPercentWidth(0.1083)
layout:setPercentHeight(0.0872)
layout:setSize(cc.size(80.0000, 80.0000))
layout:setLeftMargin(608.0767)
layout:setRightMargin(50.9233)
layout:setTopMargin(58.6677)
layout:setBottomMargin(778.3323)
Img_DBg:addChild(btnClose)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

