--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Img_BG
local Img_BG = ccui.ImageView:create()
Img_BG:ignoreContentAdaptWithSize(false)
Img_BG:loadTexture("game/weishuwu_std/resource/image/ludan.png",0)
Img_BG:setLayoutComponentEnabled(true)
Img_BG:setName("Img_BG")
Img_BG:setTag(122)
Img_BG:setCascadeColorEnabled(true)
Img_BG:setCascadeOpacityEnabled(true)
Img_BG:setPosition(0.0000, 0.0000)
Img_BG:setScaleX(0.8000)
Img_BG:setScaleY(0.8000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_BG)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(1352.0000, 967.0000))
layout:setLeftMargin(-676.0000)
layout:setRightMargin(-676.0000)
layout:setTopMargin(-483.5000)
layout:setBottomMargin(-483.5000)
Node:addChild(Img_BG)

--Create FntNum1
--local FntNum1 = ccui.TextBMFont:create()
--FntNum1:setFntFile("game/weishuwu_std/resource/number/numb1.fnt")
local FntNum1 = ccui.Text:create()
FntNum1:setFontName("lobby/resource/font/simhei.ttf")
FntNum1:setFontSize(30)
FntNum1:setString([[30]])
FntNum1:setLayoutComponentEnabled(true)
FntNum1:setName("FntNum1")
FntNum1:setTag(294)
FntNum1:setCascadeColorEnabled(true)
FntNum1:setCascadeOpacityEnabled(true)
FntNum1:setPosition(223.0002, 904.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FntNum1)
layout:setPositionPercentX(0.1649)
layout:setPositionPercentY(0.9349)
layout:setSize(cc.size(55.0000, 39.0000))
layout:setLeftMargin(195.5002)
layout:setRightMargin(1101.5000)
layout:setTopMargin(43.5000)
layout:setBottomMargin(884.5000)
Img_BG:addChild(FntNum1)

--Create FntNum2
--local FntNum2 = ccui.TextBMFont:create()
--FntNum2:setFntFile("game/weishuwu_std/resource/number/numb1.fnt")
local FntNum2 = ccui.Text:create()
FntNum2:setFontName("lobby/resource/font/simhei.ttf")
FntNum2:setFontSize(30)
FntNum2:setString([[15]])
FntNum2:setLayoutComponentEnabled(true)
FntNum2:setName("FntNum2")
FntNum2:setTag(295)
FntNum2:setCascadeColorEnabled(true)
FntNum2:setCascadeOpacityEnabled(true)
FntNum2:setPosition(535.9999, 904.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FntNum2)
layout:setPositionPercentX(0.3964)
layout:setPositionPercentY(0.9349)
layout:setSize(cc.size(54.0000, 39.0000))
layout:setLeftMargin(508.9999)
layout:setRightMargin(789.0001)
layout:setTopMargin(43.5000)
layout:setBottomMargin(884.5000)
Img_BG:addChild(FntNum2)

--Create FntNum3
--local FntNum3 = ccui.TextBMFont:create()
--FntNum3:setFntFile("game/weishuwu_std/resource/number/numb1.fnt")
local FntNum3 = ccui.Text:create()
FntNum3:setFontName("lobby/resource/font/simhei.ttf")
FntNum3:setFontSize(30)
FntNum3:setString([[20]])
FntNum3:setLayoutComponentEnabled(true)
FntNum3:setName("FntNum3")
FntNum3:setTag(296)
FntNum3:setCascadeColorEnabled(true)
FntNum3:setCascadeOpacityEnabled(true)
FntNum3:setPosition(849.9977, 904.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FntNum3)
layout:setPositionPercentX(0.6287)
layout:setPositionPercentY(0.9349)
layout:setSize(cc.size(54.0000, 39.0000))
layout:setLeftMargin(822.9977)
layout:setRightMargin(475.0023)
layout:setTopMargin(43.5000)
layout:setBottomMargin(884.5000)
Img_BG:addChild(FntNum3)

--Create FntNum4
--local FntNum4 = ccui.TextBMFont:create()
--FntNum4:setFntFile("game/weishuwu_std/resource/number/numb1.fnt")
local FntNum4 = ccui.Text:create()
FntNum4:setFontName("lobby/resource/font/simhei.ttf")
FntNum4:setFontSize(30)
FntNum4:setString([[11]])
FntNum4:setLayoutComponentEnabled(true)
FntNum4:setName("FntNum4")
FntNum4:setTag(297)
FntNum4:setCascadeColorEnabled(true)
FntNum4:setCascadeOpacityEnabled(true)
FntNum4:setPosition(1164.1540, 904.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(FntNum4)
layout:setPositionPercentX(0.8611)
layout:setPositionPercentY(0.9349)
layout:setSize(cc.size(54.0000, 39.0000))
layout:setLeftMargin(1137.1540)
layout:setRightMargin(160.8462)
layout:setTopMargin(43.5000)
layout:setBottomMargin(884.5000)
Img_BG:addChild(FntNum4)

--Create BtnExit
local BtnExit = ccui.Button:create()
BtnExit:ignoreContentAdaptWithSize(false)
BtnExit:loadTextureNormal("game/weishuwu_std/resource/button/guanb.png",0)
BtnExit:setTitleFontSize(14)
BtnExit:setTitleColor(cc.c3b(65, 65, 70))
BtnExit:setScale9Enabled(true)
BtnExit:setCapInsets(cc.rect(0,0,80,80))
BtnExit:setLayoutComponentEnabled(true)
BtnExit:setName("BtnExit")
BtnExit:setTag(124)
BtnExit:setCascadeColorEnabled(true)
BtnExit:setCascadeOpacityEnabled(true)
BtnExit:setPosition(1296.0000, 909.0007)
BtnExit:setScaleX(1.2000)
BtnExit:setScaleY(1.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(BtnExit)
layout:setPositionPercentX(0.9586)
layout:setPositionPercentY(0.9400)
layout:setPercentWidth(0.0592)
layout:setPercentHeight(0.0827)
layout:setSize(cc.size(80.0000, 80.0000))
layout:setLeftMargin(1256.0000)
layout:setRightMargin(15.9998)
layout:setTopMargin(17.9993)
layout:setBottomMargin(869.0007)
Img_BG:addChild(BtnExit)

--Create pnlBigEyeItem
local pnlBigEyeItem = ccui.Layout:create()
pnlBigEyeItem:ignoreContentAdaptWithSize(false)
pnlBigEyeItem:setBackGroundColorOpacity(102)
pnlBigEyeItem:setTouchEnabled(true);
pnlBigEyeItem:setLayoutComponentEnabled(true)
pnlBigEyeItem:setName("pnlBigEyeItem")
pnlBigEyeItem:setTag(298)
pnlBigEyeItem:setCascadeColorEnabled(true)
pnlBigEyeItem:setCascadeOpacityEnabled(true)
pnlBigEyeItem:setPosition(27.0000, 585.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(pnlBigEyeItem)
layout:setPositionPercentX(0.0200)
layout:setPositionPercentY(0.6050)
layout:setPercentWidth(0.9615)
layout:setPercentHeight(0.2844)
layout:setSize(cc.size(1300.0000, 275.0000))
layout:setLeftMargin(27.0000)
layout:setRightMargin(25.0000)
layout:setTopMargin(106.9999)
layout:setBottomMargin(585.0001)
Img_BG:addChild(pnlBigEyeItem)

--Create pnlZhupanItem
local pnlZhupanItem = ccui.Layout:create()
pnlZhupanItem:ignoreContentAdaptWithSize(false)
pnlZhupanItem:setBackGroundColorOpacity(102)
pnlZhupanItem:setTouchEnabled(true);
pnlZhupanItem:setLayoutComponentEnabled(true)
pnlZhupanItem:setName("pnlZhupanItem")
pnlZhupanItem:setTag(299)
pnlZhupanItem:setCascadeColorEnabled(true)
pnlZhupanItem:setCascadeOpacityEnabled(true)
pnlZhupanItem:setPosition(27.0001, 17.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(pnlZhupanItem)
layout:setPositionPercentX(0.0200)
layout:setPositionPercentY(0.0176)
layout:setPercentWidth(0.9615)
layout:setPercentHeight(0.5843)
layout:setSize(cc.size(1300.0000, 565.0000))
layout:setLeftMargin(27.0001)
layout:setRightMargin(24.9999)
layout:setTopMargin(384.9999)
layout:setBottomMargin(17.0001)
Img_BG:addChild(pnlZhupanItem)

--Create hong1_1
local hong1_1 = ccui.ImageView:create()
hong1_1:ignoreContentAdaptWithSize(false)
hong1_1:loadTexture("game/weishuwu_std/resource/image/7.png",0)
hong1_1:setLayoutComponentEnabled(true)
hong1_1:setName("hong1_1")
hong1_1:setTag(300)
hong1_1:setCascadeColorEnabled(true)
hong1_1:setCascadeOpacityEnabled(true)
hong1_1:setPosition(400.0000, 879.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(hong1_1)
layout:setPositionPercentX(0.2959)
layout:setPositionPercentY(0.9090)
layout:setPercentWidth(0.0710)
layout:setPercentHeight(0.0920)
layout:setSize(cc.size(96.0000, 89.0000))
layout:setLeftMargin(352.0000)
layout:setRightMargin(904.0000)
layout:setTopMargin(43.5000)
layout:setBottomMargin(834.5000)
Img_BG:addChild(hong1_1)

--Create lan1_2
local lan1_2 = ccui.ImageView:create()
lan1_2:ignoreContentAdaptWithSize(false)
lan1_2:loadTexture("game/weishuwu_std/resource/image/8.png",0)
lan1_2:setLayoutComponentEnabled(true)
lan1_2:setName("lan1_2")
lan1_2:setTag(301)
lan1_2:setCascadeColorEnabled(true)
lan1_2:setCascadeOpacityEnabled(true)
lan1_2:setPosition(26.0000, 932.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(lan1_2)
layout:setPositionPercentX(0.0192)
layout:setPositionPercentY(0.9648)
layout:setPercentWidth(0.0710)
layout:setPercentHeight(0.0920)
layout:setSize(cc.size(96.0000, 89.0000))
layout:setLeftMargin(-22.0000)
layout:setRightMargin(1278.0000)
layout:setTopMargin(-10.4999)
layout:setBottomMargin(888.4999)
Img_BG:addChild(lan1_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

