--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Img_Lu
local Img_Lu = ccui.ImageView:create()
Img_Lu:ignoreContentAdaptWithSize(false)
Img_Lu:loadTexture("game/weishuwu_std/resource/image/1.png",0)
Img_Lu:setLayoutComponentEnabled(true)
Img_Lu:setName("Img_Lu")
Img_Lu:setTag(104)
Img_Lu:setCascadeColorEnabled(true)
Img_Lu:setCascadeOpacityEnabled(true)
Img_Lu:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Img_Lu)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(35.0000, 36.0000))
layout:setLeftMargin(-17.5000)
layout:setRightMargin(-17.5000)
layout:setTopMargin(-18.0000)
layout:setBottomMargin(-18.0000)
Node:addChild(Img_Lu)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

