--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ImgDBg
local ImgDBg = ccui.ImageView:create()
ImgDBg:ignoreContentAdaptWithSize(false)
ImgDBg:loadTexture("game/horserace_std/resource/image/cmdh.png",0)
ImgDBg:setLayoutComponentEnabled(true)
ImgDBg:setName("ImgDBg")
ImgDBg:setTag(330)
ImgDBg:setCascadeColorEnabled(true)
ImgDBg:setCascadeOpacityEnabled(true)
ImgDBg:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ImgDBg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(621.0000, 661.0000))
layout:setLeftMargin(-277.0000)
layout:setRightMargin(-277.0000)
layout:setTopMargin(-337.5000)
layout:setBottomMargin(-337.5000)
Node:addChild(ImgDBg)

--Create btnAddChips
local btnAddChips = ccui.Button:create()
btnAddChips:ignoreContentAdaptWithSize(false)
btnAddChips:loadTextureNormal("game/horserace_std/resource/button/sf.png",0)
btnAddChips:setTitleFontSize(14)
btnAddChips:setTitleColor(cc.c3b(65, 65, 70))
btnAddChips:setLayoutComponentEnabled(true)
btnAddChips:setName("btnAddChips")
btnAddChips:setTag(331)
btnAddChips:setCascadeColorEnabled(true)
btnAddChips:setCascadeOpacityEnabled(true)
btnAddChips:setPosition(310.0000, 420.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnAddChips)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.6222)
layout:setSize(cc.size(421.0000, 144.0000))
layout:setLeftMargin(144.5000)
layout:setRightMargin(144.5000)
layout:setTopMargin(194.0000)
layout:setBottomMargin(359.0000)
ImgDBg:addChild(btnAddChips)

--Create btnReduceChips
local btnReduceChips = ccui.Button:create()
btnReduceChips:ignoreContentAdaptWithSize(false)
btnReduceChips:loadTextureNormal("game/horserace_std/resource/button/xf.png",0)
btnReduceChips:setTitleFontSize(14)
btnReduceChips:setTitleColor(cc.c3b(65, 65, 70))
btnReduceChips:setLayoutComponentEnabled(true)
btnReduceChips:setName("btnReduceChips")
btnReduceChips:setTag(332)
btnReduceChips:setCascadeColorEnabled(true)
btnReduceChips:setCascadeOpacityEnabled(true)
btnReduceChips:setPosition(310.0000, 270.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnReduceChips)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.4000)
layout:setSize(cc.size(421.0000, 144.0000))
layout:setLeftMargin(144.5000)
layout:setRightMargin(144.5000)
layout:setTopMargin(344.0000)
layout:setBottomMargin(209.0000)
ImgDBg:addChild(btnReduceChips)

--Create btnExchangeAll
local btnExchangeAll = ccui.Button:create()
btnExchangeAll:ignoreContentAdaptWithSize(false)
btnExchangeAll:loadTextureNormal("game/horserace_std/resource/button/qbdh.png",0)
btnExchangeAll:setTitleFontSize(14)
btnExchangeAll:setTitleColor(cc.c3b(65, 65, 70))
btnExchangeAll:setLayoutComponentEnabled(true)
btnExchangeAll:setName("btnExchangeAll")
btnExchangeAll:setTag(333)
btnExchangeAll:setCascadeColorEnabled(true)
btnExchangeAll:setCascadeOpacityEnabled(true)
btnExchangeAll:setPosition(310.0000, 120.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnExchangeAll)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1778)
layout:setSize(cc.size(421.0000, 144.0000))
layout:setLeftMargin(144.5000)
layout:setRightMargin(144.5000)
layout:setTopMargin(494.0000)
layout:setBottomMargin(59.0000)
ImgDBg:addChild(btnExchangeAll)

--Create btnClose
local btnClose = ccui.Button:create()
btnClose:ignoreContentAdaptWithSize(false)
btnClose:loadTextureNormal("game/horserace_std/resource/button/gb.png",0)
btnClose:setTitleFontSize(14)
btnClose:setTitleColor(cc.c3b(65, 65, 70))
btnClose:setLayoutComponentEnabled(true)
btnClose:setName("btnClose")
btnClose:setTag(339)
btnClose:setCascadeColorEnabled(true)
btnClose:setCascadeOpacityEnabled(true)
btnClose:setPosition(580.0000, 650.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnClose)
layout:setPositionPercentX(0.9386)
layout:setPositionPercentY(0.9481)
layout:setPercentWidth(0.2329)
layout:setPercentHeight(0.1911)
layout:setSize(cc.size(127.0000, 127.0000))
layout:setLeftMargin(455.5000)
layout:setRightMargin(-30.5000)
layout:setTopMargin(-29.5000)
layout:setBottomMargin(575.5000)
ImgDBg:addChild(btnClose)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

