--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")
--Node:setVisible(false)

--Create nodeCard
local nodeCard=cc.Node:create()
nodeCard:setName("nodeCard")
nodeCard:setTag(177)
nodeCard:setCascadeColorEnabled(true)
nodeCard:setCascadeOpacityEnabled(true)
nodeCard:setPosition(970.0000, 900.0000)
nodeCard:setScaleX(0.5000)
nodeCard:setScaleY(0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(nodeCard)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(960.0000)
layout:setRightMargin(-960.0000)
layout:setTopMargin(-930.0000)
layout:setBottomMargin(930.0000)
Node:addChild(nodeCard)

--Create imgCardTypeBG
local imgCardTypeBG = ccui.ImageView:create()
imgCardTypeBG:ignoreContentAdaptWithSize(false)
imgCardTypeBG:loadTexture("game/bairenniuniu_std/resource/image/cd.png",0)
imgCardTypeBG:setLayoutComponentEnabled(true)
imgCardTypeBG:setName("imgCardTypeBG")
imgCardTypeBG:setTag(611)
imgCardTypeBG:setCascadeColorEnabled(true)
imgCardTypeBG:setCascadeOpacityEnabled(true)
imgCardTypeBG:setPosition(960.0000, 860.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCardTypeBG)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(234.0000, 88.0000))
layout:setLeftMargin(900.0000)
layout:setRightMargin(-1578.0000)
layout:setTopMargin(-260.5000)
layout:setBottomMargin(147.5000)
Node:addChild(imgCardTypeBG)

--Create imgCardType
local imgCardType = ccui.ImageView:create()
imgCardType:ignoreContentAdaptWithSize(false)
imgCardType:loadTexture("game/bairenniuniu_std/resource/word/n8.png",0)
imgCardType:setLayoutComponentEnabled(true)
imgCardType:setName("imgCardType")
imgCardType:setTag(610)
imgCardType:setCascadeColorEnabled(true)
imgCardType:setCascadeOpacityEnabled(true)
imgCardType:setPosition(960.0000, 860.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCardType)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(71.0000, 35.0000))
layout:setLeftMargin(900.0000)
layout:setRightMargin(-1578.0000)
layout:setTopMargin(-260.5000)
layout:setBottomMargin(147.5000)
Node:addChild(imgCardType)

--Create imgMask
local imgMask = cc.Sprite:create("game/bairenniuniu_std/resource/image/xzk.png")
imgMask:setName("imgMask")
imgMask:setTag(128)
imgMask:setCascadeColorEnabled(true)
imgMask:setCascadeOpacityEnabled(true)
imgMask:setAnchorPoint(0.0000, 0.0000)
imgMask:setPosition(810.0000, 548.8430)
layout = ccui.LayoutComponent:bindLayoutComponent(imgMask)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(284.0000, 385.0000))
layout:setLeftMargin(810.0000)
layout:setRightMargin(-1094.0000)
layout:setTopMargin(-933.8430)
layout:setBottomMargin(548.8430)
Node:addChild(imgMask)

--Create nodeEffect
local nodeEffect=cc.Node:create()
nodeEffect:setName("nodeEffect")
nodeEffect:setTag(439)
nodeEffect:setCascadeColorEnabled(true)
nodeEffect:setCascadeOpacityEnabled(true)
nodeEffect:setPosition(960.0000, 930.0000)
nodeEffect:setScaleX(0.5000)
nodeEffect:setScaleY(0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(nodeEffect)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(960.0000)
layout:setRightMargin(-960.0000)
layout:setTopMargin(-930.0000)
layout:setBottomMargin(930.0000)
Node:addChild(nodeEffect)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

