--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create LabBeilv
local LabBeilv = ccui.ImageView:create()
LabBeilv:ignoreContentAdaptWithSize(false)
LabBeilv:loadTexture("game/bairenniuniu_std/resource/image/blb.png",0)
LabBeilv:setLayoutComponentEnabled(true)
LabBeilv:setName("LabBeilv")
LabBeilv:setTag(88)
LabBeilv:setCascadeColorEnabled(true)
LabBeilv:setCascadeOpacityEnabled(true)
LabBeilv:setPosition(960.0000, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(LabBeilv)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5417)
layout:setPercentHeight(0.3370)
layout:setSize({width = 1040.0000, height = 364.0000})
layout:setLeftMargin(440.0000)
layout:setRightMargin(440.0000)
layout:setTopMargin(358.0000)
layout:setBottomMargin(358.0000)
Scene:addChild(LabBeilv)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

