--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_Bg
local Image_Bg = ccui.ImageView:create()
Image_Bg:ignoreContentAdaptWithSize(false)
Image_Bg:loadTexture("game/bairenniuniu_std/resource/image/cdbj.png",0)
Image_Bg:setLayoutComponentEnabled(true)
Image_Bg:setName("Image_Bg")
Image_Bg:setTag(569)
Image_Bg:setCascadeColorEnabled(true)
Image_Bg:setCascadeOpacityEnabled(true)
Image_Bg:setPosition(1716.1480, 450.4567)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_Bg)
layout:setPositionPercentX(0.8938)
layout:setPositionPercentY(0.4171)
layout:setSize(cc.size(407.0000, 616.0000))
layout:setLeftMargin(1512.6480)
layout:setRightMargin(0.3521)
layout:setTopMargin(321.5433)
layout:setBottomMargin(142.4567)
Node:addChild(Image_Bg)

--Create BtnSet
local BtnSet = ccui.Button:create()
BtnSet:ignoreContentAdaptWithSize(false)
BtnSet:loadTextureNormal("Default/Button_Normal.png",0)
BtnSet:setTitleFontSize(14)
BtnSet:setTitleColor(cc.c3b(65, 65, 70))
BtnSet:setScale9Enabled(true)
BtnSet:setCapInsets(cc.rect(15,11,260,114))
BtnSet:setLayoutComponentEnabled(true)
BtnSet:setName("BtnSet")
BtnSet:setTag(570)
BtnSet:setCascadeColorEnabled(true)
BtnSet:setCascadeOpacityEnabled(true)
BtnSet:setPosition(1719.1500, 447.4576)
layout = ccui.LayoutComponent:bindLayoutComponent(BtnSet)
layout:setPositionPercentX(0.8954)
layout:setPositionPercentY(0.4143)
layout:setSize(cc.size(290.0000, 136.0000))
layout:setLeftMargin(1574.1500)
layout:setRightMargin(55.8503)
layout:setTopMargin(564.5424)
layout:setBottomMargin(379.4576)
Node:addChild(BtnSet)

--Create BtnHelp
local BtnHelp = ccui.Button:create()
BtnHelp:ignoreContentAdaptWithSize(false)
BtnHelp:loadTextureNormal("Default/Button_Normal.png",0)
BtnHelp:setTitleFontSize(14)
BtnHelp:setTitleColor(cc.c3b(65, 65, 70))
BtnHelp:setScale9Enabled(true)
BtnHelp:setCapInsets(cc.rect(15,11,260,114))
BtnHelp:setLayoutComponentEnabled(true)
BtnHelp:setName("BtnHelp")
BtnHelp:setTag(571)
BtnHelp:setCascadeColorEnabled(true)
BtnHelp:setCascadeOpacityEnabled(true)
BtnHelp:setPosition(1719.1500, 609.4564)
layout = ccui.LayoutComponent:bindLayoutComponent(BtnHelp)
layout:setPositionPercentX(0.8954)
layout:setPositionPercentY(0.5643)
layout:setSize(cc.size(290.0000, 136.0000))
layout:setLeftMargin(1574.1500)
layout:setRightMargin(55.8503)
layout:setTopMargin(402.5436)
layout:setBottomMargin(541.4564)
Node:addChild(BtnHelp)

--Create BtnExit
local BtnExit = ccui.Button:create()
BtnExit:ignoreContentAdaptWithSize(false)
BtnExit:loadTextureNormal("Default/Button_Normal.png",0)
BtnExit:setTitleFontSize(14)
BtnExit:setTitleColor(cc.c3b(65, 65, 70))
BtnExit:setScale9Enabled(true)
BtnExit:setCapInsets(cc.rect(15,11,260,114))
BtnExit:setLayoutComponentEnabled(true)
BtnExit:setName("BtnExit")
BtnExit:setTag(572)
BtnExit:setCascadeColorEnabled(true)
BtnExit:setCascadeOpacityEnabled(true)
BtnExit:setPosition(1719.1500, 287.4572)
layout = ccui.LayoutComponent:bindLayoutComponent(BtnExit)
layout:setPositionPercentX(0.8954)
layout:setPositionPercentY(0.2662)
layout:setSize(cc.size(290.0000, 136.0000))
layout:setLeftMargin(1574.1500)
layout:setRightMargin(55.8503)
layout:setTopMargin(724.5428)
layout:setBottomMargin(219.4572)
Node:addChild(BtnExit)

--Create zk_1
-- local zk_1 = cc.Sprite:create("game/bairenniuniu_std/resource/button/zk.png")
-- zk_1:setName("zk_1")
-- zk_1:setTag(92)
-- zk_1:setCascadeColorEnabled(true)
-- zk_1:setCascadeOpacityEnabled(true)
-- zk_1:setPosition(1703.6420, 812.9064)
-- zk_1:setRotationSkewX(-90.0000)
-- zk_1:setRotationSkewY(-90.0000)
-- layout = ccui.LayoutComponent:bindLayoutComponent(zk_1)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(111.0000, 249.0000))
-- layout:setLeftMargin(1648.1420)
-- layout:setRightMargin(-1759.1420)
-- layout:setTopMargin(-937.4064)
-- layout:setBottomMargin(688.4064)
-- Node:addChild(zk_1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

