--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create imgBg
local imgBg = ccui.ImageView:create()
imgBg:ignoreContentAdaptWithSize(false)
imgBg:loadTexture("update/resource/bg.png",0)
imgBg:setLayoutComponentEnabled(true)
imgBg:setName("imgBg")
imgBg:setTag(269)
imgBg:setCascadeColorEnabled(true)
imgBg:setCascadeOpacityEnabled(true)
imgBg:setPosition(960.0000, 540.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1920.0000, height = 1080.0000})
Scene:addChild(imgBg)

--Create nodeAct
local nodeAct=cc.Node:create()
nodeAct:setName("nodeCard")
Scene:addChild(nodeAct)

-- --Create imgBg
-- local light1 = cc.Sprite:create("update/resource/bg_1.png")
-- light1:setCascadeColorEnabled(true)
-- light1:setCascadeOpacityEnabled(true)
-- light1:setPosition(960.0000, 192.0000)
-- layout = ccui.LayoutComponent:bindLayoutComponent(light1)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(1920.0000, 394.0000))
-- layout:setLeftMargin(844.3009)
-- layout:setRightMargin(-1074.3010)
-- layout:setTopMargin(-1078.0400)
-- layout:setBottomMargin(824.0400)
-- Scene:addChild(light1)

--灯光2
local light2 = cc.Sprite:create("update/resource/Logo.png")
light2:setCascadeColorEnabled(true)
light2:setCascadeOpacityEnabled(true)
light2:setPosition(1460.0000, 930.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(light2)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(921.0000, 649.0000))
layout:setLeftMargin(844.3009)
layout:setRightMargin(-1074.3010)
layout:setTopMargin(-1078.0400)
layout:setBottomMargin(824.0400)
Scene:addChild(light2)

--Create updateBj
local updateBj = ccui.ImageView:create()
updateBj:ignoreContentAdaptWithSize(false)
updateBj:loadTexture("update/resource/jdt-01.png",0)
updateBj:setLayoutComponentEnabled(true)
updateBj:setName("updateBj")
updateBj:setTag(270)
updateBj:setCascadeColorEnabled(true)
updateBj:setCascadeOpacityEnabled(true)
updateBj:setPosition(1350.0000, 450.0000)
--updateBj:setScale(0.65)
layout = ccui.LayoutComponent:bindLayoutComponent(updateBj)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2111)
layout:setPercentWidth(0.5927)
layout:setPercentHeight(0.0398)
layout:setSize({width = 776.0000, height = 35.0000})
layout:setLeftMargin(390.9999)
layout:setRightMargin(391.0000)
layout:setTopMargin(830.5005)
layout:setBottomMargin(206.4995)
Scene:addChild(updateBj)

--Create LoadingBar_update
local LoadingBar_update = ccui.LoadingBar:create()
LoadingBar_update:loadTexture("update/resource/jdt-02.PNG",0)
LoadingBar_update:ignoreContentAdaptWithSize(false)
LoadingBar_update:setPercent(57)
LoadingBar_update:setLayoutComponentEnabled(true)
LoadingBar_update:setName("LoadingBar_update")
LoadingBar_update:setTag(271)
LoadingBar_update:setCascadeColorEnabled(true)
LoadingBar_update:setCascadeOpacityEnabled(true)
--LoadingBar_update:setPosition(960.0000, 220.0000)
LoadingBar_update:setPosition(1350.0000, 450.0000)
--LoadingBar_update:setScale(0.65)
layout = ccui.LayoutComponent:bindLayoutComponent(LoadingBar_update)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2111)
layout:setPercentWidth(0.5927)
layout:setPercentHeight(0.0398)
layout:setSize({width = 776.0000, height = 35.0000})
layout:setLeftMargin(391.0000)
layout:setRightMargin(391.0000)
layout:setTopMargin(830.5000)
layout:setBottomMargin(206.5000)
Scene:addChild(LoadingBar_update)

--Create textLoading
local textLoading = ccui.Text:create()
textLoading:ignoreContentAdaptWithSize(true)
textLoading:setTextAreaSize({width = 0, height = 0})
textLoading:setFontName("simhei.ttf")
textLoading:setFontSize(48)
textLoading:setString([[游戏加载中，马上就好]])
textLoading:setLayoutComponentEnabled(true)
textLoading:setName("textLoading")
textLoading:setTag(272)
textLoading:setCascadeColorEnabled(true)
textLoading:setCascadeOpacityEnabled(true)
textLoading:setPosition(1350.0000, 400.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(textLoading)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.1602)
layout:setPercentWidth(0.2505)
layout:setPercentHeight(0.0509)
layout:setSize({width = 481.0000, height = 55.0000})
layout:setLeftMargin(719.5000)
layout:setRightMargin(719.5000)
layout:setTopMargin(879.5311)
layout:setBottomMargin(145.4689)
Scene:addChild(textLoading)

--Create nodeLoading
local nodeLoading=cc.Node:create()
nodeLoading:setName("nodeLoading")
nodeLoading:setTag(273)
nodeLoading:setCascadeColorEnabled(true)
nodeLoading:setCascadeOpacityEnabled(true)
nodeLoading:setPosition(960.0000, 290.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(nodeLoading)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2685)
layout:setLeftMargin(960.0000)
layout:setRightMargin(960.0000)
layout:setTopMargin(790.0000)
layout:setBottomMargin(290.0000)
Scene:addChild(nodeLoading)

--Create btnClose
local btnExit = ccui.Button:create()
btnExit:ignoreContentAdaptWithSize(false)
btnExit:loadTextureNormal("update/resource/btnClose1.png",0)
btnExit:loadTexturePressed("update/resource/btnClose3.png",0)
btnExit:setTitleFontSize(14)
btnExit:setTitleColor({r = 65, g = 65, b = 70})
btnExit:setLayoutComponentEnabled(true)
btnExit:setName("btnExit")
btnExit:setTag(163)
btnExit:setCascadeColorEnabled(true)
btnExit:setCascadeOpacityEnabled(true)
btnExit:setPosition(1899.0000, 1064.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnExit)
layout:setPositionPercentX(0.0339)
layout:setPositionPercentY(0.9444)
layout:setPercentWidth(0.0458)
layout:setPercentHeight(0.0852)
layout:setSize({width = 42.0000, height = 32.0000})
layout:setLeftMargin(21.0002)
layout:setRightMargin(1811.0000)
layout:setTopMargin(13.9990)
layout:setBottomMargin(974.0009)
Scene:addChild(btnExit)

--Create btnClose
local btnSmall = ccui.Button:create()
btnSmall:ignoreContentAdaptWithSize(false)
btnSmall:loadTextureNormal("lobby/resource/button/btnSmall1.png",0)
btnSmall:loadTexturePressed("lobby/resource/button/btnSmall3.png",0)
btnSmall:setTitleFontSize(14)
btnSmall:setTitleColor({r = 65, g = 65, b = 70})
btnSmall:setLayoutComponentEnabled(true)
btnSmall:setName("btnSmall")
btnSmall:setTag(163)
btnSmall:setCascadeColorEnabled(true)
btnSmall:setCascadeOpacityEnabled(true)
btnSmall:setPosition(1857.0000, 1064.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSmall)
layout:setPositionPercentX(0.0339)
layout:setPositionPercentY(0.9444)
layout:setPercentWidth(0.0458)
layout:setPercentHeight(0.0852)
layout:setSize({width = 42.0000, height = 32.0000})
layout:setLeftMargin(21.0002)
layout:setRightMargin(1811.0000)
layout:setTopMargin(13.9990)
layout:setBottomMargin(974.0009)
Scene:addChild(btnSmall)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

