--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------


-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create imgBg
local imgBg = cc.Sprite:create("game/joyfive_std/resource/image/bg.png")
imgBg:setName("imgBg")
imgBg:setTag(3)
imgBg:setCascadeColorEnabled(true)
imgBg:setCascadeOpacityEnabled(true)
imgBg:setAnchorPoint(0.0000, 0.0000)
imgBg:setPosition(-1.3612, 0.0000)
imgBg:setOpacity(203)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBg)
layout:setPositionPercentX(-0.0007)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(1920.0000, 1080.0000))
layout:setLeftMargin(-1.3612)
layout:setRightMargin(1.3612)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
Scene:addChild(imgBg)

--Create btnAddChips
local btnAddChips = ccui.Button:create()
btnAddChips:ignoreContentAdaptWithSize(false)
btnAddChips:loadTextureNormal("game/joyfive_std/resource/button/sf1.png",0)
btnAddChips:loadTexturePressed("game/joyfive_std/resource/button/sf3.png",0)
btnAddChips:loadTextureDisabled("game/joyfive_std/resource/button/sf1.png",0)
btnAddChips:setTitleFontSize(14)
btnAddChips:setTitleColor(cc.c3b(65, 65, 70))
btnAddChips:setScale9Enabled(true)
btnAddChips:setCapInsets(cc.rect(15,11,78,24))
btnAddChips:setLayoutComponentEnabled(true)
btnAddChips:setName("btnAddChips")
btnAddChips:setTag(248)
btnAddChips:setCascadeColorEnabled(true)
btnAddChips:setCascadeOpacityEnabled(true)
btnAddChips:setPosition(115.4465, 189.4771)
layout = ccui.LayoutComponent:bindLayoutComponent(btnAddChips)
layout:setPositionPercentX(0.0601)
layout:setPositionPercentY(0.1754)
layout:setPercentWidth(0.0562)
layout:setPercentHeight(0.0426)
layout:setSize(cc.size(108.0000, 46.0000))
layout:setLeftMargin(61.4465)
layout:setRightMargin(1750.5530)
layout:setTopMargin(867.5229)
layout:setBottomMargin(166.4771)
Scene:addChild(btnAddChips)

--Create btnSubtractChips
local btnSubtractChips = ccui.Button:create()
btnSubtractChips:ignoreContentAdaptWithSize(false)
btnSubtractChips:loadTextureNormal("game/joyfive_std/resource/button/xf1.png",0)
btnSubtractChips:loadTexturePressed("game/joyfive_std/resource/button/xf3.png",0)
btnSubtractChips:loadTextureDisabled("game/joyfive_std/resource/button/xf1.png",0)
btnSubtractChips:setTitleFontSize(14)
btnSubtractChips:setTitleColor(cc.c3b(65, 65, 70))
btnSubtractChips:setScale9Enabled(true)
btnSubtractChips:setCapInsets(cc.rect(15,11,78,24))
btnSubtractChips:setLayoutComponentEnabled(true)
btnSubtractChips:setName("btnSubtractChips")
btnSubtractChips:setTag(249)
btnSubtractChips:setCascadeColorEnabled(true)
btnSubtractChips:setCascadeOpacityEnabled(true)
btnSubtractChips:setPosition(283.7433, 189.4771)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSubtractChips)
layout:setPositionPercentX(0.1478)
layout:setPositionPercentY(0.1754)
layout:setPercentWidth(0.0562)
layout:setPercentHeight(0.0426)
layout:setSize(cc.size(108.0000, 46.0000))
layout:setLeftMargin(229.7433)
layout:setRightMargin(1582.2570)
layout:setTopMargin(867.5229)
layout:setBottomMargin(166.4771)
Scene:addChild(btnSubtractChips)

--Create btnStart
local btnStart = ccui.Button:create()
btnStart:ignoreContentAdaptWithSize(false)
btnStart:loadTextureNormal("game/joyfive_std/resource/button/ks1.png",0)
btnStart:loadTexturePressed("game/joyfive_std/resource/button/ks3.png",0)
btnStart:loadTextureDisabled("game/joyfive_std/resource/button/ks1.png",0)
btnStart:setTitleFontSize(14)
btnStart:setTitleColor(cc.c3b(65, 65, 70))
btnStart:setScale9Enabled(true)
btnStart:setCapInsets(cc.rect(15,11,114,36))
btnStart:setLayoutComponentEnabled(true)
btnStart:setName("btnStart")
btnStart:setTag(830)
btnStart:setCascadeColorEnabled(true)
btnStart:setCascadeOpacityEnabled(true)
btnStart:setPosition(567.9999, 193.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnStart)
layout:setPositionPercentX(0.2958)
layout:setPositionPercentY(0.1787)
layout:setPercentWidth(0.0750)
layout:setPercentHeight(0.0537)
layout:setSize(cc.size(144.0000, 58.0000))
layout:setLeftMargin(495.9999)
layout:setRightMargin(1280.0000)
layout:setTopMargin(858.0000)
layout:setBottomMargin(164.0000)
Scene:addChild(btnStart)

--Create btnChangeTable
local btnChangeTable = ccui.Button:create()
btnChangeTable:ignoreContentAdaptWithSize(false)
btnChangeTable:loadTextureNormal("game/joyfive_std/resource/button/hz1.png",0)
btnChangeTable:loadTexturePressed("game/joyfive_std/resource/button/hz3.png",0)
btnChangeTable:loadTextureDisabled("game/joyfive_std/resource/button/hz1.png",0)
btnChangeTable:setTitleFontSize(14)
btnChangeTable:setTitleColor(cc.c3b(65, 65, 70))
btnChangeTable:setScale9Enabled(true)
btnChangeTable:setCapInsets(cc.rect(15,11,114,36))
btnChangeTable:setLayoutComponentEnabled(true)
btnChangeTable:setName("btnChangeTable")
btnChangeTable:setTag(831)
btnChangeTable:setCascadeColorEnabled(true)
btnChangeTable:setCascadeOpacityEnabled(true)
btnChangeTable:setPosition(1070.0000, 193.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnChangeTable)
layout:setPositionPercentX(0.5573)
layout:setPositionPercentY(0.1787)
layout:setPercentWidth(0.0750)
layout:setPercentHeight(0.0537)
layout:setSize(cc.size(144.0000, 58.0000))
layout:setLeftMargin(998.0000)
layout:setRightMargin(778.0000)
layout:setTopMargin(858.0000)
layout:setBottomMargin(164.0000)
Scene:addChild(btnChangeTable)

--Create totalChipsCon
local totalChipsCon=cc.Node:create()
totalChipsCon:setName("totalChipsCon")
totalChipsCon:setTag(256)
totalChipsCon:setCascadeColorEnabled(true)
totalChipsCon:setCascadeOpacityEnabled(true)
totalChipsCon:setPosition(810.7994, 483.9100)
layout = ccui.LayoutComponent:bindLayoutComponent(totalChipsCon)
layout:setPositionPercentX(0.4223)
layout:setPositionPercentY(0.4481)
layout:setLeftMargin(810.7994)
layout:setRightMargin(1109.2010)
layout:setTopMargin(596.0900)
layout:setBottomMargin(483.9100)
Scene:addChild(totalChipsCon)

--Create playerChipsCon_1
local playerChipsCon_1=cc.Node:create()
playerChipsCon_1:setName("playerChipsCon_1")
playerChipsCon_1:setTag(569)
playerChipsCon_1:setCascadeColorEnabled(true)
playerChipsCon_1:setCascadeOpacityEnabled(true)
playerChipsCon_1:setPosition(667.7980, 259.9106)
layout = ccui.LayoutComponent:bindLayoutComponent(playerChipsCon_1)
layout:setPositionPercentX(0.3478)
layout:setPositionPercentY(0.2407)
layout:setLeftMargin(667.7980)
layout:setRightMargin(1252.2020)
layout:setTopMargin(820.0894)
layout:setBottomMargin(259.9106)
Scene:addChild(playerChipsCon_1)

--Create playerChipsCon_2
local playerChipsCon_2=cc.Node:create()
playerChipsCon_2:setName("playerChipsCon_2")
playerChipsCon_2:setTag(570)
playerChipsCon_2:setCascadeColorEnabled(true)
playerChipsCon_2:setCascadeOpacityEnabled(true)
playerChipsCon_2:setPosition(549.7998, 592.9138)
layout = ccui.LayoutComponent:bindLayoutComponent(playerChipsCon_2)
layout:setPositionPercentX(0.2864)
layout:setPositionPercentY(0.5490)
layout:setLeftMargin(549.7998)
layout:setRightMargin(1370.2000)
layout:setTopMargin(487.0862)
layout:setBottomMargin(592.9138)
Scene:addChild(playerChipsCon_2)

--Create playerChipsCon_3
local playerChipsCon_3=cc.Node:create()
playerChipsCon_3:setName("playerChipsCon_3")
playerChipsCon_3:setTag(571)
playerChipsCon_3:setCascadeColorEnabled(true)
playerChipsCon_3:setCascadeOpacityEnabled(true)
playerChipsCon_3:setPosition(796.8006, 676.9121)
layout = ccui.LayoutComponent:bindLayoutComponent(playerChipsCon_3)
layout:setPositionPercentX(0.4150)
layout:setPositionPercentY(0.6268)
layout:setLeftMargin(796.8006)
layout:setRightMargin(1123.1990)
layout:setTopMargin(403.0879)
layout:setBottomMargin(676.9121)
Scene:addChild(playerChipsCon_3)

--Create playerChipsCon_4
local playerChipsCon_4=cc.Node:create()
playerChipsCon_4:setName("playerChipsCon_4")
playerChipsCon_4:setTag(572)
playerChipsCon_4:setCascadeColorEnabled(true)
playerChipsCon_4:setCascadeOpacityEnabled(true)
playerChipsCon_4:setPosition(970.8009, 447.9125)
layout = ccui.LayoutComponent:bindLayoutComponent(playerChipsCon_4)
layout:setPositionPercentX(0.5056)
layout:setPositionPercentY(0.4147)
layout:setLeftMargin(970.8009)
layout:setRightMargin(949.1991)
layout:setTopMargin(632.0875)
layout:setBottomMargin(447.9125)
Scene:addChild(playerChipsCon_4)

--Create spTitle
local spTitle = cc.Sprite:create("game/joyfive_std/resource/image/dht.png")
spTitle:setName("spTitle")
spTitle:setTag(44)
spTitle:setCascadeColorEnabled(true)
spTitle:setCascadeOpacityEnabled(true)
spTitle:setAnchorPoint(0.5000, 1.0000)
spTitle:setPosition(960.0000, 1080.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(spTitle)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(1.0000)
layout:setSize(cc.size(1920.0000, 36.0000))
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(1044.0000)
Scene:addChild(spTitle)

--Create txtTotalBetChips
local txtTotalBetChips = ccui.Text:create()
txtTotalBetChips:ignoreContentAdaptWithSize(true)
txtTotalBetChips:setTextAreaSize(cc.size(0, 0))
txtTotalBetChips:setFontSize(36)
txtTotalBetChips:setString([[1234567890
]])
txtTotalBetChips:setTextHorizontalAlignment(1)
txtTotalBetChips:setTextVerticalAlignment(1)
txtTotalBetChips:enableShadow(cc.c4b(110, 110, 110, 255), cc.size(2.0000, -2.0000), 0)
txtTotalBetChips:setLayoutComponentEnabled(true)
txtTotalBetChips:setName("txtTotalBetChips")
txtTotalBetChips:setTag(532)
txtTotalBetChips:setCascadeColorEnabled(true)
txtTotalBetChips:setCascadeOpacityEnabled(true)
txtTotalBetChips:setVisible(false)
txtTotalBetChips:setPosition(814.0250, 610.0382)
txtTotalBetChips:setColor(cc.c3b(255, 165, 0))
layout = ccui.LayoutComponent:bindLayoutComponent(txtTotalBetChips)
layout:setPositionPercentX(0.4240)
layout:setPositionPercentY(0.5649)
layout:setSize(cc.size(180.0000, 72.0000))
layout:setLeftMargin(760.0250)
layout:setRightMargin(1051.9750)
layout:setTopMargin(433.9618)
layout:setBottomMargin(574.0382)
Scene:addChild(txtTotalBetChips)

--Create fntChips_1
local fntChips_1 = ccui.TextAtlas:create([[012345678]],
													"game/joyfive_std/resource/number/number1.png",
													12,
													20,
													"0")
fntChips_1:setLayoutComponentEnabled(true)
fntChips_1:setName("fntChips_1")
fntChips_1:setTag(141)
fntChips_1:setCascadeColorEnabled(true)
fntChips_1:setCascadeOpacityEnabled(true)
fntChips_1:setPosition(637.9160, 242.2704)
layout = ccui.LayoutComponent:bindLayoutComponent(fntChips_1)
layout:setPositionPercentX(0.3322)
layout:setPositionPercentY(0.2243)
layout:setPercentWidth(0.0661)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(108.0000, 20.0000))
layout:setLeftMargin(583.9160)
layout:setRightMargin(1228.0840)
layout:setTopMargin(827.7296)
layout:setBottomMargin(232.2704)
Scene:addChild(fntChips_1)

--Create fntChips_2
local fntChips_2 = ccui.TextAtlas:create([[012345678]],
													"game/joyfive_std/resource/number/number1.png",
													12,
													20,
													"0")
fntChips_2:setLayoutComponentEnabled(true)
fntChips_2:setName("fntChips_2")
fntChips_2:setTag(142)
fntChips_2:setCascadeColorEnabled(true)
fntChips_2:setCascadeOpacityEnabled(true)
fntChips_2:setPosition(531.8460, 639.7786)
fntChips_2:setRotationSkewX(90.0000)
fntChips_2:setRotationSkewY(90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fntChips_2)
layout:setPositionPercentX(0.2770)
layout:setPositionPercentY(0.5924)
layout:setPercentWidth(0.0661)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(108.0000, 20.0000))
layout:setLeftMargin(477.8460)
layout:setRightMargin(1334.1540)
layout:setTopMargin(430.2214)
layout:setBottomMargin(629.7786)
Scene:addChild(fntChips_2)

--Create fntChips_3
local fntChips_3 = ccui.TextAtlas:create([[012345678]],
													"game/joyfive_std/resource/number/number1.png",
													12,
													20,
													"0")
fntChips_3:setLayoutComponentEnabled(true)
fntChips_3:setName("fntChips_3")
fntChips_3:setTag(143)
fntChips_3:setCascadeColorEnabled(true)
fntChips_3:setCascadeOpacityEnabled(true)
fntChips_3:setPosition(870.7803, 813.7198)
layout = ccui.LayoutComponent:bindLayoutComponent(fntChips_3)
layout:setPositionPercentX(0.4535)
layout:setPositionPercentY(0.7534)
layout:setPercentWidth(0.0661)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(108.0000, 20.0000))
layout:setLeftMargin(816.7803)
layout:setRightMargin(995.2197)
layout:setTopMargin(256.2802)
layout:setBottomMargin(803.7198)
Scene:addChild(fntChips_3)

--Create fntChips_4
local fntChips_4 = ccui.TextAtlas:create([[012345678]],
													"game/joyfive_std/resource/number/number1.png",
													12,
													20,
													"0")
fntChips_4:setLayoutComponentEnabled(true)
fntChips_4:setName("fntChips_4")
fntChips_4:setTag(144)
fntChips_4:setCascadeColorEnabled(true)
fntChips_4:setCascadeOpacityEnabled(true)
fntChips_4:setPosition(1105.4360, 465.0955)
fntChips_4:setRotationSkewX(270.0000)
fntChips_4:setRotationSkewY(270.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fntChips_4)
layout:setPositionPercentX(0.5757)
layout:setPositionPercentY(0.4306)
layout:setPercentWidth(0.0661)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(108.0000, 20.0000))
layout:setLeftMargin(1051.4360)
layout:setRightMargin(760.5636)
layout:setTopMargin(604.9045)
layout:setBottomMargin(455.0955)
Scene:addChild(fntChips_4)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

