--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------


-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgPlayerBg
local imgPlayerBg = cc.Sprite:create("game/joyfive_std/resource/image/xxbj.png")
imgPlayerBg:setName("imgPlayerBg")
imgPlayerBg:setTag(323)
imgPlayerBg:setCascadeColorEnabled(true)
imgPlayerBg:setCascadeOpacityEnabled(true)
imgPlayerBg:setPosition(1449.4470, 615.0211)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayerBg)
layout:setPositionPercentX(0.7549)
layout:setPositionPercentY(0.5695)
layout:setSize(cc.size(346.0000, 172.0000))
layout:setLeftMargin(1276.4470)
layout:setRightMargin(297.5530)
layout:setTopMargin(378.9789)
layout:setBottomMargin(529.0211)
Node:addChild(imgPlayerBg)

--Create imgHead
local imgHead = cc.Sprite:create("game/joyfive_std/resource/head/1.png")
imgHead:setName("imgHead")
imgHead:setTag(324)
imgHead:setCascadeColorEnabled(true)
imgHead:setCascadeOpacityEnabled(true)
imgHead:setPosition(1359.5080, 617.2594)
layout = ccui.LayoutComponent:bindLayoutComponent(imgHead)
layout:setPositionPercentX(0.7081)
layout:setPositionPercentY(0.5715)
layout:setSize(cc.size(115.0000, 115.0000))
layout:setLeftMargin(1302.0080)
layout:setRightMargin(502.9922)
layout:setTopMargin(405.2406)
layout:setBottomMargin(559.7594)
Node:addChild(imgHead)

--Create labName
local labName = ccui.Text:create()
labName:ignoreContentAdaptWithSize(true)
labName:setTextAreaSize(cc.size(0, 0))
labName:setFontSize(16)
labName:setString([[让往事随风随风随风]])
labName:setLayoutComponentEnabled(true)
labName:setName("labName")
labName:setTag(325)
labName:setCascadeColorEnabled(true)
labName:setCascadeOpacityEnabled(true)
labName:setPosition(1504.2440, 655.5899)
labName:setColor(cc.c3b(157, 149, 160))
layout = ccui.LayoutComponent:bindLayoutComponent(labName)
layout:setPositionPercentX(0.7835)
layout:setPositionPercentY(0.6070)
layout:setPercentWidth(0.0521)
layout:setPercentHeight(0.0213)
layout:setSize(cc.size(144.0000, 16.0000))
layout:setLeftMargin(1432.2440)
layout:setRightMargin(343.7563)
layout:setTopMargin(416.4101)
layout:setBottomMargin(647.5899)
Node:addChild(labName)

--Create fntChips
local fntChips = ccui.TextAtlas:create([[012345678]],
													"game/joyfive_std/resource/number/number1.png",
													12,
													20,
													"0")
fntChips:setLayoutComponentEnabled(true)
fntChips:setName("fntChips")
fntChips:setTag(326)
fntChips:setCascadeColorEnabled(true)
fntChips:setCascadeOpacityEnabled(true)
fntChips:setAnchorPoint(0.0000, 0.5000)
fntChips:setPosition(1468.7480, 588.9157)
layout = ccui.LayoutComponent:bindLayoutComponent(fntChips)
layout:setPositionPercentX(0.7650)
layout:setPositionPercentY(0.5453)
layout:setPercentWidth(0.0661)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(108.0000, 20.0000))
layout:setLeftMargin(1468.7480)
layout:setRightMargin(343.2520)
layout:setTopMargin(481.0843)
layout:setBottomMargin(578.9157)
Node:addChild(fntChips)

--Create imCardBg
local imCardBg = cc.Sprite:create("game/joyfive_std/resource/image/pbg.png")
imCardBg:setName("imCardBg")
imCardBg:setTag(327)
imCardBg:setCascadeColorEnabled(true)
imCardBg:setCascadeOpacityEnabled(true)
imCardBg:setPosition(1449.1240, 454.1463)
layout = ccui.LayoutComponent:bindLayoutComponent(imCardBg)
layout:setPositionPercentX(0.7548)
layout:setPositionPercentY(0.4205)
layout:setSize(cc.size(290.0000, 152.0000))
layout:setLeftMargin(1304.1240)
layout:setRightMargin(325.8762)
layout:setTopMargin(549.8537)
layout:setBottomMargin(378.1463)
Node:addChild(imCardBg)

--Create imgCard1
local imgCard1 = ccui.ImageView:create()
imgCard1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
imgCard1:loadTexture("BM.png",1)
imgCard1:setLayoutComponentEnabled(true)
imgCard1:setName("imgCard1")
imgCard1:setTag(355)
imgCard1:setCascadeColorEnabled(true)
imgCard1:setCascadeOpacityEnabled(true)
imgCard1:setPosition(1364.7600, 450.3900)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard1)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(1318.7600)
layout:setRightMargin(-1410.7600)
layout:setTopMargin(-511.3900)
layout:setBottomMargin(389.3900)
Node:addChild(imgCard1)

--Create imgCard2
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard2 = cc.Sprite:createWithSpriteFrameName("FK_1.png")
imgCard2:setName("imgCard2")
imgCard2:setTag(329)
imgCard2:setCascadeColorEnabled(true)
imgCard2:setCascadeOpacityEnabled(true)
imgCard2:setPosition(1410.0520, 450.3946)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard2)
layout:setPositionPercentX(0.7344)
layout:setPositionPercentY(0.4170)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(1364.0520)
layout:setRightMargin(463.9484)
layout:setTopMargin(568.6054)
layout:setBottomMargin(389.3946)
Node:addChild(imgCard2)

--Create imgCard3
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard3 = cc.Sprite:createWithSpriteFrameName("FK_3.png")
imgCard3:setName("imgCard3")
imgCard3:setTag(330)
imgCard3:setCascadeColorEnabled(true)
imgCard3:setCascadeOpacityEnabled(true)
imgCard3:setPosition(1449.7320, 450.3946)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard3)
layout:setPositionPercentX(0.7551)
layout:setPositionPercentY(0.4170)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(1403.7320)
layout:setRightMargin(424.2676)
layout:setTopMargin(568.6054)
layout:setBottomMargin(389.3946)
Node:addChild(imgCard3)

--Create imgCard4
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard4 = cc.Sprite:createWithSpriteFrameName("FK_4.png")
imgCard4:setName("imgCard4")
imgCard4:setTag(331)
imgCard4:setCascadeColorEnabled(true)
imgCard4:setCascadeOpacityEnabled(true)
imgCard4:setPosition(1489.4080, 450.3946)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard4)
layout:setPositionPercentX(0.7757)
layout:setPositionPercentY(0.4170)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(1443.4080)
layout:setRightMargin(384.5924)
layout:setTopMargin(568.6054)
layout:setBottomMargin(389.3946)
Node:addChild(imgCard4)

--Create imgCard5
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard5 = cc.Sprite:createWithSpriteFrameName("FK_5.png")
imgCard5:setName("imgCard5")
imgCard5:setTag(332)
imgCard5:setCascadeColorEnabled(true)
imgCard5:setCascadeOpacityEnabled(true)
imgCard5:setPosition(1532.2160, 450.3946)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard5)
layout:setPositionPercentX(0.7980)
layout:setPositionPercentY(0.4170)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(1486.2160)
layout:setRightMargin(341.7842)
layout:setTopMargin(568.6054)
layout:setBottomMargin(389.3946)
Node:addChild(imgCard5)

--Create imgSettleAccountsWin
local imgSettleAccountsWin = cc.Sprite:create("game/joyfive_std/resource/image/jsbg.png")
imgSettleAccountsWin:setName("imgSettleAccountsWin")
imgSettleAccountsWin:setTag(333)
imgSettleAccountsWin:setCascadeColorEnabled(true)
imgSettleAccountsWin:setCascadeOpacityEnabled(true)
imgSettleAccountsWin:setPosition(971.9335, 597.3961)
layout = ccui.LayoutComponent:bindLayoutComponent(imgSettleAccountsWin)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(279.0000, 90.0000))
layout:setLeftMargin(832.4335)
layout:setRightMargin(-1111.4330)
layout:setTopMargin(-642.3961)
layout:setBottomMargin(552.3961)
Node:addChild(imgSettleAccountsWin)

--Create fntSettleAccountsWin
local fntSettleAccountsWin = ccui.TextBMFont:create()
fntSettleAccountsWin:setFntFile("game/joyfive_std/resource/number/joyfivechips.fnt")
fntSettleAccountsWin:setString([[+0123456789]])
fntSettleAccountsWin:setLayoutComponentEnabled(true)
fntSettleAccountsWin:setName("fntSettleAccountsWin")
fntSettleAccountsWin:setTag(334)
fntSettleAccountsWin:setCascadeColorEnabled(true)
fntSettleAccountsWin:setCascadeOpacityEnabled(true)
fntSettleAccountsWin:setPosition(970.4172, 607.1400)
layout = ccui.LayoutComponent:bindLayoutComponent(fntSettleAccountsWin)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(0.0224)
layout:setPercentHeight(0.0269)
layout:setSize(cc.size(224.0000, 29.0000))
layout:setLeftMargin(858.4172)
layout:setRightMargin(-1082.4170)
layout:setTopMargin(-621.6400)
layout:setBottomMargin(592.6400)
Node:addChild(fntSettleAccountsWin)

--Create imgSettleAccountsLose
local imgSettleAccountsLose = cc.Sprite:create("game/joyfive_std/resource/image/jsbg1.png")
imgSettleAccountsLose:setName("imgSettleAccountsLose")
imgSettleAccountsLose:setTag(616)
imgSettleAccountsLose:setCascadeColorEnabled(true)
imgSettleAccountsLose:setCascadeOpacityEnabled(true)
imgSettleAccountsLose:setPosition(972.7297, 597.4316)
layout = ccui.LayoutComponent:bindLayoutComponent(imgSettleAccountsLose)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(279.0000, 90.0000))
layout:setLeftMargin(833.2297)
layout:setRightMargin(-1112.2300)
layout:setTopMargin(-642.4316)
layout:setBottomMargin(552.4316)
Node:addChild(imgSettleAccountsLose)

--Create fntSettleAccountsLose
local fntSettleAccountsLose = ccui.TextBMFont:create()
fntSettleAccountsLose:setFntFile("game/joyfive_std/resource/number/lose.fnt")
fntSettleAccountsLose:setString([[-0123456789]])
fntSettleAccountsLose:setLayoutComponentEnabled(true)
fntSettleAccountsLose:setName("fntSettleAccountsLose")
fntSettleAccountsLose:setTag(617)
fntSettleAccountsLose:setCascadeColorEnabled(true)
fntSettleAccountsLose:setCascadeOpacityEnabled(true)
fntSettleAccountsLose:setPosition(971.1942, 607.1715)
layout = ccui.LayoutComponent:bindLayoutComponent(fntSettleAccountsLose)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(223.0000, 29.0000))
layout:setLeftMargin(859.6942)
layout:setRightMargin(-1082.6940)
layout:setTopMargin(-621.6715)
layout:setBottomMargin(592.6715)
Node:addChild(fntSettleAccountsLose)

--Create spBetType
local spBetType = cc.Sprite:create("game/joyfive_std/resource/word/gz.png")
spBetType:setName("spBetType")
spBetType:setTag(335)
spBetType:setCascadeColorEnabled(true)
spBetType:setCascadeOpacityEnabled(true)
spBetType:setPosition(1241.8370, 611.6371)
layout = ccui.LayoutComponent:bindLayoutComponent(spBetType)
layout:setPositionPercentX(0.6468)
layout:setPositionPercentY(0.5663)
layout:setSize(cc.size(78.0000, 26.0000))
layout:setLeftMargin(1202.8370)
layout:setRightMargin(639.1635)
layout:setTopMargin(455.3629)
layout:setBottomMargin(598.6371)
Node:addChild(spBetType)

--Create imgReady
local imgReady = cc.Sprite:create("game/joyfive_std/resource/word/zb.png")
imgReady:setName("imgReady")
imgReady:setTag(336)
imgReady:setCascadeColorEnabled(true)
imgReady:setCascadeOpacityEnabled(true)
imgReady:setPosition(1206.4380, 606.2227)
layout = ccui.LayoutComponent:bindLayoutComponent(imgReady)
layout:setPositionPercentX(0.6284)
layout:setPositionPercentY(0.5613)
layout:setSize(cc.size(162.0000, 105.0000))
layout:setLeftMargin(1125.4380)
layout:setRightMargin(632.5621)
layout:setTopMargin(421.2773)
layout:setBottomMargin(553.7227)
Node:addChild(imgReady)

--Create imgClockBg
local imgClockBg = cc.Sprite:create("game/joyfive_std/resource/image/clock.png")
imgClockBg:setName("imgClockBg")
imgClockBg:setTag(337)
imgClockBg:setCascadeColorEnabled(true)
imgClockBg:setCascadeOpacityEnabled(true)
imgClockBg:setPosition(1210.8830, 610.4089)
layout = ccui.LayoutComponent:bindLayoutComponent(imgClockBg)
layout:setPositionPercentX(0.6307)
layout:setPositionPercentY(0.5652)
layout:setSize(cc.size(110.0000, 131.0000))
layout:setLeftMargin(1155.8830)
layout:setRightMargin(654.1168)
layout:setTopMargin(404.0911)
layout:setBottomMargin(544.9089)
Node:addChild(imgClockBg)

--Create fntClock
local fntClock = ccui.TextAtlas:create([[60]],
													"game/joyfive_std/resource/number/clocksz.png",
													25,
													40,
													"0")
fntClock:setLayoutComponentEnabled(true)
fntClock:setName("fntClock")
fntClock:setTag(338)
fntClock:setCascadeColorEnabled(true)
fntClock:setCascadeOpacityEnabled(true)
fntClock:setPosition(1211.8470, 612.9900)
layout = ccui.LayoutComponent:bindLayoutComponent(fntClock)
layout:setPositionPercentX(0.6312)
layout:setPositionPercentY(0.5676)
layout:setPercentWidth(0.0875)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(50.0000, 40.0000))
layout:setLeftMargin(1186.8470)
layout:setRightMargin(683.1528)
layout:setTopMargin(447.0100)
layout:setBottomMargin(592.9900)
Node:addChild(fntClock)

--Create ndEffect
local ndEffect=cc.Node:create()
ndEffect:setName("ndEffect")
ndEffect:setTag(573)
ndEffect:setCascadeColorEnabled(true)
ndEffect:setCascadeOpacityEnabled(true)
ndEffect:setPosition(1224.9020, 492.2505)
layout = ccui.LayoutComponent:bindLayoutComponent(ndEffect)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(1224.9020)
layout:setRightMargin(-1224.9020)
layout:setTopMargin(-492.2505)
layout:setBottomMargin(492.2505)
Node:addChild(ndEffect)

--Create checkCardCon
local checkCardCon=cc.Node:create()
checkCardCon:setName("checkCardCon")
checkCardCon:setTag(625)
checkCardCon:setCascadeColorEnabled(true)
checkCardCon:setCascadeOpacityEnabled(true)
checkCardCon:setPosition(1620.9910, 700.0071)
layout = ccui.LayoutComponent:bindLayoutComponent(checkCardCon)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(1620.9910)
layout:setRightMargin(-1620.9910)
layout:setTopMargin(-700.0071)
layout:setBottomMargin(700.0071)
Node:addChild(checkCardCon)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

