--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------


-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgPlayerBg
local imgPlayerBg = cc.Sprite:create("game/joyfive_std/resource/image/xxbj.png")
imgPlayerBg:setName("imgPlayerBg")
imgPlayerBg:setTag(256)
imgPlayerBg:setCascadeColorEnabled(true)
imgPlayerBg:setCascadeOpacityEnabled(true)
imgPlayerBg:setPosition(178.9170, 621.4886)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayerBg)
layout:setPositionPercentX(0.0932)
layout:setPositionPercentY(0.5755)
layout:setSize(cc.size(346.0000, 172.0000))
layout:setLeftMargin(5.9170)
layout:setRightMargin(1568.0830)
layout:setTopMargin(372.5114)
layout:setBottomMargin(535.4886)
Node:addChild(imgPlayerBg)

--Create imgHead
local imgHead = cc.Sprite:create("game/joyfive_std/resource/head/1.png")
imgHead:setName("imgHead")
imgHead:setTag(257)
imgHead:setCascadeColorEnabled(true)
imgHead:setCascadeOpacityEnabled(true)
imgHead:setPosition(89.4997, 622.7281)
layout = ccui.LayoutComponent:bindLayoutComponent(imgHead)
layout:setPositionPercentX(0.0466)
layout:setPositionPercentY(0.5766)
layout:setSize(cc.size(115.0000, 115.0000))
layout:setLeftMargin(31.9997)
layout:setRightMargin(1773.0000)
layout:setTopMargin(399.7719)
layout:setBottomMargin(565.2281)
Node:addChild(imgHead)

--Create labName
local labName = ccui.Text:create()
labName:ignoreContentAdaptWithSize(true)
labName:setTextAreaSize(cc.size(0, 0))
labName:setFontSize(16)
labName:setString([[让往事随风随风随风]])
labName:setLayoutComponentEnabled(true)
labName:setName("labName")
labName:setTag(258)
labName:setCascadeColorEnabled(true)
labName:setCascadeOpacityEnabled(true)
labName:setPosition(233.7134, 662.0536)
labName:setColor(cc.c3b(157, 149, 160))
layout = ccui.LayoutComponent:bindLayoutComponent(labName)
layout:setPositionPercentX(0.1217)
layout:setPositionPercentY(0.6130)
layout:setPercentWidth(0.0521)
layout:setPercentHeight(0.0213)
layout:setSize(cc.size(144.0000, 16.0000))
layout:setLeftMargin(161.7134)
layout:setRightMargin(1614.2870)
layout:setTopMargin(409.9464)
layout:setBottomMargin(654.0536)
Node:addChild(labName)

--Create fntChips
local fntChips = ccui.TextAtlas:create([[012345678]],
													"game/joyfive_std/resource/number/number1.png",
													12,
													20,
													"0")
fntChips:setLayoutComponentEnabled(true)
fntChips:setName("fntChips")
fntChips:setTag(259)
fntChips:setCascadeColorEnabled(true)
fntChips:setCascadeOpacityEnabled(true)
fntChips:setAnchorPoint(0.0000, 0.5000)
fntChips:setPosition(198.2167, 596.3820)
layout = ccui.LayoutComponent:bindLayoutComponent(fntChips)
layout:setPositionPercentX(0.1032)
layout:setPositionPercentY(0.5522)
layout:setPercentWidth(0.0661)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(108.0000, 20.0000))
layout:setLeftMargin(198.2167)
layout:setRightMargin(1613.7830)
layout:setTopMargin(473.6180)
layout:setBottomMargin(586.3820)
Node:addChild(fntChips)

--Create imCardBg
local imCardBg = cc.Sprite:create("game/joyfive_std/resource/image/pbg.png")
imCardBg:setName("imCardBg")
imCardBg:setTag(260)
imCardBg:setCascadeColorEnabled(true)
imCardBg:setCascadeOpacityEnabled(true)
imCardBg:setPosition(187.7575, 460.6159)
layout = ccui.LayoutComponent:bindLayoutComponent(imCardBg)
layout:setPositionPercentX(0.0978)
layout:setPositionPercentY(0.4265)
layout:setSize(cc.size(290.0000, 152.0000))
layout:setLeftMargin(42.7575)
layout:setRightMargin(1587.2420)
layout:setTopMargin(543.3840)
layout:setBottomMargin(384.6159)
Node:addChild(imCardBg)

--Create imgCard1
local imgCard1 = ccui.ImageView:create()
imgCard1:ignoreContentAdaptWithSize(false)
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
imgCard1:loadTexture("BM.png",1)
imgCard1:setLayoutComponentEnabled(true)
imgCard1:setName("imgCard1")
imgCard1:setTag(353)
imgCard1:setCascadeColorEnabled(true)
imgCard1:setCascadeOpacityEnabled(true)
imgCard1:setPosition(103.3900, 456.8900)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard1)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(57.3900)
layout:setRightMargin(-149.3900)
layout:setTopMargin(-517.8900)
layout:setBottomMargin(395.8900)
Node:addChild(imgCard1)

--Create imgCard2
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard2 = cc.Sprite:createWithSpriteFrameName("FK_1.png")
imgCard2:setName("imgCard2")
imgCard2:setTag(262)
imgCard2:setCascadeColorEnabled(true)
imgCard2:setCascadeOpacityEnabled(true)
imgCard2:setPosition(148.6953, 456.8603)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard2)
layout:setPositionPercentX(0.0774)
layout:setPositionPercentY(0.4230)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(102.6953)
layout:setRightMargin(1725.3050)
layout:setTopMargin(562.1398)
layout:setBottomMargin(395.8603)
Node:addChild(imgCard2)

--Create imgCard3
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard3 = cc.Sprite:createWithSpriteFrameName("FK_3.png")
imgCard3:setName("imgCard3")
imgCard3:setTag(263)
imgCard3:setCascadeColorEnabled(true)
imgCard3:setCascadeOpacityEnabled(true)
imgCard3:setPosition(188.3754, 456.8603)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard3)
layout:setPositionPercentX(0.0981)
layout:setPositionPercentY(0.4230)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(142.3754)
layout:setRightMargin(1685.6250)
layout:setTopMargin(562.1398)
layout:setBottomMargin(395.8603)
Node:addChild(imgCard3)

--Create imgCard4
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard4 = cc.Sprite:createWithSpriteFrameName("FK_4.png")
imgCard4:setName("imgCard4")
imgCard4:setTag(264)
imgCard4:setCascadeColorEnabled(true)
imgCard4:setCascadeOpacityEnabled(true)
imgCard4:setPosition(228.0481, 456.8603)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard4)
layout:setPositionPercentX(0.1188)
layout:setPositionPercentY(0.4230)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(182.0481)
layout:setRightMargin(1645.9520)
layout:setTopMargin(562.1398)
layout:setBottomMargin(395.8603)
Node:addChild(imgCard4)

--Create imgCard5
cc.SpriteFrameCache:getInstance():addSpriteFrames("game/joyfive_std/resource/effect/dapuke.plist")
local imgCard5 = cc.Sprite:createWithSpriteFrameName("FK_5.png")
imgCard5:setName("imgCard5")
imgCard5:setTag(265)
imgCard5:setCascadeColorEnabled(true)
imgCard5:setCascadeOpacityEnabled(true)
imgCard5:setPosition(270.8569, 456.8603)
layout = ccui.LayoutComponent:bindLayoutComponent(imgCard5)
layout:setPositionPercentX(0.1411)
layout:setPositionPercentY(0.4230)
layout:setSize(cc.size(92.0000, 122.0000))
layout:setLeftMargin(224.8569)
layout:setRightMargin(1603.1430)
layout:setTopMargin(562.1398)
layout:setBottomMargin(395.8603)
Node:addChild(imgCard5)

--Create imgSettleAccountsWin
local imgSettleAccountsWin = cc.Sprite:create("game/joyfive_std/resource/image/jsbg.png")
imgSettleAccountsWin:setName("imgSettleAccountsWin")
imgSettleAccountsWin:setTag(266)
imgSettleAccountsWin:setCascadeColorEnabled(true)
imgSettleAccountsWin:setCascadeOpacityEnabled(true)
imgSettleAccountsWin:setPosition(658.5331, 597.8651)
layout = ccui.LayoutComponent:bindLayoutComponent(imgSettleAccountsWin)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(279.0000, 90.0000))
layout:setLeftMargin(519.0331)
layout:setRightMargin(-798.0331)
layout:setTopMargin(-642.8651)
layout:setBottomMargin(552.8651)
Node:addChild(imgSettleAccountsWin)

--Create fntSettleAccountsWin
local fntSettleAccountsWin = ccui.TextBMFont:create()
fntSettleAccountsWin:setFntFile("game/joyfive_std/resource/number/joyfivechips.fnt")
fntSettleAccountsWin:setString([[+0123456789]])
fntSettleAccountsWin:setLayoutComponentEnabled(true)
fntSettleAccountsWin:setName("fntSettleAccountsWin")
fntSettleAccountsWin:setTag(267)
fntSettleAccountsWin:setCascadeColorEnabled(true)
fntSettleAccountsWin:setCascadeOpacityEnabled(true)
fntSettleAccountsWin:setPosition(657.0084, 607.6096)
layout = ccui.LayoutComponent:bindLayoutComponent(fntSettleAccountsWin)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(0.0224)
layout:setPercentHeight(0.0269)
layout:setSize(cc.size(224.0000, 29.0000))
layout:setLeftMargin(545.0084)
layout:setRightMargin(-769.0084)
layout:setTopMargin(-622.1096)
layout:setBottomMargin(593.1096)
Node:addChild(fntSettleAccountsWin)

--Create imgSettleAccountsLose
local imgSettleAccountsLose = cc.Sprite:create("game/joyfive_std/resource/image/jsbg1.png")
imgSettleAccountsLose:setName("imgSettleAccountsLose")
imgSettleAccountsLose:setTag(612)
imgSettleAccountsLose:setCascadeColorEnabled(true)
imgSettleAccountsLose:setCascadeOpacityEnabled(true)
imgSettleAccountsLose:setPosition(658.7142, 597.4325)
layout = ccui.LayoutComponent:bindLayoutComponent(imgSettleAccountsLose)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(279.0000, 90.0000))
layout:setLeftMargin(519.2142)
layout:setRightMargin(-798.2142)
layout:setTopMargin(-642.4325)
layout:setBottomMargin(552.4325)
Node:addChild(imgSettleAccountsLose)

--Create fntSettleAccountsLose
local fntSettleAccountsLose = ccui.TextBMFont:create()
fntSettleAccountsLose:setFntFile("game/joyfive_std/resource/number/lose.fnt")
fntSettleAccountsLose:setString([[-0123456789]])
fntSettleAccountsLose:setLayoutComponentEnabled(true)
fntSettleAccountsLose:setName("fntSettleAccountsLose")
fntSettleAccountsLose:setTag(613)
fntSettleAccountsLose:setCascadeColorEnabled(true)
fntSettleAccountsLose:setCascadeOpacityEnabled(true)
fntSettleAccountsLose:setPosition(657.1836, 607.1729)
layout = ccui.LayoutComponent:bindLayoutComponent(fntSettleAccountsLose)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(223.0000, 29.0000))
layout:setLeftMargin(545.6836)
layout:setRightMargin(-768.6836)
layout:setTopMargin(-621.6729)
layout:setBottomMargin(592.6729)
Node:addChild(fntSettleAccountsLose)

--Create spBetType
local spBetType = cc.Sprite:create("game/joyfive_std/resource/word/gz.png")
spBetType:setName("spBetType")
spBetType:setTag(268)
spBetType:setCascadeColorEnabled(true)
spBetType:setCascadeOpacityEnabled(true)
spBetType:setPosition(434.5898, 625.8235)
layout = ccui.LayoutComponent:bindLayoutComponent(spBetType)
layout:setPositionPercentX(0.2263)
layout:setPositionPercentY(0.5795)
layout:setSize(cc.size(78.0000, 26.0000))
layout:setLeftMargin(395.5898)
layout:setRightMargin(1446.4100)
layout:setTopMargin(441.1765)
layout:setBottomMargin(612.8235)
Node:addChild(spBetType)

--Create imgReady
local imgReady = cc.Sprite:create("game/joyfive_std/resource/word/zb.png")
imgReady:setName("imgReady")
imgReady:setTag(269)
imgReady:setCascadeColorEnabled(true)
imgReady:setCascadeOpacityEnabled(true)
imgReady:setPosition(430.0597, 618.7001)
layout = ccui.LayoutComponent:bindLayoutComponent(imgReady)
layout:setPositionPercentX(0.2240)
layout:setPositionPercentY(0.5729)
layout:setSize(cc.size(162.0000, 105.0000))
layout:setLeftMargin(349.0597)
layout:setRightMargin(1408.9400)
layout:setTopMargin(408.7999)
layout:setBottomMargin(566.2001)
Node:addChild(imgReady)

--Create imgClockBg
local imgClockBg = cc.Sprite:create("game/joyfive_std/resource/image/clock.png")
imgClockBg:setName("imgClockBg")
imgClockBg:setTag(270)
imgClockBg:setCascadeColorEnabled(true)
imgClockBg:setCascadeOpacityEnabled(true)
imgClockBg:setPosition(434.5010, 622.8833)
layout = ccui.LayoutComponent:bindLayoutComponent(imgClockBg)
layout:setPositionPercentX(0.2263)
layout:setPositionPercentY(0.5767)
layout:setSize(cc.size(110.0000, 131.0000))
layout:setLeftMargin(379.5010)
layout:setRightMargin(1430.4990)
layout:setTopMargin(391.6167)
layout:setBottomMargin(557.3833)
Node:addChild(imgClockBg)

--Create fntClock
local fntClock = ccui.TextAtlas:create([[60]],
													"game/joyfive_std/resource/number/clocksz.png",
													25,
													40,
													"0")
fntClock:setLayoutComponentEnabled(true)
fntClock:setName("fntClock")
fntClock:setTag(271)
fntClock:setCascadeColorEnabled(true)
fntClock:setCascadeOpacityEnabled(true)
fntClock:setPosition(435.4740, 625.4680)
layout = ccui.LayoutComponent:bindLayoutComponent(fntClock)
layout:setPositionPercentX(0.2268)
layout:setPositionPercentY(0.5791)
layout:setPercentWidth(0.0875)
layout:setPercentHeight(0.0167)
layout:setSize(cc.size(50.0000, 40.0000))
layout:setLeftMargin(410.4740)
layout:setRightMargin(1459.5260)
layout:setTopMargin(434.5320)
layout:setBottomMargin(605.4680)
Node:addChild(fntClock)

--Create ndEffect
local ndEffect=cc.Node:create()
ndEffect:setName("ndEffect")
ndEffect:setTag(272)
ndEffect:setCascadeColorEnabled(true)
ndEffect:setCascadeOpacityEnabled(true)
ndEffect:setPosition(393.0036, 454.6872)
layout = ccui.LayoutComponent:bindLayoutComponent(ndEffect)
layout:setPositionPercentX(0.2047)
layout:setPositionPercentY(0.4210)
layout:setLeftMargin(393.0036)
layout:setRightMargin(1526.9960)
layout:setTopMargin(625.3128)
layout:setBottomMargin(454.6872)
Node:addChild(ndEffect)

--Create checkCardCon
local checkCardCon=cc.Node:create()
checkCardCon:setName("checkCardCon")
checkCardCon:setTag(623)
checkCardCon:setCascadeColorEnabled(true)
checkCardCon:setCascadeOpacityEnabled(true)
checkCardCon:setPosition(3.7985, 642.9074)
layout = ccui.LayoutComponent:bindLayoutComponent(checkCardCon)
layout:setPositionPercentX(0.0020)
layout:setPositionPercentY(0.5953)
layout:setLeftMargin(3.7985)
layout:setRightMargin(1916.2020)
layout:setTopMargin(437.0926)
layout:setBottomMargin(642.9074)
Node:addChild(checkCardCon)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

