--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ImgDizhuo
local ImgDizhuo = ccui.ImageView:create()
ImgDizhuo:ignoreContentAdaptWithSize(false)
ImgDizhuo:loadTexture("game/likuipiyu/resource/battery/paozuo.png",0)
ImgDizhuo:setLayoutComponentEnabled(true)
ImgDizhuo:setName("ImgDizhuo")
ImgDizhuo:setTag(39)
ImgDizhuo:setCascadeColorEnabled(true)
ImgDizhuo:setCascadeOpacityEnabled(true)
ImgDizhuo:setPosition(0.0000, 18.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ImgDizhuo)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(308.0000, 124.0000))
layout:setLeftMargin(-154.0000)
layout:setRightMargin(-154.0000)
layout:setTopMargin(-80.0000)
layout:setBottomMargin(-44.0000)
Node:addChild(ImgDizhuo)

--Create ImgJifenkuang
local ImgJifenkuang = cc.Sprite:create("game/likuipiyu/resource/battery/PaoTai.png")
ImgJifenkuang:setName("ImgJifenkuang")
ImgJifenkuang:setTag(14)
ImgJifenkuang:setCascadeColorEnabled(true)
ImgJifenkuang:setCascadeOpacityEnabled(true)
ImgJifenkuang:setAnchorPoint(0.0000, 0.5000)
ImgJifenkuang:setPosition(97.0421, -8.3084)
layout = ccui.LayoutComponent:bindLayoutComponent(ImgJifenkuang)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(329.0000, 109.0000))
layout:setLeftMargin(97.0421)
layout:setRightMargin(-426.0421)
layout:setTopMargin(-46.1916)
layout:setBottomMargin(-62.8084)
Node:addChild(ImgJifenkuang)

--Create btnDda
local btnDda = ccui.Button:create()
btnDda:ignoreContentAdaptWithSize(false)
btnDda:loadTextureNormal("game/likuipiyu/resource/battery/dda.png",0)
btnDda:setTitleFontSize(14)
btnDda:setTitleColor(cc.c3b(65, 65, 70))
btnDda:setScale9Enabled(true)
btnDda:setCapInsets(cc.rect(15,11,71,77))
btnDda:setLayoutComponentEnabled(true)
btnDda:setName("btnDda")
btnDda:setTag(9)
btnDda:setCascadeColorEnabled(true)
btnDda:setCascadeOpacityEnabled(true)
btnDda:setPosition(-125.0005, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnDda)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(101.0000, 99.0000))
layout:setLeftMargin(-175.5005)
layout:setRightMargin(74.5005)
layout:setTopMargin(-50.5000)
layout:setBottomMargin(-48.5000)
Node:addChild(btnDda)

--Create btnAdd
local btnAdd = ccui.Button:create()
btnAdd:ignoreContentAdaptWithSize(false)
btnAdd:loadTextureNormal("game/likuipiyu/resource/battery/add.png",0)
btnAdd:setTitleFontSize(14)
btnAdd:setTitleColor(cc.c3b(65, 65, 70))
btnAdd:setScale9Enabled(true)
btnAdd:setCapInsets(cc.rect(15,11,71,77))
btnAdd:setLayoutComponentEnabled(true)
btnAdd:setName("btnAdd")
btnAdd:setTag(8)
btnAdd:setCascadeColorEnabled(true)
btnAdd:setCascadeOpacityEnabled(true)
btnAdd:setPosition(125.0000, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnAdd)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(101.0000, 99.0000))
layout:setLeftMargin(74.5000)
layout:setRightMargin(-175.5000)
layout:setTopMargin(-50.5000)
layout:setBottomMargin(-48.5000)
Node:addChild(btnAdd)

--Create ImgPaoguan
local ImgPaoguan = cc.Sprite:create("game/likuipiyu/resource/battery/Bow_01.png")
ImgPaoguan:setName("ImgPaoguan")
ImgPaoguan:setTag(13)
ImgPaoguan:setCascadeColorEnabled(true)
ImgPaoguan:setCascadeOpacityEnabled(true)
ImgPaoguan:setAnchorPoint(0.1500, 0.5000)
ImgPaoguan:setPosition(-0.0001, -0.5000)
ImgPaoguan:setRotationSkewX(-90.0000)
ImgPaoguan:setRotationSkewY(-90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ImgPaoguan)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(261.0000, 192.0000))
layout:setLeftMargin(-39.1501)
layout:setRightMargin(-221.8499)
layout:setTopMargin(-95.5000)
layout:setBottomMargin(-96.5000)
Node:addChild(ImgPaoguan)

--Create ImgGaizi
local ImgGaizi = ccui.ImageView:create()
ImgGaizi:ignoreContentAdaptWithSize(false)
ImgGaizi:loadTexture("game/likuipiyu/resource/battery/paogai.png",0)
ImgGaizi:setLayoutComponentEnabled(true)
ImgGaizi:setName("ImgGaizi")
ImgGaizi:setTag(42)
ImgGaizi:setCascadeColorEnabled(true)
ImgGaizi:setCascadeOpacityEnabled(true)
ImgGaizi:setAnchorPoint(0.5000, 0.0000)
ImgGaizi:setPosition(-0.0001, -73.4993)
layout = ccui.LayoutComponent:bindLayoutComponent(ImgGaizi)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(175.0000, 88.0000))
layout:setLeftMargin(-87.5001)
layout:setRightMargin(-87.4999)
layout:setTopMargin(-14.5007)
layout:setBottomMargin(-73.4993)
Node:addChild(ImgGaizi)

--Create FntLv
--local FntLv = ccui.TextBMFont:create()
--FntLv:setFntFile("game/likuipiyu/resource/number/betall.fnt")
--FntLv:setString([[9900]])
local FntLv = ccui.TextAtlas:create([[9900]],"game/jinchanbuyu/resource/number/betall.png",100,130,"0")
FntLv:setLayoutComponentEnabled(true)
FntLv:setName("FntLv")
FntLv:setTag(43)
FntLv:setCascadeColorEnabled(true)
FntLv:setCascadeOpacityEnabled(true)
FntLv:setPosition(-0.0001, -21.0003)
FntLv:setScale(0.2000)
layout = ccui.LayoutComponent:bindLayoutComponent(FntLv)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(200.0000, 130.0000))
layout:setLeftMargin(-32.0001)
layout:setRightMargin(-31.9999)
layout:setTopMargin(10.0003)
layout:setBottomMargin(-32.0003)
Node:addChild(FntLv)

--Create FntJifen
--local FntJifen = ccui.TextBMFont:create()
--FntJifen:setFntFile("game/likuipiyu/resource/number/multiple.fnt")
--FntJifen:setString([[112121000]])
local FntJifen = ccui.TextAtlas:create([[112121000]],"game/jinchanbuyu/resource/number/multiple.png",100,130,"0")
FntJifen:setLayoutComponentEnabled(true)
FntJifen:setName("FntJifen")
FntJifen:setTag(44)
FntJifen:setCascadeColorEnabled(true)
FntJifen:setCascadeOpacityEnabled(true)
FntJifen:setAnchorPoint(0.0000, 0.5000)
FntJifen:setPosition(176.0009, 4.0000)
FntJifen:setScale(0.3000)
layout = ccui.LayoutComponent:bindLayoutComponent(FntJifen)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(200.0000, 130.0000))
layout:setLeftMargin(176.0009)
layout:setRightMargin(-415.0009)
layout:setTopMargin(-27.5000)
layout:setBottomMargin(-19.5000)
Node:addChild(FntJifen)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

