--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgBj
local imgBj = ccui.ImageView:create()
imgBj:ignoreContentAdaptWithSize(false)
imgBj:loadTexture("game/likuipiyu/resource/panel/panelPs.png",0)
imgBj:setLayoutComponentEnabled(true)
imgBj:setName("imgBj")
imgBj:setTag(86)
imgBj:setCascadeColorEnabled(true)
imgBj:setCascadeOpacityEnabled(true)
imgBj:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBj)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(891.0000, 380.0000))
layout:setLeftMargin(-445.5000)
layout:setRightMargin(-445.5000)
layout:setTopMargin(-190.0000)
layout:setBottomMargin(-190.0000)
Node:addChild(imgBj)

--Create btnClose
local btnClose = ccui.Button:create()
btnClose:ignoreContentAdaptWithSize(false)
btnClose:loadTextureNormal("lobby/resource/button/close.png",0)
btnClose:setTitleFontSize(14)
btnClose:setTitleColor(cc.c3b(65, 65, 70))
--btnClose:setScale9Enabled(true)
--btnClose:setCapInsets(cc.rect(15,11,47,50))
btnClose:setLayoutComponentEnabled(true)
btnClose:setName("btnClose")
btnClose:setTag(87)
btnClose:setCascadeColorEnabled(true)
btnClose:setCascadeOpacityEnabled(true)
btnClose:setPosition(389.9999, 60.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnClose)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(72.0000, 72.0000))
layout:setLeftMargin(351.4999)
layout:setRightMargin(-428.4999)
layout:setTopMargin(-86.0000)
layout:setBottomMargin(14.0000)
Node:addChild(btnClose)

--Create CheckBox_Hight
local CheckBox_Hight = ccui.CheckBox:create()
CheckBox_Hight:ignoreContentAdaptWithSize(false)
CheckBox_Hight:loadTextureBackGround("game/likuipiyu/resource/panel/choseBj.png",0)
CheckBox_Hight:loadTextureFrontCross("game/likuipiyu/resource/panel/btnClose.png",0)
CheckBox_Hight:setSelected(true)
CheckBox_Hight:setLayoutComponentEnabled(true)
CheckBox_Hight:setName("CheckBox_Hight")
CheckBox_Hight:setTag(88)
CheckBox_Hight:setCascadeColorEnabled(true)
CheckBox_Hight:setCascadeOpacityEnabled(true)
CheckBox_Hight:setPosition(-369.9988, -65.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_Hight)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(65.0000, 65.0000))
layout:setLeftMargin(-402.4988)
layout:setRightMargin(337.4988)
layout:setTopMargin(32.5001)
layout:setBottomMargin(-97.5001)
Node:addChild(CheckBox_Hight)

--Create imgHight
local imgHight = ccui.ImageView:create()
imgHight:ignoreContentAdaptWithSize(false)
imgHight:loadTexture("game/likuipiyu/resource/panel/PsHight.png",0)
imgHight:setLayoutComponentEnabled(true)
imgHight:setName("imgHight")
imgHight:setTag(89)
imgHight:setCascadeColorEnabled(true)
imgHight:setCascadeOpacityEnabled(true)
imgHight:setPosition(-280.0000, -70.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgHight)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(65.0000, 68.0000))
layout:setLeftMargin(-312.5000)
layout:setRightMargin(247.5000)
layout:setTopMargin(36.0000)
layout:setBottomMargin(-104.0000)
Node:addChild(imgHight)

--Create CheckBox_Middle
local CheckBox_Middle = ccui.CheckBox:create()
CheckBox_Middle:ignoreContentAdaptWithSize(false)
CheckBox_Middle:loadTextureBackGround("game/likuipiyu/resource/panel/choseBj.png",0)
CheckBox_Middle:loadTextureFrontCross("game/likuipiyu/resource/panel/btnClose.png",0)
CheckBox_Middle:setLayoutComponentEnabled(true)
CheckBox_Middle:setName("CheckBox_Middle")
CheckBox_Middle:setTag(90)
CheckBox_Middle:setCascadeColorEnabled(true)
CheckBox_Middle:setCascadeOpacityEnabled(true)
CheckBox_Middle:setPosition(-55.0000, -65.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_Middle)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(65.0000, 65.0000))
layout:setLeftMargin(-87.5000)
layout:setRightMargin(22.5000)
layout:setTopMargin(32.5000)
layout:setBottomMargin(-97.5000)
Node:addChild(CheckBox_Middle)

--Create imgMiddle
local imgMiddle = ccui.ImageView:create()
imgMiddle:ignoreContentAdaptWithSize(false)
imgMiddle:loadTexture("game/likuipiyu/resource/panel/PsMiddle.png",0)
imgMiddle:setLayoutComponentEnabled(true)
imgMiddle:setName("imgMiddle")
imgMiddle:setTag(91)
imgMiddle:setCascadeColorEnabled(true)
imgMiddle:setCascadeOpacityEnabled(true)
imgMiddle:setPosition(35.0000, -70.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(imgMiddle)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(65.0000, 68.0000))
layout:setLeftMargin(2.5000)
layout:setRightMargin(-67.5000)
layout:setTopMargin(36.0000)
layout:setBottomMargin(-104.0000)
Node:addChild(imgMiddle)

--Create CheckBox_Low
local CheckBox_Low = ccui.CheckBox:create()
CheckBox_Low:ignoreContentAdaptWithSize(false)
CheckBox_Low:loadTextureBackGround("game/likuipiyu/resource/panel/choseBj.png",0)
CheckBox_Low:loadTextureFrontCross("game/likuipiyu/resource/panel/btnClose.png",0)
CheckBox_Low:setLayoutComponentEnabled(true)
CheckBox_Low:setName("CheckBox_Low")
CheckBox_Low:setTag(92)
CheckBox_Low:setCascadeColorEnabled(true)
CheckBox_Low:setCascadeOpacityEnabled(true)
CheckBox_Low:setPosition(260.0000, -65.0011)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_Low)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(65.0000, 65.0000))
layout:setLeftMargin(227.5000)
layout:setRightMargin(-292.5000)
layout:setTopMargin(32.5011)
layout:setBottomMargin(-97.5011)
Node:addChild(CheckBox_Low)

--Create imgLow
local imgLow = ccui.ImageView:create()
imgLow:ignoreContentAdaptWithSize(false)
imgLow:loadTexture("game/likuipiyu/resource/panel/PsLow.png",0)
imgLow:setLayoutComponentEnabled(true)
imgLow:setName("imgLow")
imgLow:setTag(93)
imgLow:setCascadeColorEnabled(true)
imgLow:setCascadeOpacityEnabled(true)
imgLow:setPosition(350.0000, -65.0003)
layout = ccui.LayoutComponent:bindLayoutComponent(imgLow)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(65.0000, 68.0000))
layout:setLeftMargin(317.5000)
layout:setRightMargin(-382.5000)
layout:setTopMargin(31.0003)
layout:setBottomMargin(-99.0003)
Node:addChild(imgLow)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

