--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create CheckBox_lock
-- local CheckBox_lock = ccui.CheckBox:create()
-- CheckBox_lock:ignoreContentAdaptWithSize(false)
-- CheckBox_lock:loadTextureBackGround("game/likuipiyu/resource/panel/btnLock.png",0)
-- CheckBox_lock:loadTextureFrontCross("game/likuipiyu/resource/panel/btnUnLock.png",0)
-- CheckBox_lock:setLayoutComponentEnabled(true)
-- CheckBox_lock:setName("CheckBox_lock")
-- CheckBox_lock:setTag(23)
-- CheckBox_lock:setCascadeColorEnabled(true)
-- CheckBox_lock:setCascadeOpacityEnabled(true)
-- CheckBox_lock:setPosition(0.0000, 0.0000)
-- layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_lock)
-- layout:setPositionPercentX(0.0000)
-- layout:setPositionPercentY(0.0000)
-- layout:setSize(cc.size(182.0000, 182.0000))
-- layout:setLeftMargin(-91.0000)
-- layout:setRightMargin(-91.0000)
-- layout:setTopMargin(-91.0000)
-- layout:setBottomMargin(-91.0000)
-- Node:addChild(CheckBox_lock)

--Create CheckBox_Set
local CheckBox_auto_fire = ccui.CheckBox:create()
CheckBox_auto_fire:ignoreContentAdaptWithSize(false)
CheckBox_auto_fire:loadTextureBackGround("game/likuipiyu/resource/panel/zidongfashe.png",0)
CheckBox_auto_fire:loadTextureFrontCross("game/likuipiyu/resource/panel/qxzdfs.png",0)
CheckBox_auto_fire:setLayoutComponentEnabled(true)
CheckBox_auto_fire:setName("CheckBox_auto_fire")
CheckBox_auto_fire:setTag(15)
CheckBox_auto_fire:setCascadeColorEnabled(true)
CheckBox_auto_fire:setCascadeOpacityEnabled(true)
CheckBox_auto_fire:setAnchorPoint(1.0000, 0.5000)
CheckBox_auto_fire:setPosition(90.0000, 200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_auto_fire)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(182.0000, 182.0000))
layout:setLeftMargin(-62.0006)
layout:setRightMargin(-0.9994)
layout:setTopMargin(-67.5008)
layout:setBottomMargin(-67.4992)
Node:addChild(CheckBox_auto_fire)

--Create CheckBox_Set
local CheckBox_auto_lock = ccui.CheckBox:create()
CheckBox_auto_lock:ignoreContentAdaptWithSize(false)
CheckBox_auto_lock:loadTextureBackGround("game/likuipiyu/resource/panel/zidongsuoding.png",0)
CheckBox_auto_lock:loadTextureFrontCross("game/likuipiyu/resource/panel/qixiaosuding.png",0)
CheckBox_auto_lock:setLayoutComponentEnabled(true)
CheckBox_auto_lock:setName("CheckBox_auto_lock")
CheckBox_auto_lock:setTag(15)
CheckBox_auto_lock:setCascadeColorEnabled(true)
CheckBox_auto_lock:setCascadeOpacityEnabled(true)
CheckBox_auto_lock:setAnchorPoint(1.0000, 0.5000)
CheckBox_auto_lock:setPosition(90.0000, -200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_auto_lock)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(182.0000, 182.0000))
layout:setLeftMargin(-62.0006)
layout:setRightMargin(-0.9994)
layout:setTopMargin(-67.5008)
layout:setBottomMargin(-67.4992)
Node:addChild(CheckBox_auto_lock)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

