--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create CheckBox_Set
local CheckBox_Set = ccui.CheckBox:create()
CheckBox_Set:ignoreContentAdaptWithSize(false)
CheckBox_Set:loadTextureBackGround("game/likuipiyu/resource/panel/btnLeft.png",0)
CheckBox_Set:loadTextureFrontCross("game/likuipiyu/resource/panel/btnRight.png",0)
CheckBox_Set:setLayoutComponentEnabled(true)
CheckBox_Set:setName("CheckBox_Set")
CheckBox_Set:setTag(15)
CheckBox_Set:setCascadeColorEnabled(true)
CheckBox_Set:setCascadeOpacityEnabled(true)
CheckBox_Set:setAnchorPoint(1.0000, 0.5000)
CheckBox_Set:setPosition(0.9994, 0.0008)
layout = ccui.LayoutComponent:bindLayoutComponent(CheckBox_Set)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(63.0000, 135.0000))
layout:setLeftMargin(-62.0006)
layout:setRightMargin(-0.9994)
layout:setTopMargin(-67.5008)
layout:setBottomMargin(-67.4992)
Node:addChild(CheckBox_Set)

--Create ImgPanelBj
local ImgPanelBj = ccui.ImageView:create()
ImgPanelBj:ignoreContentAdaptWithSize(false)
ImgPanelBj:loadTexture("game/likuipiyu/resource/panel/panel.png",0)
ImgPanelBj:setLayoutComponentEnabled(true)
ImgPanelBj:setName("ImgPanelBj")
ImgPanelBj:setTag(16)
ImgPanelBj:setCascadeColorEnabled(true)
ImgPanelBj:setCascadeOpacityEnabled(true)
ImgPanelBj:setPosition(89.9999, 0.0007)
layout = ccui.LayoutComponent:bindLayoutComponent(ImgPanelBj)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(178.0000, 675.0000))
layout:setLeftMargin(0.9999)
layout:setRightMargin(-178.9999)
layout:setTopMargin(-337.5007)
layout:setBottomMargin(-337.4993)
Node:addChild(ImgPanelBj)

--Create btnSet
local btnSet = ccui.Button:create()
btnSet:ignoreContentAdaptWithSize(false)
btnSet:loadTextureNormal("game/likuipiyu/resource/panel/btnSetup.png",0)
btnSet:setTitleFontSize(14)
btnSet:setTitleColor(cc.c3b(65, 65, 70))
btnSet:setScale9Enabled(true)
btnSet:setCapInsets(cc.rect(15,11,128,136))
btnSet:setLayoutComponentEnabled(true)
btnSet:setName("btnSet")
btnSet:setTag(17)
btnSet:setCascadeColorEnabled(true)
btnSet:setCascadeOpacityEnabled(true)
btnSet:setPosition(89.9989, 82.3480)
layout = ccui.LayoutComponent:bindLayoutComponent(btnSet)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(158.0000, 158.0000))
layout:setLeftMargin(10.9989)
layout:setRightMargin(-168.9989)
layout:setTopMargin(-161.3480)
layout:setBottomMargin(3.3480)
Node:addChild(btnSet)

--Create btnHelp
local btnHelp = ccui.Button:create()
btnHelp:ignoreContentAdaptWithSize(false)
btnHelp:loadTextureNormal("game/likuipiyu/resource/panel/btnHelp.png",0)
btnHelp:setTitleFontSize(14)
btnHelp:setTitleColor(cc.c3b(65, 65, 70))
btnHelp:setScale9Enabled(true)
btnHelp:setCapInsets(cc.rect(15,11,128,136))
btnHelp:setLayoutComponentEnabled(true)
btnHelp:setName("btnHelp")
btnHelp:setTag(18)
btnHelp:setCascadeColorEnabled(true)
btnHelp:setCascadeOpacityEnabled(true)
btnHelp:setPosition(89.9989, -81.3264)
layout = ccui.LayoutComponent:bindLayoutComponent(btnHelp)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(158.0000, 158.0000))
layout:setLeftMargin(10.9989)
layout:setRightMargin(-168.9989)
layout:setTopMargin(2.3264)
layout:setBottomMargin(-160.3264)
Node:addChild(btnHelp)

--Create btnOut
local btnOut = ccui.Button:create()
btnOut:ignoreContentAdaptWithSize(false)
btnOut:loadTextureNormal("game/likuipiyu/resource/panel/btnOut.png",0)
btnOut:setTitleFontSize(14)
btnOut:setTitleColor(cc.c3b(65, 65, 70))
btnOut:setScale9Enabled(true)
btnOut:setCapInsets(cc.rect(15,11,128,136))
btnOut:setLayoutComponentEnabled(true)
btnOut:setName("btnOut")
btnOut:setTag(19)
btnOut:setCascadeColorEnabled(true)
btnOut:setCascadeOpacityEnabled(true)
btnOut:setPosition(89.9990, -245.0007)
layout = ccui.LayoutComponent:bindLayoutComponent(btnOut)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(158.0000, 158.0000))
layout:setLeftMargin(10.9990)
layout:setRightMargin(-168.9990)
layout:setTopMargin(166.0007)
layout:setBottomMargin(-324.0007)
Node:addChild(btnOut)

--Create btnPs
local btnPs = ccui.Button:create()
btnPs:ignoreContentAdaptWithSize(false)
btnPs:loadTextureNormal("game/likuipiyu/resource/panel/btnPs.png",0)
btnPs:setTitleFontSize(14)
btnPs:setTitleColor(cc.c3b(65, 65, 70))
btnPs:setScale9Enabled(true)
btnPs:setCapInsets(cc.rect(15,11,128,136))
btnPs:setLayoutComponentEnabled(true)
btnPs:setName("btnPs")
btnPs:setTag(83)
btnPs:setCascadeColorEnabled(true)
btnPs:setCascadeOpacityEnabled(true)
btnPs:setPosition(90.0000, 247.0223)
layout = ccui.LayoutComponent:bindLayoutComponent(btnPs)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(158.0000, 160.0000))
layout:setLeftMargin(11.0000)
layout:setRightMargin(-169.0000)
layout:setTopMargin(-327.0223)
layout:setBottomMargin(167.0223)
Node:addChild(btnPs)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

