require "game.ddz_match_std.data._init_ddz_match_std_data"
require "game.ddz_match_std.ddz_match_manager"

require "game.ddz_match_std.script.net_message.send_doudizhu"
require "game.ddz_match_std.script.net_message.rec_parse_doudizhu"
require "game.ddz_match_std.script.net_message.rec_pro_doudizhu"
require "game.ddz_match_std.script.ddzMatch_card_item"
require "game.ddz_match_std.script.ddzMatch_card_list"
require "game.ddz_match_std.script.ddzMatch_mainscene"
require "game.ddz_match_std.script.ddzMatch_room_item"
require "game.ddz_match_std.script.ddzMatch_desk"
require "game.ddz_match_std.script.ddzMatch_player"
require "game.ddz_match_std.script.ddzMatch_reward_item"
require "game.ddz_match_std.script.ddzMatch_settlement"
require "game.ddz_match_std.script.ddzMatch_ranking"
require "game.ddz_match_std.script.ddzMatch_rankingWait"
require "game.ddz_match_std.script.ddzMatch_ball"
require "game.ddz_match_std.script.ddzMatch_certificate"