--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create sprHead
local sprHead = cc.Sprite:create("common/head_pic/115/1.png")
sprHead:setName("sprHead")
sprHead:setTag(68)
sprHead:setCascadeColorEnabled(true)
sprHead:setCascadeOpacityEnabled(true)
sprHead:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprHead)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(115.0000, 115.0000))
layout:setLeftMargin(-57.5000)
layout:setRightMargin(-57.5000)
layout:setTopMargin(-57.5000)
layout:setBottomMargin(-57.5000)
Node:addChild(sprHead)

--Create sprMark
local sprMark = cc.Sprite:create("game/ddz_match_std/resource/image/nongmingtoubiao.png")
sprMark:setName("sprMark")
sprMark:setTag(69)
sprMark:setCascadeColorEnabled(true)
sprMark:setCascadeOpacityEnabled(true)
sprMark:setPosition(-28.8859, 27.8552)
layout = ccui.LayoutComponent:bindLayoutComponent(sprMark)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(60.0000, 60.0000))
layout:setLeftMargin(-58.8859)
layout:setRightMargin(-1.1141)
layout:setTopMargin(-57.8552)
layout:setBottomMargin(-2.1448)
Node:addChild(sprMark)

--Create imgClock
local imgClock = cc.Sprite:create("game/ddz_match_std/resource/image/naozhong.png")
imgClock:setName("imgClock")
imgClock:setTag(72)
imgClock:setCascadeColorEnabled(true)
imgClock:setCascadeOpacityEnabled(true)
imgClock:setPosition(-0.7679, 115.3964)
layout = ccui.LayoutComponent:bindLayoutComponent(imgClock)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(60.0000, 71.0000))
layout:setLeftMargin(-30.7679)
layout:setRightMargin(-29.2321)
layout:setTopMargin(-150.8964)
layout:setBottomMargin(79.8964)
Node:addChild(imgClock)

--Create fntTime
local fntTime = ccui.TextBMFont:create()
fntTime:setFntFile("game/ddz_match_std/resource/number/time.fnt")
fntTime:setString([[12]])
fntTime:setLayoutComponentEnabled(true)
fntTime:setName("fntTime")
fntTime:setTag(73)
fntTime:setCascadeColorEnabled(true)
fntTime:setCascadeOpacityEnabled(true)
fntTime:setPosition(30.6152, 34.7357)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTime)
layout:setPositionPercentX(0.5103)
layout:setPositionPercentY(0.4892)
layout:setSize(cc.size(28.0000, 30.0000))
layout:setLeftMargin(16.6152)
layout:setRightMargin(15.3848)
layout:setTopMargin(21.2643)
layout:setBottomMargin(19.7357)
imgClock:addChild(fntTime)

--Create BitmapFontLabel_2
local BitmapFontLabel_2 = ccui.TextBMFont:create()
BitmapFontLabel_2:setFntFile("game/ddz_match_std/resource/number/scoreF.fnt")
BitmapFontLabel_2:setString([[100]])
BitmapFontLabel_2:setLayoutComponentEnabled(true)
BitmapFontLabel_2:setName("BitmapFontLabel_2")
BitmapFontLabel_2:setTag(74)
BitmapFontLabel_2:setCascadeColorEnabled(true)
BitmapFontLabel_2:setCascadeOpacityEnabled(true)
BitmapFontLabel_2:setPosition(-0.2693, -88.8964)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_2)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(66.0000, 44.0000))
layout:setLeftMargin(-33.2694)
layout:setRightMargin(-32.7307)
layout:setTopMargin(66.8964)
layout:setBottomMargin(-110.8963)
Node:addChild(BitmapFontLabel_2)

--Create sprSurplusCard
local sprSurplusCard = cc.Sprite:create("game/ddz_match_std/resource/word/shengyu.png")
sprSurplusCard:setName("sprSurplusCard")
sprSurplusCard:setTag(75)
sprSurplusCard:setCascadeColorEnabled(true)
sprSurplusCard:setCascadeOpacityEnabled(true)
sprSurplusCard:setPosition(126.2651, -88.0242)
layout = ccui.LayoutComponent:bindLayoutComponent(sprSurplusCard)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(95.0000, 33.0000))
layout:setLeftMargin(78.7651)
layout:setRightMargin(-173.7651)
layout:setTopMargin(71.5242)
layout:setBottomMargin(-104.5242)
Node:addChild(sprSurplusCard)

--Create BitmapFontLabel_3
local BitmapFontLabel_3 = ccui.TextBMFont:create()
BitmapFontLabel_3:setFntFile("game/ddz_match_std/resource/number/surplusPuke.fnt")
BitmapFontLabel_3:setString([[22]])
BitmapFontLabel_3:setLayoutComponentEnabled(true)
BitmapFontLabel_3:setName("BitmapFontLabel_3")
BitmapFontLabel_3:setTag(76)
BitmapFontLabel_3:setCascadeColorEnabled(true)
BitmapFontLabel_3:setCascadeOpacityEnabled(true)
BitmapFontLabel_3:setPosition(48.6090, 18.4229)
layout = ccui.LayoutComponent:bindLayoutComponent(BitmapFontLabel_3)
layout:setPositionPercentX(0.5117)
layout:setPositionPercentY(0.5583)
layout:setSize(cc.size(36.0000, 30.0000))
layout:setLeftMargin(30.6090)
layout:setRightMargin(28.3910)
layout:setTopMargin(-0.4229)
layout:setBottomMargin(3.4229)
sprSurplusCard:addChild(BitmapFontLabel_3)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

