--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgPVP
local imgPVP = cc.Sprite:create("game/ddz_match_std/resource/image/matchOne.png")
imgPVP:setName("imgPVP")
imgPVP:setTag(13)
imgPVP:setCascadeColorEnabled(true)
imgPVP:setCascadeOpacityEnabled(true)
imgPVP:setPosition(91.2411, 116.1491)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPVP)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(182.0000, 113.0000))
layout:setLeftMargin(0.2411)
layout:setRightMargin(-182.2411)
layout:setTopMargin(-172.6491)
layout:setBottomMargin(59.6491)
Node:addChild(imgPVP)

--Create btnEnter
local btnEnter = ccui.Button:create()
btnEnter:ignoreContentAdaptWithSize(false)
btnEnter:loadTextureNormal("game/ddz_match_std/resource/button/k1.png",0)
btnEnter:loadTexturePressed("game/ddz_match_std/resource/button/k3.png",0)
btnEnter:setTitleFontSize(14)
btnEnter:setTitleColor(cc.c3b(65, 65, 70))
btnEnter:setScale9Enabled(true)
btnEnter:setCapInsets(cc.rect(15,11,162,153))
btnEnter:setLayoutComponentEnabled(true)
btnEnter:setName("btnEnter")
btnEnter:setTag(12)
btnEnter:setCascadeColorEnabled(true)
btnEnter:setCascadeOpacityEnabled(true)
btnEnter:setAnchorPoint(0.0000, 0.0000)
btnEnter:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnEnter)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(192.0000, 175.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(-192.0000)
layout:setTopMargin(-175.0000)
layout:setBottomMargin(0.0000)
Node:addChild(btnEnter)

--Create imgWord
local imgWord = cc.Sprite:create("game/ddz_match_std/resource/word/biaoti.png")
imgWord:setName("imgWord")
imgWord:setTag(14)
imgWord:setCascadeColorEnabled(true)
imgWord:setCascadeOpacityEnabled(true)
imgWord:setPosition(97.2408, 61.1478)
layout = ccui.LayoutComponent:bindLayoutComponent(imgWord)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(147.0000, 18.0000))
layout:setLeftMargin(23.7408)
layout:setRightMargin(-170.7408)
layout:setTopMargin(-70.1478)
layout:setBottomMargin(52.1478)
Node:addChild(imgWord)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

