--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create sprBack
local sprBack = cc.Sprite:create("game/ddz_match_std/resource/image/bj.png")
sprBack:setName("sprBack")
sprBack:setTag(16)
sprBack:setCascadeColorEnabled(true)
sprBack:setCascadeOpacityEnabled(true)
sprBack:setPosition(421.0011, 299.0010)
layout = ccui.LayoutComponent:bindLayoutComponent(sprBack)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(832.0000, 590.0000))
layout:setLeftMargin(5.0011)
layout:setRightMargin(-837.0011)
layout:setTopMargin(-594.0010)
layout:setBottomMargin(4.0010)
Node:addChild(sprBack)

--Create labBeginNum
local labBeginNum = ccui.Text:create()
labBeginNum:ignoreContentAdaptWithSize(true)
labBeginNum:setTextAreaSize(cc.size(0, 0))
labBeginNum:setFontName("lobby/resource/font/simhei.ttf")
labBeginNum:setFontSize(20)
labBeginNum:setString([[满100人开赛]])
labBeginNum:setLayoutComponentEnabled(true)
labBeginNum:setName("labBeginNum")
labBeginNum:setTag(23)
labBeginNum:setCascadeColorEnabled(true)
labBeginNum:setCascadeOpacityEnabled(true)
labBeginNum:setAnchorPoint(0.0000, 0.5000)
labBeginNum:setPosition(312.4672, 552.5329)
layout = ccui.LayoutComponent:bindLayoutComponent(labBeginNum)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(110.0000, 23.0000))
layout:setLeftMargin(312.4672)
layout:setRightMargin(-422.4672)
layout:setTopMargin(-564.0329)
layout:setBottomMargin(541.0329)
Node:addChild(labBeginNum)

--Create labWaitTime
local labWaitTime = ccui.Text:create()
labWaitTime:ignoreContentAdaptWithSize(true)
labWaitTime:setTextAreaSize(cc.size(0, 0))
labWaitTime:setFontName("lobby/resource/font/simhei.ttf")
labWaitTime:setFontSize(20)
labWaitTime:setString([[预计等待时间100秒]])
labWaitTime:setLayoutComponentEnabled(true)
labWaitTime:setName("labWaitTime")
labWaitTime:setTag(25)
labWaitTime:setCascadeColorEnabled(true)
labWaitTime:setCascadeOpacityEnabled(true)
labWaitTime:setAnchorPoint(0.0000, 0.5000)
labWaitTime:setPosition(443.1605, 552.5329)
layout = ccui.LayoutComponent:bindLayoutComponent(labWaitTime)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(170.0000, 23.0000))
layout:setLeftMargin(443.1605)
layout:setRightMargin(-613.1605)
layout:setTopMargin(-564.0329)
layout:setBottomMargin(541.0329)
Node:addChild(labWaitTime)

--Create labBeginTime
local labBeginTime = ccui.Text:create()
labBeginTime:ignoreContentAdaptWithSize(true)
labBeginTime:setTextAreaSize(cc.size(0, 0))
labBeginTime:setFontName("lobby/resource/font/simhei.ttf")
labBeginTime:setFontSize(20)
labBeginTime:setString([[离开赛还有100]])
labBeginTime:setLayoutComponentEnabled(true)
labBeginTime:setName("labBeginTime")
labBeginTime:setTag(24)
labBeginTime:setCascadeColorEnabled(true)
labBeginTime:setCascadeOpacityEnabled(true)
labBeginTime:setAnchorPoint(0.0000, 0.5000)
labBeginTime:setPosition(626.3580, 552.5329)
layout = ccui.LayoutComponent:bindLayoutComponent(labBeginTime)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(130.0000, 23.0000))
layout:setLeftMargin(626.3580)
layout:setRightMargin(-756.3580)
layout:setTopMargin(-564.0329)
layout:setBottomMargin(541.0329)
Node:addChild(labBeginTime)

--Create sprLoading
local sprLoading = cc.Sprite:create("game/ddz_match_std/resource/image/sjc1.png")
sprLoading:setName("sprLoading")
sprLoading:setTag(19)
sprLoading:setCascadeColorEnabled(true)
sprLoading:setCascadeOpacityEnabled(true)
sprLoading:setPosition(518.2480, 514.6439)
layout = ccui.LayoutComponent:bindLayoutComponent(sprLoading)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(333.0000, 21.0000))
layout:setLeftMargin(351.7480)
layout:setRightMargin(-684.7480)
layout:setTopMargin(-525.1439)
layout:setBottomMargin(504.1439)
Node:addChild(sprLoading)

--Create loadingBar
local loadingBar = ccui.LoadingBar:create()
loadingBar:loadTexture("game/ddz_match_std/resource/image/sjc.png",0)
loadingBar:ignoreContentAdaptWithSize(false)
loadingBar:setPercent(52)
loadingBar:setLayoutComponentEnabled(true)
loadingBar:setName("loadingBar")
loadingBar:setTag(18)
loadingBar:setCascadeColorEnabled(true)
loadingBar:setCascadeOpacityEnabled(true)
loadingBar:setPosition(167.0000, 11.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(loadingBar)
layout:setPositionPercentX(0.5015)
layout:setPositionPercentY(0.5238)
layout:setSize(cc.size(333.0000, 21.0000))
layout:setLeftMargin(0.5000)
layout:setRightMargin(-0.5000)
layout:setTopMargin(-0.5000)
layout:setBottomMargin(0.5000)
sprLoading:addChild(loadingBar)

--Create sprMatchTitle
local sprMatchTitle = cc.Sprite:create("game/ddz_match_std/resource/word/jss.png")
sprMatchTitle:setName("sprMatchTitle")
sprMatchTitle:setTag(28)
sprMatchTitle:setCascadeColorEnabled(true)
sprMatchTitle:setCascadeOpacityEnabled(true)
sprMatchTitle:setPosition(190.5554, 542.3762)
layout = ccui.LayoutComponent:bindLayoutComponent(sprMatchTitle)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(210.0000, 83.0000))
layout:setLeftMargin(85.5554)
layout:setRightMargin(-295.5554)
layout:setTopMargin(-583.8762)
layout:setBottomMargin(500.8762)
Node:addChild(sprMatchTitle)

--Create btnApply
local btnApply = ccui.Button:create()
btnApply:ignoreContentAdaptWithSize(false)
btnApply:loadTextureNormal("game/ddz_match_std/resource/button/baoming1.png",0)
btnApply:loadTexturePressed("game/ddz_match_std/resource/button/baoming1.png",0)
btnApply:setTitleFontSize(14)
btnApply:setTitleColor(cc.c3b(65, 65, 70))
btnApply:setScale9Enabled(true)
btnApply:setCapInsets(cc.rect(15,11,163,71))
btnApply:setLayoutComponentEnabled(true)
btnApply:setName("btnApply")
btnApply:setTag(30)
btnApply:setCascadeColorEnabled(true)
btnApply:setCascadeOpacityEnabled(true)
btnApply:setPosition(629.0228, 69.1457)
layout = ccui.LayoutComponent:bindLayoutComponent(btnApply)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(193.0000, 93.0000))
layout:setLeftMargin(532.5228)
layout:setRightMargin(-725.5228)
layout:setTopMargin(-115.6457)
layout:setBottomMargin(22.6457)
Node:addChild(btnApply)

--Create btnCancel
local btnCancel = ccui.Button:create()
btnCancel:ignoreContentAdaptWithSize(false)
btnCancel:loadTextureNormal("game/ddz_match_std/resource/button/quxiaobaoming1.png",0)
btnCancel:loadTexturePressed("game/ddz_match_std/resource/button/quxiaobaoming1.png",0)
btnCancel:setTitleFontSize(14)
btnCancel:setTitleColor(cc.c3b(65, 65, 70))
btnCancel:setScale9Enabled(true)
btnCancel:setCapInsets(cc.rect(15,11,163,71))
btnCancel:setLayoutComponentEnabled(true)
btnCancel:setName("btnCancel")
btnCancel:setTag(31)
btnCancel:setCascadeColorEnabled(true)
btnCancel:setCascadeOpacityEnabled(true)
btnCancel:setPosition(629.0204, 73.1500)
layout = ccui.LayoutComponent:bindLayoutComponent(btnCancel)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(193.0000, 93.0000))
layout:setLeftMargin(532.5204)
layout:setRightMargin(-725.5204)
layout:setTopMargin(-119.6500)
layout:setBottomMargin(26.6500)
Node:addChild(btnCancel)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

