--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgPlayerHead
local imgPlayerHead = cc.Sprite:create("common/head_pic/223/1.png")
imgPlayerHead:setName("imgPlayerHead")
imgPlayerHead:setTag(424)
imgPlayerHead:setCascadeColorEnabled(true)
imgPlayerHead:setCascadeOpacityEnabled(true)
imgPlayerHead:setPosition(341.0000, 753.0000)
imgPlayerHead:setScaleX(0.8500)
imgPlayerHead:setScaleY(0.8500)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayerHead)
layout:setPositionPercentX(0.1776)
layout:setPositionPercentY(0.6972)
layout:setSize(cc.size(223.0000, 235.0000))
layout:setLeftMargin(229.5000)
layout:setRightMargin(1467.5000)
layout:setTopMargin(209.5000)
layout:setBottomMargin(635.5000)
Node:addChild(imgPlayerHead)

--Create imgBankerNiCheng
local imgBankerNiCheng = ccui.Text:create()
imgBankerNiCheng:ignoreContentAdaptWithSize(true)
imgBankerNiCheng:setTextAreaSize(cc.size(0, 0))
imgBankerNiCheng:setFontName("simhei.ttf")
imgBankerNiCheng:setFontSize(40)
imgBankerNiCheng:setString([[昵称:]])
imgBankerNiCheng:setLayoutComponentEnabled(true)
imgBankerNiCheng:setName("imgBankerNiCheng")
imgBankerNiCheng:setTag(425)
imgBankerNiCheng:setCascadeColorEnabled(true)
imgBankerNiCheng:setCascadeOpacityEnabled(true)
imgBankerNiCheng:setAnchorPoint(0.0000, 0.5000)
imgBankerNiCheng:setPosition(448.0000, 837.0002)
imgBankerNiCheng:setColor(cc.c3b(191, 191, 191))
layout = ccui.LayoutComponent:bindLayoutComponent(imgBankerNiCheng)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.7750)
layout:setPercentWidth(0.0521)
layout:setPercentHeight(0.0426)
layout:setSize(cc.size(100.0000, 46.0000))
layout:setLeftMargin(448.0000)
layout:setRightMargin(1372.0000)
layout:setTopMargin(219.9998)
layout:setBottomMargin(814.0002)
Node:addChild(imgBankerNiCheng)

--Create imgBankerChips
local imgBankerChips = ccui.Text:create()
imgBankerChips:ignoreContentAdaptWithSize(true)
imgBankerChips:setTextAreaSize(cc.size(0, 0))
imgBankerChips:setFontName("simhei.ttf")
imgBankerChips:setFontSize(40)
imgBankerChips:setString([[筹码:]])
imgBankerChips:setLayoutComponentEnabled(true)
imgBankerChips:setName("imgBankerChips")
imgBankerChips:setTag(426)
imgBankerChips:setCascadeColorEnabled(true)
imgBankerChips:setCascadeOpacityEnabled(true)
imgBankerChips:setAnchorPoint(0.0000, 0.5000)
imgBankerChips:setPosition(448.0000, 782.9990)
imgBankerChips:setColor(cc.c3b(191, 191, 191))
layout = ccui.LayoutComponent:bindLayoutComponent(imgBankerChips)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.7250)
layout:setPercentWidth(0.0521)
layout:setPercentHeight(0.0426)
layout:setSize(cc.size(100.0000, 46.0000))
layout:setLeftMargin(448.0000)
layout:setRightMargin(1372.0000)
layout:setTopMargin(274.0010)
layout:setBottomMargin(759.9990)
Node:addChild(imgBankerChips)

--Create imgBankerJuShu
local imgBankerJuShu = ccui.Text:create()
imgBankerJuShu:ignoreContentAdaptWithSize(true)
imgBankerJuShu:setTextAreaSize(cc.size(0, 0))
imgBankerJuShu:setFontName("simhei.ttf")
imgBankerJuShu:setFontSize(40)
imgBankerJuShu:setString([[局数:]])
imgBankerJuShu:setLayoutComponentEnabled(true)
imgBankerJuShu:setName("imgBankerJuShu")
imgBankerJuShu:setTag(427)
imgBankerJuShu:setCascadeColorEnabled(true)
imgBankerJuShu:setCascadeOpacityEnabled(true)
imgBankerJuShu:setAnchorPoint(0.0000, 0.5000)
imgBankerJuShu:setPosition(448.0000, 727.0000)
imgBankerJuShu:setColor(cc.c3b(191, 191, 191))
layout = ccui.LayoutComponent:bindLayoutComponent(imgBankerJuShu)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.6731)
layout:setPercentWidth(0.0521)
layout:setPercentHeight(0.0426)
layout:setSize(cc.size(100.0000, 46.0000))
layout:setLeftMargin(448.0000)
layout:setRightMargin(1372.0000)
layout:setTopMargin(330.0000)
layout:setBottomMargin(704.0000)
Node:addChild(imgBankerJuShu)

--Create imgBankerChengJi
local imgBankerChengJi = ccui.Text:create()
imgBankerChengJi:ignoreContentAdaptWithSize(true)
imgBankerChengJi:setTextAreaSize(cc.size(0, 0))
imgBankerChengJi:setFontName("simhei.ttf")
imgBankerChengJi:setFontSize(40)
imgBankerChengJi:setString([[成绩:]])
imgBankerChengJi:setLayoutComponentEnabled(true)
imgBankerChengJi:setName("imgBankerChengJi")
imgBankerChengJi:setTag(428)
imgBankerChengJi:setCascadeColorEnabled(true)
imgBankerChengJi:setCascadeOpacityEnabled(true)
imgBankerChengJi:setAnchorPoint(0.0000, 0.5000)
imgBankerChengJi:setPosition(448.0002, 672.0001)
imgBankerChengJi:setColor(cc.c3b(191, 191, 191))
layout = ccui.LayoutComponent:bindLayoutComponent(imgBankerChengJi)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.6222)
layout:setPercentWidth(0.0521)
layout:setPercentHeight(0.0426)
layout:setSize(cc.size(100.0000, 46.0000))
layout:setLeftMargin(448.0002)
layout:setRightMargin(1372.0000)
layout:setTopMargin(384.9999)
layout:setBottomMargin(649.0001)
Node:addChild(imgBankerChengJi)

--Create labNiCheng
local labNiCheng = ccui.Text:create()
labNiCheng:ignoreContentAdaptWithSize(true)
labNiCheng:setTextAreaSize(cc.size(0, 0))
labNiCheng:setFontName("simhei.ttf")
labNiCheng:setFontSize(30)
labNiCheng:setString([[]])
labNiCheng:setLayoutComponentEnabled(true)
labNiCheng:setName("labNiCheng")
labNiCheng:setTag(429)
labNiCheng:setCascadeColorEnabled(true)
labNiCheng:setCascadeOpacityEnabled(true)
labNiCheng:setAnchorPoint(0.0000, 0.5000)
labNiCheng:setPosition(554.0000, 837.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(labNiCheng)
layout:setPositionPercentX(0.2885)
layout:setPositionPercentY(0.7750)
layout:setPercentWidth(0.0859)
layout:setPercentHeight(0.0315)
layout:setLeftMargin(554.0000)
layout:setRightMargin(1201.0000)
layout:setTopMargin(226.0000)
layout:setBottomMargin(820.0000)
Node:addChild(labNiCheng)

--Create labChips
local labChips = ccui.Text:create()
labChips:ignoreContentAdaptWithSize(true)
labChips:setTextAreaSize(cc.size(0, 0))
labChips:setFontName("simhei.ttf")
labChips:setFontSize(30)
labChips:setString([[]])
labChips:setLayoutComponentEnabled(true)
labChips:setName("labChips")
labChips:setTag(430)
labChips:setCascadeColorEnabled(true)
labChips:setCascadeOpacityEnabled(true)
labChips:setAnchorPoint(0.0000, 0.5000)
labChips:setPosition(554.0000, 783.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(labChips)
layout:setPositionPercentX(0.2885)
layout:setPositionPercentY(0.7250)
layout:setPercentWidth(0.0156)
layout:setPercentHeight(0.0315)
layout:setLeftMargin(554.0000)
layout:setRightMargin(1336.0000)
layout:setTopMargin(280.0000)
layout:setBottomMargin(766.0000)
Node:addChild(labChips)

--Create labJuShu
local labJuShu = ccui.Text:create()
labJuShu:ignoreContentAdaptWithSize(true)
labJuShu:setTextAreaSize(cc.size(0, 0))
labJuShu:setFontName("simhei.ttf")
labJuShu:setFontSize(30)
labJuShu:setString([[]])
labJuShu:setLayoutComponentEnabled(true)
labJuShu:setName("labJuShu")
labJuShu:setTag(431)
labJuShu:setCascadeColorEnabled(true)
labJuShu:setCascadeOpacityEnabled(true)
labJuShu:setAnchorPoint(0.0000, 0.5000)
labJuShu:setPosition(554.0000, 727.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(labJuShu)
layout:setPositionPercentX(0.2885)
layout:setPositionPercentY(0.6731)
layout:setPercentWidth(0.0156)
layout:setPercentHeight(0.0315)
layout:setLeftMargin(554.0000)
layout:setRightMargin(1336.0000)
layout:setTopMargin(336.0000)
layout:setBottomMargin(710.0000)
Node:addChild(labJuShu)

--Create labChengJi
local labChengJi = ccui.Text:create()
labChengJi:ignoreContentAdaptWithSize(true)
labChengJi:setTextAreaSize(cc.size(0, 0))
labChengJi:setFontName("simhei.ttf")
labChengJi:setFontSize(30)
labChengJi:setString([[]])
labChengJi:setLayoutComponentEnabled(true)
labChengJi:setName("labChengJi")
labChengJi:setTag(432)
labChengJi:setCascadeColorEnabled(true)
labChengJi:setCascadeOpacityEnabled(true)
labChengJi:setAnchorPoint(0.0000, 0.5000)
labChengJi:setPosition(554.0000, 672.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(labChengJi)
layout:setPositionPercentX(0.2885)
layout:setPositionPercentY(0.6222)
layout:setPercentWidth(0.0156)
layout:setPercentHeight(0.0315)
layout:setLeftMargin(554.0000)
layout:setRightMargin(1336.0000)
layout:setTopMargin(391.0000)
layout:setBottomMargin(655.0000)
Node:addChild(labChengJi)

--Create imgBanker
local imgBanker = cc.Sprite:create("game/4s_std/resource/word/4sshop_banker_dianzhang.png")
imgBanker:setName("imgBanker")
imgBanker:setTag(433)
imgBanker:setCascadeColorEnabled(true)
imgBanker:setCascadeOpacityEnabled(true)
imgBanker:setPosition(269.0000, 837.0006)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBanker)
layout:setPositionPercentX(0.1401)
layout:setPositionPercentY(0.7750)
layout:setSize(cc.size(162.0000, 153.0000))
layout:setLeftMargin(188.0000)
layout:setRightMargin(1570.0000)
layout:setTopMargin(166.4994)
layout:setBottomMargin(760.5006)
Node:addChild(imgBanker)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

