--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------


-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create pnlChips
local pnlChips = ccui.Layout:create()
pnlChips:ignoreContentAdaptWithSize(false)
pnlChips:setBackGroundColorOpacity(102)
pnlChips:setLayoutComponentEnabled(true)
pnlChips:setName("pnlChips")
pnlChips:setTag(76)
pnlChips:setCascadeColorEnabled(true)
pnlChips:setCascadeOpacityEnabled(true)
pnlChips:setPosition(0.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(pnlChips)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize(cc.size(1920.0000, 1080.0000))
layout:setLeftMargin(0.0000)
layout:setRightMargin(0.0000)
layout:setTopMargin(0.0000)
layout:setBottomMargin(0.0000)
Node:addChild(pnlChips)

--Create fntPlayer8
local fntPlayer8 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer8:setLayoutComponentEnabled(true)
fntPlayer8:setName("fntPlayer8")
fntPlayer8:setTag(77)
fntPlayer8:setCascadeColorEnabled(true)
fntPlayer8:setCascadeOpacityEnabled(true)
fntPlayer8:setPosition(1098.8750, 354.6421)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer8)
layout:setPositionPercentX(0.5723)
layout:setPositionPercentY(0.3284)
layout:setLeftMargin(1098.8750)
layout:setRightMargin(821.1254)
layout:setTopMargin(725.3579)
layout:setBottomMargin(354.6421)
Node:addChild(fntPlayer8)

--Create fntPlayer7
local fntPlayer7 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer7:setLayoutComponentEnabled(true)
fntPlayer7:setName("fntPlayer7")
fntPlayer7:setTag(78)
fntPlayer7:setCascadeColorEnabled(true)
fntPlayer7:setCascadeOpacityEnabled(true)
fntPlayer7:setPosition(911.3916, 354.6421)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer7)
layout:setPositionPercentX(0.4747)
layout:setPositionPercentY(0.3284)
layout:setPercentWidth(0.0053)
layout:setPercentHeight(0.3000)
layout:setLeftMargin(816.3916)
layout:setRightMargin(913.6084)
layout:setTopMargin(712.3579)
layout:setBottomMargin(341.6421)
Node:addChild(fntPlayer7)

--Create fntPlayer6
local fntPlayer6 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer6:setLayoutComponentEnabled(true)
fntPlayer6:setName("fntPlayer6")
fntPlayer6:setTag(79)
fntPlayer6:setCascadeColorEnabled(true)
fntPlayer6:setCascadeOpacityEnabled(true)
fntPlayer6:setPosition(721.9089, 354.6421)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer6)
layout:setPositionPercentX(0.3760)
layout:setPositionPercentY(0.3284)
layout:setPercentWidth(0.0053)
layout:setPercentHeight(0.3000)
layout:setLeftMargin(626.9089)
layout:setRightMargin(1103.0910)
layout:setTopMargin(712.3579)
layout:setBottomMargin(341.6421)
Node:addChild(fntPlayer6)

--Create fntPlayer5
local fntPlayer5 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer5:setLayoutComponentEnabled(true)
fntPlayer5:setName("fntPlayer5")
fntPlayer5:setTag(80)
fntPlayer5:setCascadeColorEnabled(true)
fntPlayer5:setCascadeOpacityEnabled(true)
fntPlayer5:setPosition(530.4263, 354.6421)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer5)
layout:setPositionPercentX(0.2763)
layout:setPositionPercentY(0.3284)
layout:setPercentWidth(0.0053)
layout:setPercentHeight(0.3000)
layout:setLeftMargin(435.4263)
layout:setRightMargin(1294.5740)
layout:setTopMargin(712.3579)
layout:setBottomMargin(341.6421)
Node:addChild(fntPlayer5)

--Create fntPlayer4
local fntPlayer4 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer4:setLayoutComponentEnabled(true)
fntPlayer4:setName("fntPlayer4")
fntPlayer4:setTag(81)
fntPlayer4:setCascadeColorEnabled(true)
fntPlayer4:setCascadeOpacityEnabled(true)
fntPlayer4:setPosition(1100.1060, 558.8492)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer4)
layout:setPositionPercentX(0.5730)
layout:setPositionPercentY(0.5175)
layout:setPercentWidth(0.0053)
layout:setPercentHeight(0.3000)
layout:setLeftMargin(1005.1060)
layout:setRightMargin(724.8944)
layout:setTopMargin(508.1508)
layout:setBottomMargin(545.8492)
Node:addChild(fntPlayer4)

--Create fntPlayer3
local fntPlayer3 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer3:setLayoutComponentEnabled(true)
fntPlayer3:setName("fntPlayer3")
fntPlayer3:setTag(82)
fntPlayer3:setCascadeColorEnabled(true)
fntPlayer3:setCascadeOpacityEnabled(true)
fntPlayer3:setPosition(907.7507, 558.8492)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer3)
layout:setPositionPercentX(0.4728)
layout:setPositionPercentY(0.5175)
layout:setPercentWidth(0.0053)
layout:setPercentHeight(0.3000)
layout:setLeftMargin(812.7507)
layout:setRightMargin(917.2493)
layout:setTopMargin(508.1508)
layout:setBottomMargin(545.8492)
Node:addChild(fntPlayer3)

--Create fntPlayer2
local fntPlayer2 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer2:setLayoutComponentEnabled(true)
fntPlayer2:setName("fntPlayer2")
fntPlayer2:setTag(83)
fntPlayer2:setCascadeColorEnabled(true)
fntPlayer2:setCascadeOpacityEnabled(true)
fntPlayer2:setPosition(724.3965, 558.8492)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer2)
layout:setPositionPercentX(0.3773)
layout:setPositionPercentY(0.5175)
layout:setPercentWidth(0.0053)
layout:setPercentHeight(0.3000)
layout:setLeftMargin(629.3965)
layout:setRightMargin(1100.6040)
layout:setTopMargin(508.1508)
layout:setBottomMargin(545.8492)
Node:addChild(fntPlayer2)

--Create fntPlayer1
local fntPlayer1 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntPlayer1:setLayoutComponentEnabled(true)
fntPlayer1:setName("fntPlayer1")
fntPlayer1:setTag(84)
fntPlayer1:setCascadeColorEnabled(true)
fntPlayer1:setCascadeOpacityEnabled(true)
fntPlayer1:setPosition(533.0420, 558.8492)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayer1)
layout:setPositionPercentX(0.2776)
layout:setPositionPercentY(0.5175)
layout:setPercentWidth(0.0053)
layout:setPercentHeight(0.3000)
layout:setLeftMargin(438.0420)
layout:setRightMargin(1291.9580)
layout:setTopMargin(508.1508)
layout:setBottomMargin(545.8492)
Node:addChild(fntPlayer1)

--Create fntTotal8
local fntTotal8 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal8:setLayoutComponentEnabled(true)
fntTotal8:setName("fntTotal8")
fntTotal8:setTag(85)
fntTotal8:setCascadeColorEnabled(true)
fntTotal8:setCascadeOpacityEnabled(true)
fntTotal8:setPosition(1100.8750, 469.8837)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal8)
layout:setPositionPercentX(0.5734)
layout:setPositionPercentY(0.4351)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(1005.8750)
layout:setRightMargin(724.1252)
layout:setTopMargin(597.1163)
layout:setBottomMargin(456.8837)
Node:addChild(fntTotal8)

--Create fntTotal7
local fntTotal7 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal7:setLayoutComponentEnabled(true)
fntTotal7:setName("fntTotal7")
fntTotal7:setTag(86)
fntTotal7:setCascadeColorEnabled(true)
fntTotal7:setCascadeOpacityEnabled(true)
fntTotal7:setPosition(906.3914, 469.8837)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal7)
layout:setPositionPercentX(0.4721)
layout:setPositionPercentY(0.4351)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(811.3914)
layout:setRightMargin(918.6086)
layout:setTopMargin(597.1163)
layout:setBottomMargin(456.8837)
Node:addChild(fntTotal7)

--Create fntTotal6
local fntTotal6 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal6:setLayoutComponentEnabled(true)
fntTotal6:setName("fntTotal6")
fntTotal6:setTag(87)
fntTotal6:setCascadeColorEnabled(true)
fntTotal6:setCascadeOpacityEnabled(true)
fntTotal6:setPosition(717.9088, 469.8837)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal6)
layout:setPositionPercentX(0.3739)
layout:setPositionPercentY(0.4351)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(622.9088)
layout:setRightMargin(1107.0910)
layout:setTopMargin(597.1163)
layout:setBottomMargin(456.8837)
Node:addChild(fntTotal6)

--Create fntTotal5
local fntTotal5 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal5:setLayoutComponentEnabled(true)
fntTotal5:setName("fntTotal5")
fntTotal5:setTag(88)
fntTotal5:setCascadeColorEnabled(true)
fntTotal5:setCascadeOpacityEnabled(true)
fntTotal5:setPosition(531.4263, 469.8837)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal5)
layout:setPositionPercentX(0.2768)
layout:setPositionPercentY(0.4351)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(436.4263)
layout:setRightMargin(1293.5740)
layout:setTopMargin(597.1163)
layout:setBottomMargin(456.8837)
Node:addChild(fntTotal5)

--Create fntTotal4
local fntTotal4 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal4:setLayoutComponentEnabled(true)
fntTotal4:setName("fntTotal4")
fntTotal4:setTag(89)
fntTotal4:setCascadeColorEnabled(true)
fntTotal4:setCascadeOpacityEnabled(true)
fntTotal4:setPosition(1101.1060, 674.0909)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal4)
layout:setPositionPercentX(0.5735)
layout:setPositionPercentY(0.6242)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(1006.1060)
layout:setRightMargin(723.8944)
layout:setTopMargin(392.9091)
layout:setBottomMargin(661.0909)
Node:addChild(fntTotal4)

--Create fntTotal3
local fntTotal3 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal3:setLayoutComponentEnabled(true)
fntTotal3:setName("fntTotal3")
fntTotal3:setTag(90)
fntTotal3:setCascadeColorEnabled(true)
fntTotal3:setCascadeOpacityEnabled(true)
fntTotal3:setPosition(911.7507, 674.0909)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal3)
layout:setPositionPercentX(0.4749)
layout:setPositionPercentY(0.6242)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(816.7507)
layout:setRightMargin(913.2493)
layout:setTopMargin(392.9091)
layout:setBottomMargin(661.0909)
Node:addChild(fntTotal3)

--Create fntTotal2
local fntTotal2 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal2:setLayoutComponentEnabled(true)
fntTotal2:setName("fntTotal2")
fntTotal2:setTag(91)
fntTotal2:setCascadeColorEnabled(true)
fntTotal2:setCascadeOpacityEnabled(true)
fntTotal2:setPosition(724.3965, 674.0909)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal2)
layout:setPositionPercentX(0.3773)
layout:setPositionPercentY(0.6242)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(629.3965)
layout:setRightMargin(1100.6040)
layout:setTopMargin(392.9091)
layout:setBottomMargin(661.0909)
Node:addChild(fntTotal2)

--Create fntTotal1
local fntTotal1 = ccui.TextAtlas:create([[]],
													"game/4s_std/resource/number/4sshop_number1.png",
													19,
													26,
													"0")
fntTotal1:setLayoutComponentEnabled(true)
fntTotal1:setName("fntTotal1")
fntTotal1:setTag(92)
fntTotal1:setCascadeColorEnabled(true)
fntTotal1:setCascadeOpacityEnabled(true)
fntTotal1:setPosition(533.0420, 674.0909)
layout = ccui.LayoutComponent:bindLayoutComponent(fntTotal1)
layout:setPositionPercentX(0.2776)
layout:setPositionPercentY(0.6242)
layout:setPercentWidth(0.8842)
layout:setPercentHeight(0.1000)
layout:setLeftMargin(438.0420)
layout:setRightMargin(1291.9580)
layout:setTopMargin(392.9091)
layout:setBottomMargin(661.0909)
Node:addChild(fntTotal1)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

