--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------


-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgBg
local imgBg = cc.Sprite:create("game/4s_std/resource/image/desk/4sdating.jpg")
imgBg:setName("imgBg")
imgBg:setTag(168)
imgBg:setCascadeColorEnabled(true)
imgBg:setCascadeOpacityEnabled(true)
imgBg:setPosition(0.9999, -1.0001)
imgBg:setOpacity(251)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(825.0000, 590.0000))
layout:setLeftMargin(-411.5001)
layout:setRightMargin(-413.4999)
layout:setTopMargin(-293.9999)
layout:setBottomMargin(-296.0001)
Node:addChild(imgBg)

--Create btnPlayer
local btnPlayer = ccui.Button:create()
btnPlayer:ignoreContentAdaptWithSize(false)
btnPlayer:loadTextureNormal("game/4s_std/resource/image/desk/jryx1.png",0)
btnPlayer:loadTexturePressed("game/4s_std/resource/image/desk/jryx2.png",0)
btnPlayer:loadTextureDisabled("game/4s_std/resource/image/desk/jryx3.png",0)
btnPlayer:setTitleFontSize(14)
btnPlayer:setTitleColor(cc.c3b(65, 65, 70))
btnPlayer:setScale9Enabled(true)
btnPlayer:setCapInsets(cc.rect(15,11,134,27))
btnPlayer:setLayoutComponentEnabled(true)
btnPlayer:setName("btnPlayer")
btnPlayer:setTag(169)
btnPlayer:setCascadeColorEnabled(true)
btnPlayer:setCascadeOpacityEnabled(true)
btnPlayer:setPosition(-1.5269, -215.8795)
layout = ccui.LayoutComponent:bindLayoutComponent(btnPlayer)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(164.0000, 49.0000))
layout:setLeftMargin(-83.5269)
layout:setRightMargin(-80.4731)
layout:setTopMargin(191.3795)
layout:setBottomMargin(-240.3795)
Node:addChild(btnPlayer)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

