--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create btnStop
local btnStop = ccui.Button:create()
btnStop:ignoreContentAdaptWithSize(false)
btnStop:loadTextureNormal("game/4s_std/resource/button/4sshop_button_stop.png",0)
btnStop:setTitleFontSize(14)
btnStop:setTitleColor(cc.c3b(65, 65, 70))
btnStop:setScale9Enabled(true)
btnStop:setCapInsets(cc.rect(15,11,115,79))
btnStop:setLayoutComponentEnabled(true)
btnStop:setName("btnStop")
btnStop:setTag(435)
btnStop:setCascadeColorEnabled(true)
btnStop:setCascadeOpacityEnabled(true)
btnStop:setPosition(878.0001, 818.9985)
layout = ccui.LayoutComponent:bindLayoutComponent(btnStop)
layout:setPositionPercentX(0.4573)
layout:setPositionPercentY(0.7583)
layout:setPercentWidth(0.0755)
layout:setPercentHeight(0.0935)
layout:setSize(cc.size(145.0000, 101.0000))
layout:setLeftMargin(805.5001)
layout:setRightMargin(969.4999)
layout:setTopMargin(210.5015)
layout:setBottomMargin(768.4985)
Node:addChild(btnStop)

--Create btnCancel
local btnCancel = ccui.Button:create()
btnCancel:ignoreContentAdaptWithSize(false)
btnCancel:loadTextureNormal("game/4s_std/resource/button/4sshop_button_quxiao.png",0)
btnCancel:setTitleFontSize(14)
btnCancel:setTitleColor(cc.c3b(65, 65, 70))
btnCancel:setScale9Enabled(true)
btnCancel:setCapInsets(cc.rect(15,11,115,79))
btnCancel:setLayoutComponentEnabled(true)
btnCancel:setName("btnCancel")
btnCancel:setTag(436)
btnCancel:setCascadeColorEnabled(true)
btnCancel:setCascadeOpacityEnabled(true)
btnCancel:setPosition(878.0000, 819.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnCancel)
layout:setPositionPercentX(0.4573)
layout:setPositionPercentY(0.7583)
layout:setPercentWidth(0.0755)
layout:setPercentHeight(0.0935)
layout:setSize(cc.size(145.0000, 101.0000))
layout:setLeftMargin(805.5000)
layout:setRightMargin(969.5000)
layout:setTopMargin(210.5000)
layout:setBottomMargin(768.5000)
Node:addChild(btnCancel)

--Create btnApply
local btnApply = ccui.Button:create()
btnApply:ignoreContentAdaptWithSize(false)
btnApply:loadTextureNormal("game/4s_std/resource/button/4sshop_button_banker.png",0)
btnApply:setTitleFontSize(14)
btnApply:setTitleColor(cc.c3b(65, 65, 70))
btnApply:setScale9Enabled(true)
btnApply:setCapInsets(cc.rect(15,11,115,79))
btnApply:setLayoutComponentEnabled(true)
btnApply:setName("btnApply")
btnApply:setTag(437)
btnApply:setCascadeColorEnabled(true)
btnApply:setCascadeOpacityEnabled(true)
btnApply:setPosition(878.0000, 819.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(btnApply)
layout:setPositionPercentX(0.4573)
layout:setPositionPercentY(0.7583)
layout:setPercentWidth(0.0755)
layout:setPercentHeight(0.0935)
layout:setSize(cc.size(145.0000, 101.0000))
layout:setLeftMargin(805.5000)
layout:setRightMargin(969.5000)
layout:setTopMargin(210.5000)
layout:setBottomMargin(768.5000)
Node:addChild(btnApply)

--Create rank
local rank = cc.Sprite:create("game/4s_std/resource/word/ddsz.png")
rank:setName("rank")
rank:setTag(438)
rank:setCascadeColorEnabled(true)
rank:setCascadeOpacityEnabled(true)
rank:setPosition(530.0000, 577.9998)
rank:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(rank)
layout:setPositionPercentX(0.2760)
layout:setPositionPercentY(0.5352)
layout:setSize(cc.size(580.0000, 70.0000))
layout:setLeftMargin(240.0000)
layout:setRightMargin(1100.0000)
layout:setTopMargin(467.0002)
layout:setBottomMargin(542.9998)
Node:addChild(rank)

--Create ruquestNumber
-- local ruquestNumber = ccui.TextBMFont:create()
-- ruquestNumber:setFntFile("game/4s_std/resource/number/handsel.fnt")
local ruquestNumber = ccui.Text:create()
ruquestNumber:setFontName("lobby/resource/font/simhei.ttf")
ruquestNumber:setFontSize(30)
ruquestNumber:setString([[99]])
ruquestNumber:setLayoutComponentEnabled(true)
ruquestNumber:setName("ruquestNumber")
ruquestNumber:setTag(439)
ruquestNumber:setCascadeColorEnabled(true)
ruquestNumber:setCascadeOpacityEnabled(true)
ruquestNumber:setPosition(442.0001, 578.0000)
ruquestNumber:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(ruquestNumber)
layout:setPositionPercentX(0.2302)
layout:setPositionPercentY(0.5352)
layout:setPercentWidth(0.0474)
layout:setPercentHeight(0.0454)
layout:setSize(cc.size(90.0000, 49.0000))
layout:setLeftMargin(397.0001)
layout:setRightMargin(1433.0000)
layout:setTopMargin(477.5000)
layout:setBottomMargin(553.5000)
Node:addChild(ruquestNumber)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

