--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------


-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgBankerBg
local imgBankerBg = cc.Sprite:create("game/4s_std/resource/image/jiesuan/Nroom_victorybg.png")
imgBankerBg:setName("imgBankerBg")
imgBankerBg:setTag(107)
imgBankerBg:setCascadeColorEnabled(true)
imgBankerBg:setCascadeOpacityEnabled(true)
imgBankerBg:setPosition(821.5104, 510.9190)
layout = ccui.LayoutComponent:bindLayoutComponent(imgBankerBg)
layout:setPositionPercentX(0.4279)
layout:setPositionPercentY(0.4731)
layout:setSize(cc.size(492.0000, 74.0000))
layout:setLeftMargin(575.5104)
layout:setRightMargin(852.4896)
layout:setTopMargin(532.0809)
layout:setBottomMargin(473.9190)
Node:addChild(imgBankerBg)

--Create imgPlayerBg
local imgPlayerBg = cc.Sprite:create("game/4s_std/resource/image/jiesuan/Nroom_failureibg.png")
imgPlayerBg:setName("imgPlayerBg")
imgPlayerBg:setTag(108)
imgPlayerBg:setCascadeColorEnabled(true)
imgPlayerBg:setCascadeOpacityEnabled(true)
imgPlayerBg:setPosition(821.5104, 638.7566)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayerBg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(0.2562)
layout:setPercentHeight(0.0685)
layout:setSize(cc.size(492.0000, 74.0000))
layout:setLeftMargin(575.5104)
layout:setRightMargin(-1067.5100)
layout:setTopMargin(-675.7566)
layout:setBottomMargin(601.7566)
Node:addChild(imgPlayerBg)

--Create imgPlayer0
local imgPlayer0 = cc.Sprite:create("game/4s_std/resource/word/zuanjia.png")
imgPlayer0:setName("imgPlayer0")
imgPlayer0:setTag(109)
imgPlayer0:setCascadeColorEnabled(true)
imgPlayer0:setCascadeOpacityEnabled(true)
imgPlayer0:setPosition(682.6248, 509.2729)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayer0)
layout:setPositionPercentX(0.3555)
layout:setPositionPercentY(0.4715)
layout:setPercentWidth(0.2562)
layout:setPercentHeight(0.0685)
layout:setSize(cc.size(79.0000, 42.0000))
layout:setLeftMargin(643.1248)
layout:setRightMargin(1197.8750)
layout:setTopMargin(549.7271)
layout:setBottomMargin(488.2729)
Node:addChild(imgPlayer0)

--Create imgPlayer0_0
local imgPlayer0_0 = cc.Sprite:create("game/4s_std/resource/word/wo.png")
imgPlayer0_0:setName("imgPlayer0_0")
imgPlayer0_0:setTag(110)
imgPlayer0_0:setCascadeColorEnabled(true)
imgPlayer0_0:setCascadeOpacityEnabled(true)
imgPlayer0_0:setPosition(682.9973, 637.9764)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayer0_0)
layout:setPositionPercentX(0.3557)
layout:setPositionPercentY(0.5907)
layout:setPercentWidth(0.2562)
layout:setPercentHeight(0.0685)
layout:setSize(cc.size(79.0000, 42.0000))
layout:setLeftMargin(643.4973)
layout:setRightMargin(1197.5030)
layout:setTopMargin(421.0236)
layout:setBottomMargin(616.9764)
Node:addChild(imgPlayer0_0)

--Create fntBankerChips
-- local fntBankerChips = ccui.TextBMFont:create()
-- fntBankerChips:setFntFile("game/4s_std/resource/number/jiesuan.fnt")
local fntBankerChips = ccui.Text:create()
fntBankerChips:setFontName("lobby/resource/font/simhei.ttf")
fntBankerChips:setFontSize(30)
fntBankerChips:setString([[+123456]])
fntBankerChips:setLayoutComponentEnabled(true)
fntBankerChips:setName("fntBankerChips")
fntBankerChips:setTag(111)
fntBankerChips:setCascadeColorEnabled(true)
fntBankerChips:setCascadeOpacityEnabled(true)
fntBankerChips:setAnchorPoint(0.0000, 0.0000)
fntBankerChips:setPosition(770.7278, 481.7181)
layout = ccui.LayoutComponent:bindLayoutComponent(fntBankerChips)
layout:setPositionPercentX(0.4014)
layout:setPositionPercentY(0.4460)
layout:setPercentWidth(0.0005)
layout:setPercentHeight(0.0444)
layout:setSize(cc.size(224.0000, 48.0000))
layout:setLeftMargin(770.7278)
layout:setRightMargin(925.2722)
layout:setTopMargin(550.2819)
layout:setBottomMargin(481.7181)
Node:addChild(fntBankerChips)

--Create fntPlayerChips
-- local fntPlayerChips = ccui.TextBMFont:create()
-- fntPlayerChips:setFntFile("game/4s_std/resource/number/jiesuan.fnt")
local fntPlayerChips = ccui.Text:create()
fntPlayerChips:setFontName("lobby/resource/font/simhei.ttf")
fntPlayerChips:setFontSize(30)
fntPlayerChips:setString([[-123456]])
fntPlayerChips:setLayoutComponentEnabled(true)
fntPlayerChips:setName("fntPlayerChips")
fntPlayerChips:setTag(112)
fntPlayerChips:setCascadeColorEnabled(true)
fntPlayerChips:setCascadeOpacityEnabled(true)
fntPlayerChips:setAnchorPoint(0.0000, 0.0000)
fntPlayerChips:setPosition(770.7278, 610.9962)
layout = ccui.LayoutComponent:bindLayoutComponent(fntPlayerChips)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setPercentWidth(0.1167)
layout:setPercentHeight(0.0444)
layout:setSize(cc.size(224.0000, 48.0000))
layout:setLeftMargin(770.7278)
layout:setRightMargin(-994.7278)
layout:setTopMargin(-658.9962)
layout:setBottomMargin(610.9962)
Node:addChild(fntPlayerChips)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

