--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------


-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create imgPlayer
local imgPlayer = cc.Sprite:create("game/4s_std/resource/image/player/4sshop_banker_bj.png")
imgPlayer:setName("imgPlayer")
imgPlayer:setTag(352)
imgPlayer:setCascadeColorEnabled(true)
imgPlayer:setCascadeOpacityEnabled(true)
imgPlayer:setAnchorPoint(0.0000, 0.0000)
imgPlayer:setPosition(2.7001, 20.1239)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayer)
layout:setPositionPercentX(0.0014)
layout:setPositionPercentY(0.0186)
layout:setSize(cc.size(280.0000, 154.0000))
layout:setLeftMargin(2.7001)
layout:setRightMargin(1637.3000)
layout:setTopMargin(905.8762)
layout:setBottomMargin(20.1239)
Node:addChild(imgPlayer)

--Create imgPlayerHead
local imgPlayerHead = cc.Sprite:create("game/4s_std/resource/image/banker/4sshop_banker_touxiang.png")
imgPlayerHead:setName("imgPlayerHead")
imgPlayerHead:setTag(353)
imgPlayerHead:setCascadeColorEnabled(true)
imgPlayerHead:setCascadeOpacityEnabled(true)
imgPlayerHead:setPosition(41.3501, 128.2334)
layout = ccui.LayoutComponent:bindLayoutComponent(imgPlayerHead)
layout:setPositionPercentX(0.0215)
layout:setPositionPercentY(0.1187)
layout:setSize(cc.size(60.0000, 62.0000))
layout:setLeftMargin(11.3501)
layout:setRightMargin(1848.6500)
layout:setTopMargin(920.7666)
layout:setBottomMargin(97.2334)
Node:addChild(imgPlayerHead)

--Create imgNiCheng
local imgNiCheng = cc.Sprite:create("game/4s_std/resource/word/4sshop_banker_nicheng.png")
imgNiCheng:setName("imgNiCheng")
imgNiCheng:setTag(354)
imgNiCheng:setCascadeColorEnabled(true)
imgNiCheng:setCascadeOpacityEnabled(true)
imgNiCheng:setPosition(100.1682, 144.2450)
layout = ccui.LayoutComponent:bindLayoutComponent(imgNiCheng)
layout:setPositionPercentX(0.0522)
layout:setPositionPercentY(0.1336)
layout:setSize(cc.size(50.0000, 22.0000))
layout:setLeftMargin(75.1682)
layout:setRightMargin(1794.8320)
layout:setTopMargin(924.7550)
layout:setBottomMargin(133.2450)
Node:addChild(imgNiCheng)

--Create imgChips
local imgChips = cc.Sprite:create("game/4s_std/resource/word/4sshop_banker_chouma.png")
imgChips:setName("imgChips")
imgChips:setTag(355)
imgChips:setCascadeColorEnabled(true)
imgChips:setCascadeOpacityEnabled(true)
imgChips:setPosition(96.5097, 108.2881)
layout = ccui.LayoutComponent:bindLayoutComponent(imgChips)
layout:setPositionPercentX(0.0503)
layout:setPositionPercentY(0.1003)
layout:setSize(cc.size(50.0000, 22.0000))
layout:setLeftMargin(71.5097)
layout:setRightMargin(1798.4900)
layout:setTopMargin(960.7119)
layout:setBottomMargin(97.2881)
Node:addChild(imgChips)

--Create imgJinBi
local imgJinBi = cc.Sprite:create("game/4s_std/resource/word/4sshop_banker_jinbi.png")
imgJinBi:setName("imgJinBi")
imgJinBi:setTag(356)
imgJinBi:setCascadeColorEnabled(true)
imgJinBi:setCascadeOpacityEnabled(true)
imgJinBi:setPosition(35.8319, 75.6136)
layout = ccui.LayoutComponent:bindLayoutComponent(imgJinBi)
layout:setPositionPercentX(0.0187)
layout:setPositionPercentY(0.0700)
layout:setSize(cc.size(50.0000, 22.0000))
layout:setLeftMargin(10.8319)
layout:setRightMargin(1859.1680)
layout:setTopMargin(993.3864)
layout:setBottomMargin(64.6136)
Node:addChild(imgJinBi)

--Create imgChengJi
local imgChengJi = cc.Sprite:create("game/4s_std/resource/word/4sshop_banker_chengji.png")
imgChengJi:setName("imgChengJi")
imgChengJi:setTag(357)
imgChengJi:setCascadeColorEnabled(true)
imgChengJi:setCascadeOpacityEnabled(true)
imgChengJi:setPosition(34.9121, 46.5188)
layout = ccui.LayoutComponent:bindLayoutComponent(imgChengJi)
layout:setPositionPercentX(0.0182)
layout:setPositionPercentY(0.0431)
layout:setSize(cc.size(50.0000, 22.0000))
layout:setLeftMargin(9.9121)
layout:setRightMargin(1860.0880)
layout:setTopMargin(1022.4810)
layout:setBottomMargin(35.5188)
Node:addChild(imgChengJi)

--Create imgNiChengBg
local imgNiChengBg = ccui.ImageView:create()
imgNiChengBg:ignoreContentAdaptWithSize(false)
imgNiChengBg:loadTexture("game/4s_std/resource/image/player/4sshop_banker_tiao.png",0)
imgNiChengBg:setScale9Enabled(true)
imgNiChengBg:setCapInsets(cc.rect(8,6,11,15))
imgNiChengBg:setLayoutComponentEnabled(true)
imgNiChengBg:setName("imgNiChengBg")
imgNiChengBg:setTag(358)
imgNiChengBg:setCascadeColorEnabled(true)
imgNiChengBg:setCascadeOpacityEnabled(true)
imgNiChengBg:setPosition(201.6046, 145.0014)
layout = ccui.LayoutComponent:bindLayoutComponent(imgNiChengBg)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(150.0000, 24.0000))
layout:setLeftMargin(126.6046)
layout:setRightMargin(-276.6046)
layout:setTopMargin(-157.0014)
layout:setBottomMargin(133.0014)
Node:addChild(imgNiChengBg)

--Create labNiCheng
local labNiCheng = ccui.Text:create()
labNiCheng:ignoreContentAdaptWithSize(true)
labNiCheng:setTextAreaSize(cc.size(0, 0))
labNiCheng:setFontName("lobby/resource/font/simhei.ttf")
labNiCheng:setFontSize(16)
labNiCheng:setString([[开始骂街装死干呕]])
labNiCheng:setLayoutComponentEnabled(true)
labNiCheng:setName("labNiCheng")
labNiCheng:setTag(359)
labNiCheng:setCascadeColorEnabled(true)
labNiCheng:setCascadeOpacityEnabled(true)
labNiCheng:setAnchorPoint(0.0000, 0.5000)
labNiCheng:setPosition(131.6605, 143.2139)
labNiCheng:setColor(cc.c3b(157, 149, 160))
layout = ccui.LayoutComponent:bindLayoutComponent(labNiCheng)
layout:setPositionPercentX(0.0686)
layout:setPositionPercentY(0.1326)
layout:setSize(cc.size(128.0000, 18.0000))
layout:setLeftMargin(131.6605)
layout:setRightMargin(-259.6605)
layout:setTopMargin(-152.2139)
layout:setBottomMargin(134.2139)
Node:addChild(labNiCheng)

--Create imgChipsBg
local imgChipsBg = ccui.ImageView:create()
imgChipsBg:ignoreContentAdaptWithSize(false)
imgChipsBg:loadTexture("game/4s_std/resource/image/player/4sshop_banker_tiao.png",0)
imgChipsBg:setScale9Enabled(true)
imgChipsBg:setCapInsets(cc.rect(8,6,11,15))
imgChipsBg:setLayoutComponentEnabled(true)
imgChipsBg:setName("imgChipsBg")
imgChipsBg:setTag(360)
imgChipsBg:setCascadeColorEnabled(true)
imgChipsBg:setCascadeOpacityEnabled(true)
imgChipsBg:setPosition(201.6049, 109.9988)
layout = ccui.LayoutComponent:bindLayoutComponent(imgChipsBg)
layout:setPositionPercentX(0.1050)
layout:setPositionPercentY(0.1019)
layout:setSize(cc.size(150.0000, 24.0000))
layout:setLeftMargin(126.6049)
layout:setRightMargin(-276.6049)
layout:setTopMargin(-121.9988)
layout:setBottomMargin(97.9988)
Node:addChild(imgChipsBg)

--Create imgJinBiBg
local imgJinBiBg = ccui.ImageView:create()
imgJinBiBg:ignoreContentAdaptWithSize(false)
imgJinBiBg:loadTexture("game/4s_std/resource/image/player/4sshop_banker_tiao.png",0)
imgJinBiBg:setScale9Enabled(true)
imgJinBiBg:setCapInsets(cc.rect(8,6,11,15))
imgJinBiBg:setLayoutComponentEnabled(true)
imgJinBiBg:setName("imgJinBiBg")
imgJinBiBg:setTag(361)
imgJinBiBg:setCascadeColorEnabled(true)
imgJinBiBg:setCascadeOpacityEnabled(true)
imgJinBiBg:setPosition(168.8652, 76.2103)
layout = ccui.LayoutComponent:bindLayoutComponent(imgJinBiBg)
layout:setPositionPercentX(0.0880)
layout:setPositionPercentY(0.0706)
layout:setSize(cc.size(215.0000, 24.0000))
layout:setLeftMargin(61.3652)
layout:setRightMargin(-276.3652)
layout:setTopMargin(-88.2103)
layout:setBottomMargin(64.2103)
Node:addChild(imgJinBiBg)

--Create imgChengJiBg
local imgChengJiBg = ccui.ImageView:create()
imgChengJiBg:ignoreContentAdaptWithSize(false)
imgChengJiBg:loadTexture("game/4s_std/resource/image/player/4sshop_banker_tiao.png",0)
imgChengJiBg:setScale9Enabled(true)
imgChengJiBg:setCapInsets(cc.rect(8,6,11,15))
imgChengJiBg:setLayoutComponentEnabled(true)
imgChengJiBg:setName("imgChengJiBg")
imgChengJiBg:setTag(362)
imgChengJiBg:setCascadeColorEnabled(true)
imgChengJiBg:setCascadeOpacityEnabled(true)
imgChengJiBg:setPosition(167.9459, 45.6303)
layout = ccui.LayoutComponent:bindLayoutComponent(imgChengJiBg)
layout:setPositionPercentX(0.0875)
layout:setPositionPercentY(0.0423)
layout:setSize(cc.size(215.0000, 24.0000))
layout:setLeftMargin(60.4459)
layout:setRightMargin(-275.4459)
layout:setTopMargin(-57.6303)
layout:setBottomMargin(33.6303)
Node:addChild(imgChengJiBg)

--Create labChips
local labChips = ccui.Text:create()
labChips:ignoreContentAdaptWithSize(true)
labChips:setTextAreaSize(cc.size(0, 0))
labChips:setFontName("lobby/resource/font/simhei.ttf")
labChips:setFontSize(16)
labChips:setString([[12345678912]])
labChips:setLayoutComponentEnabled(true)
labChips:setName("labChips")
labChips:setTag(363)
labChips:setCascadeColorEnabled(true)
labChips:setCascadeOpacityEnabled(true)
labChips:setAnchorPoint(0.0000, 0.5000)
labChips:setPosition(130.8444, 107.8221)
labChips:setColor(cc.c3b(157, 149, 160))
layout = ccui.LayoutComponent:bindLayoutComponent(labChips)
layout:setPositionPercentX(0.0681)
layout:setPositionPercentY(0.0998)
layout:setSize(cc.size(88.0000, 18.0000))
layout:setLeftMargin(130.8444)
layout:setRightMargin(-218.8444)
layout:setTopMargin(-116.8221)
layout:setBottomMargin(98.8221)
Node:addChild(labChips)

--Create labJinBi
local labJinBi = ccui.Text:create()
labJinBi:ignoreContentAdaptWithSize(true)
labJinBi:setTextAreaSize(cc.size(0, 0))
labJinBi:setFontName("lobby/resource/font/simhei.ttf")
labJinBi:setFontSize(16)
labJinBi:setString([[12345678912]])
labJinBi:setLayoutComponentEnabled(true)
labJinBi:setName("labJinBi")
labJinBi:setTag(364)
labJinBi:setCascadeColorEnabled(true)
labJinBi:setCascadeOpacityEnabled(true)
labJinBi:setAnchorPoint(0.0000, 0.5000)
labJinBi:setPosition(70.1668, 75.8732)
labJinBi:setColor(cc.c3b(157, 149, 160))

layout = ccui.LayoutComponent:bindLayoutComponent(labJinBi)
layout:setPositionPercentX(0.0365)
layout:setPositionPercentY(0.0703)
layout:setSize(cc.size(288.0000, 18.0000))
layout:setLeftMargin(70.1668)
layout:setRightMargin(-158.1668)
layout:setTopMargin(-84.8732)
layout:setBottomMargin(66.8732)
Node:addChild(labJinBi)

--Create labChengJi
local labChengJi = ccui.Text:create()
labChengJi:ignoreContentAdaptWithSize(true)
labChengJi:setTextAreaSize(cc.size(0, 0))
labChengJi:setFontName("lobby/resource/font/simhei.ttf")
labChengJi:setFontSize(16)
labChengJi:setString([[12]])
labChengJi:setLayoutComponentEnabled(true)
labChengJi:setName("labChengJi")
labChengJi:setTag(365)
labChengJi:setCascadeColorEnabled(true)
labChengJi:setCascadeOpacityEnabled(true)
labChengJi:setAnchorPoint(0.0000, 0.5000)
labChengJi:setPosition(69.2475, 46.2932)
labChengJi:setColor(cc.c3b(157, 149, 160))
layout = ccui.LayoutComponent:bindLayoutComponent(labChengJi)
layout:setPositionPercentX(0.0361)
layout:setPositionPercentY(0.0429)
layout:setSize(cc.size(16.0000, 18.0000))
layout:setLeftMargin(69.2475)
layout:setRightMargin(-85.2475)
layout:setTopMargin(-55.2932)
layout:setBottomMargin(37.2932)
Node:addChild(labChengJi)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

