--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create sprHeadBack
local sprHeadBack = cc.Sprite:create("game/niuniu_std/resource/image/Nroom_headbg.png")
sprHeadBack:setName("sprHeadBack")
sprHeadBack:setTag(178)
sprHeadBack:setCascadeColorEnabled(true)
sprHeadBack:setCascadeOpacityEnabled(true)
sprHeadBack:setPosition(464.6189, 934.0723)
layout = ccui.LayoutComponent:bindLayoutComponent(sprHeadBack)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(400.0000, 172.0000))
layout:setLeftMargin(249.6189)
layout:setRightMargin(-479.6189)
layout:setTopMargin(-1061.0720)
layout:setBottomMargin(807.0723)
Node:addChild(sprHeadBack)

--Create sprHead
local sprHead = cc.Sprite:create("game/niuniu_std/resource/image/Nroom_headbg.png")
sprHead:setName("sprHead")
sprHead:setTag(179)
sprHead:setCascadeColorEnabled(true)
sprHead:setCascadeOpacityEnabled(true)
sprHead:setPosition(90.0000, 85.9998)
sprHead:setScaleX(0.6000)
sprHead:setScaleY(0.6000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprHead)
layout:setPositionPercentX(0.4957)
layout:setPositionPercentY(0.4528)
layout:setSize(cc.size(230.0000, 254.0000))
layout:setHorizontalEdge(3)
layout:setVerticalEdge(3)
layout:setLeftMargin(-0.9999)
layout:setRightMargin(0.9999)
layout:setTopMargin(11.9995)
layout:setBottomMargin(-11.9995)
sprHeadBack:addChild(sprHead)

--Create labName
local labName = ccui.Text:create()
labName:ignoreContentAdaptWithSize(true)
labName:setFontName("simhei.ttf")
labName:setFontSize(24)
labName:setString([[Text Label]])
labName:setLayoutComponentEnabled(true)
labName:setName("labName")
labName:setTag(180)
labName:setCascadeColorEnabled(true)
labName:setCascadeOpacityEnabled(true)
labName:setAnchorPoint(0.0000, 0.5000)
labName:setPosition(438.6830, 960.3960)
layout = ccui.LayoutComponent:bindLayoutComponent(labName)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(180.0000, 41.0000))
layout:setLeftMargin(438.6830)
layout:setRightMargin(-667.6830)
layout:setTopMargin(-1050.8960)
layout:setBottomMargin(1009.8960)
Node:addChild(labName)

--Create labChips
local labChips = ccui.Text:create()
labChips:ignoreContentAdaptWithSize(true)
labChips:setFontName("simhei.ttf")
labChips:setFontSize(24)
labChips:setString([[9999999999]])
labChips:setLayoutComponentEnabled(true)
labChips:setName("labChips")
labChips:setTag(181)
labChips:setCascadeColorEnabled(true)
labChips:setCascadeOpacityEnabled(true)
labChips:setAnchorPoint(0.0000, 0.5000)
labChips:setPosition(438.9241, 921.7850)
layout = ccui.LayoutComponent:bindLayoutComponent(labChips)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(180.0000, 41.0000))
layout:setLeftMargin(438.9241)
layout:setRightMargin(-668.9241)
layout:setTopMargin(-1012.2850)
layout:setBottomMargin(971.2850)
Node:addChild(labChips)

--Create nodeCard
local nodeCard=cc.Node:create()
nodeCard:setName("nodeCard")
nodeCard:setTag(182)
nodeCard:setCascadeColorEnabled(true)
nodeCard:setCascadeOpacityEnabled(true)
nodeCard:setPosition(960.0000, 829.6136)
layout = ccui.LayoutComponent:bindLayoutComponent(nodeCard)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setLeftMargin(960.0000)
layout:setRightMargin(-960.0000)
layout:setTopMargin(-829.6136)
layout:setBottomMargin(829.6136)
Node:addChild(nodeCard)

--Create sprReady
local sprReady = cc.Sprite:create("game/niuniu_std/resource/word/ready.png")
sprReady:setName("sprReady")
sprReady:setTag(187)
sprReady:setCascadeColorEnabled(true)
sprReady:setCascadeOpacityEnabled(true)
sprReady:setPosition(960.0000, 925.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(sprReady)
layout:setPositionPercentX(0.0000)
layout:setPositionPercentY(0.0000)
layout:setSize(cc.size(345.0000, 93.0000))
layout:setLeftMargin(787.5000)
layout:setRightMargin(-1132.5000)
layout:setTopMargin(-971.5000)
layout:setBottomMargin(878.5000)
Node:addChild(sprReady)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

