
--4S店
require "game.4s_std.data._init_4s_config"
require "game.4s_std.4s_manager"
require "game.4s_std.script.4s_mainscene"
require "game.4s_std.script.4s_banker"  
-- require "game.4s_std.script.4s_player"
-- require "game.4s_std.script.4s_record"
require "game.4s_std.script.4s_settleAccounts"
require "game.4s_std.script.4s_applyList"
require "game.4s_std.script.4s_chipsPanel"
require "game.4s_std.script.4s_rewardBitmap"
require "game.4s_std.script.4s_scrollItem"
require "game.4s_std.script.4s_rewardListBitmap"
require "game.4s_std.script.4s_rewardLotteryBitmap"
-- require "game.4s_std.script.4s_desk"
require "game.4s_std.script.net_message.send_foursshop"
require "game.4s_std.script.net_message.rec_pro_foursshop"
require "game.4s_std.script.net_message.rec_parse_foursshop"
